### ISSUE TITLE
Document how to change volumes drive

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver-doc#1006]
We should add to the FAQ some instruction to move an install to a separate drive.

This are the same steps as when doing a mountpoint on rpi4 https://docs.btcpayserver.org/Deployment/RPi4/

**Comment by pavlenex** [comment]
@NicolasDorier Could you clarify what this is referring to and which command should be used?

From what I understood, we should add mountpoint instructions from RPI4 doc into a FAQ, naming it `How to change volumes drive`?

**Comment by RowenPM** [comment]
I think I will take this on as I have done it a few times. I'll try to have a video as well as text form.

**Comment by pavlenex** [comment]
That would be great @RowenPM!

**Comment by dennisreimann** [comment]
That sounds kinda related to this one in the Deployment FAQ: [With the docker deployment, how to use a different volume for the data?](https://docs.btcpayserver.org/FAQ/Deployment/#with-the-docker-deployment-how-to-use-a-different-volume-for-the-data)

**Comment by petzsch** [comment]
This question came up this week on mattermost again. The user had a full harddisk, couldn't even turn on pruning as bitcoind would refuse to start.

Maybe if someone starts writing something mention things like LVM for future cases where you want to add more disk space to an existing logical volume?

**Comment by Bangalisch** [comment]
i'll take it :))

**Comment by NicolasDorier** [comment]
@dennisreimann it sounds this one yes

**Comment by dennisreimann** [comment]
Alright, maybe then @Bangalisch and @petzsch can collaborate on improving the [With the docker deployment, how to use a different volume for the data?](https://docs.btcpayserver.org/FAQ/Deployment/#with-the-docker-deployment-how-to-use-a-different-volume-for-the-data) FAQ entry.
