### ISSUE TITLE
Improve `Connect an existing wallet > Import wallet file` and recommend it instead of xpub import (Update Electrum Doc, video)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1026]
I think we should probably update instructions and create a quick video of people importing Electrum into btcpay also configuring the gap limit as part of the onboarding, it's less stressful. 

Also the onboarding should explain the wallet file import which then configures master key and keypath in btcpay, where as xpub import doesn't. Will add an issue in docs for this.

**Comment by Bangalisch** [comment]
Will be taken on by @webwworthy coming days :)
