### ISSUE TITLE
Add Voltage to deployment list (web deployment)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1038]
https://voltage.cloud/btcpay

**Comment by pavlenex** [comment]
Ben did a great video on it ,so we can embed it https://www.youtube.com/watch?v=KqsM-n-e4aY

**Comment by Bangalisch** [comment]
Would it be a good idea to split Web deployment ? 
So it would look like : 
- Web Deployment - pros/cons in short.
    -Luna Node 
    -Voltage deployment 
    -Any other Webdeploy out there 

Instead of right now having web deploy telling how to on Luna node and below it we would post Voltage? Lemmi know what ya think. 
I'll go ahead and chuck it into a PR ~2 days

**Comment by pavlenex** [comment]
Yes, probably Good idea to extract these 👍

**Comment by Bangalisch** [comment]
Can close after review on #1090 :)

**Comment by pavlenex** [comment]
Done in #1090, #1094 should be next
