### ISSUE TITLE
Create new Shopify Video

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1041]
After #1036 we should:

- [x] Create a new Shopify video
- [x] Replace old one in docs
- [x] Archive old video on YT

**Comment by gaurengames** [comment]
Got the wetransfers, working on it this week.

**Comment by webwworthy** [comment]
Update: The video is edited, I'm working on transcribing the audio and will re-record the voice over next. I should have this done in the next day or two.

**Comment by webwworthy** [comment]
@pavlenex video edited and exported @Bangalisch is uploading it and adding to YouTube

**Comment by Bangalisch** [comment]
Uploaded as unlisted for review. 
Ready to put out there whenever merged :) 

GG Parker!!

**Comment by pavlenex** [comment]
The video is perfect guys, great work! Feel free to publish it.

**Comment by pavlenex** [comment]
#1098
