### ISSUE TITLE
Coldcard MK4 video and docs

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1045]
We'll get MK4 to test and update our docs and video. This issue is to track a progress on that.

Old videos [Connecting Coldcard wallet to BTCPay Server](https://youtu.be/N0eVwdP_7EQ) / 
[Coldcard wallet and BTCPay Server - PSBT Sending from a wallet airgapped](https://youtu.be/oK0h-76Giaw)

- [ ] Decide if we want to merge two legacy videos into one and record a new video
- [ ] If we're making only a single video, see what other wallets can be used to record "PSBT in BTCPay video"
If we decide for two separate videos:
- [ ] Record a new "How to connect ColdCard to BTCPay" video
- [x] Record a new "How to use PSBT in BTCPay"

**Comment by dennisreimann** [comment]
Received mine today! 👍

**Comment by webwworthy** [comment]
Got mine as well!
