### ISSUE TITLE
Add better visual for the `UseCase.md` and provide visual examples of people using BTCPay

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1050]
Following up on #996 I think the infographic doesn't really convey information well, it looks odd and text-heavy. Instead of infographic, I suggest we add images of user-groups for paragraphs where this fits. This would include person using BTCPay point of sale app, online shop accepting BTCPay, freelancer requesting bill, etc. I think showcasing btcpay in a wild tells a better story than infographic.

**Comment by Bangalisch** [comment]
Yo yo 

Let's pick this one up coming week. 
Did some exploration with @webwworthy but like to know a bit more of the scope of it and input in general. 
Here's a first set of mocks we did : 

![btcpayUSECASE](https://user-images.githubusercontent.com/102448109/190910665-58976354-24d0-4981-bedc-44a3808a0c57.jpg)

**Comment by dstrukt** [comment]
Looking good!

Will take a look and try to chime in with some thoughts when I get a moment this weekend.

**Comment by webwworthy** [comment]
@Bangalisch

**Comment by webwworthy** [comment]
@dstrukt @Bangalisch yoo back working on this graphic, what do you think of these updates? added a few more sections to show more payment / invoices than crowdfunding. Maybe could still use a POS / key pad section and say something about apps and plugins. 

![BTCPay UseCase-v2](https://user-images.githubusercontent.com/95507488/228320175-5c77882e-4943-4f10-8f35-a449dc6f5c91.png)

with guides 

![BTCPay UseCase-wGuides](https://user-images.githubusercontent.com/95507488/228320374-5ae5afcb-60c5-4e0a-9552-903dbf55fc38.png)

**Comment by webwworthy** [comment]
@Bangalisch @dstrukt @pavlenex 

I think I found a much better way to show this then the previous one I posted on Feb 21st. Here is comparison to old and grid system. 
![Use-Cases-BTCPay](https://user-images.githubusercontent.com/95507488/230129680-907368f9-3a43-41d2-bc57-600aed2d6e76.PNG)

---

![BTCPay UseCase](https://user-images.githubusercontent.com/95507488/230129710-7f78d993-ae34-4819-baa4-de4a33d72f76.png)

**Comment by pavlenex** [comment]
LGTM, much cleaner great work @webwworthy !

**Comment by dstrukt** [comment]
Discussed this a bit in today's unofficial design call.

Realizing some of the screenshots could be improved a bit (some inconsistencies), but got access to the Figma, will do my best to swap them ASAP so we can get this sent off -- great job @webwworthy.

**Comment by webwworthy** [comment]
thanks @dstrukt! pumped that looks good and appreciate any improvements on it

**Comment by webwworthy** [comment]
yo! latest updates on the use case infographic are in my PR, please review @dstrukt @pavlenex @Bas02
