### ISSUE TITLE
Improve Magento.md

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1051]
Right now our Magento doc is pretty empty and only mirrors BitPay's readme.
We should re-write it.

**Comment by Bangalisch** [comment]
Will start looking into this. 
It's also no longer called Magento but Adobe eCommerce :)

**Comment by pavlenex** [comment]
Overwritten by https://github.com/btcpayserver/btcpayserver-doc/issues/1352
