### ISSUE TITLE
Payout Support / Docs

### ISSUE THREAD

**Issue by lylepratt** [btcpayserver/btcpayserver-doc#106]
Is the BitPay Payouts API supported by BTCPayServer? Specifically, this functionality: 
https://bitpay.com/api#resource-Payouts

I can’t find the documentation for the REST api of BTCPayServer, so I’m assuming it’s an exact match?

Thanks for the help!

**Comment by lylepratt** [comment]
Interesting. Thanks for the information! The reason I'm asking is because I'd like for an app to be able automatically relay funds to various addresses when certain conditions are met.

**Comment by bitcoinshirt** [comment]
As Kukks mentioned, BTCPay does not have a hot-wallet, which means that there's no way to send out, without signing a transaction with a hardware wallet.

The hot-wallet feature is something that may be implemented in future. It should help with fiat-crypto instant exchanges and few other things.

**Comment by bitcoinshirt** [comment]
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.
