### ISSUE TITLE
Improve BTCPay Server and Shopify Integration

### ISSUE THREAD

**Issue by Satsamoon** [btcpayserver/btcpayserver-doc#1063]
I could not find the information I was looking for on the "BTCPay Server and Shopify Integration" page (`/Shopify/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]
Hi, really hoping someone can help: We have btcpayserver recently integrated into our website on Shopify. 
When ordering an item, it works to pay the BTCpay invoice, but once paid and you click 'Close' on the invoice, it takes you back to the website order page saying 'Review and Pay'.

This would of course confuse the customer. Also, in our Shopify backend under orders, it says payment pending... it does not recognize the btcpayserver invoice was paid for the order.

We assume we need to add some more API integrations under Store Settings in our BTCpay account?

We followed all directions exactly when setting up, not sure if we missed something?

We set up BTCpay through Voltage and we asked them but they weren't able to help with this.

When doing the Shopify integration, we noticed the screenshots guiding you through are outdated as they looked different than what we were seeing as we did it. Wondering if perhaps Shopify updated something that is not yet reflected in the BTCPay Shopify Integration guide?

[4:49 PM](https://chat.btcpayserver.org/btcpayserver/pl/rd8gz7iy67d17nyd5z99fg3euh)

We checked FAQs but havent been able to find an answer to the issues above. When clicking on 'Instructions for getting support' and then "Frequently Asked Questions' it went to a 404 error page. 

Would much appreciate any advice thanks!

**Comment by pavlenex** [comment]
Replied on Mattermost. Please don't post support issues on GitHub doc repo.

**Comment by pavlenex** [comment]
@Satsamoon no worries, we released a fix follow new doc here and update your btcpay 1.4.8 

https://docs.btcpayserver.org/Shopify/
