### ISSUE TITLE
Improve Apps FAQ

### ISSUE THREAD

**Issue by jmburch921** [btcpayserver/btcpayserver-doc#1077]
I would like some help recovering my node.  Jburchpga@gmail.com 
Enlightened.co.page 
last_update": 1648726114, "pub_key": "02e7cda15016259bdd4cb50dd49a55d6766f30443e2ed9ed909f47e2f666303e65", "alias": "enlightened", "addresses": [ { "network": "tcp", "addr": "4iuwittravvnsww45tnqtvbv7kswnhxnkb3hqnxctvnvh64sj7vcvlyd.onion:9735" } ], "color": "#68f442", "capacity": 10356752, "channelcount": 6, "noderank": { "capacity": 3380, "channelcount": 4265, "age": 3797, "growth": 4874 } }
I am positive I set up the server here.

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by pavlenex** [comment]
You should post this on whatever lightning implementation repository you're using. For LND for example, their recovery process is documented here https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md

This is documentaiton repository and not support forum.
