### ISSUE TITLE
Add dashboard tab in user documentation for release 1.5

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver-doc#1082]
Alot of change coming to release 1.5 in regard to Dashboard. 
It should be added to the user documentation on its own page. 
 

- [x] brief introduction to Dashboard as its own page in documentation. 

- [ ] Short introduction video?

**Comment by Bangalisch** [comment]
PR #1083

**Comment by pavlenex** [comment]
Don't think we need a video for this one for now, so closing since it's added in #1083 by @Bangalisch 🎉
