### ISSUE TITLE
Add DreamLab Network as a web-deployment option

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1094]
A new provider just started offering btcpay VPS easy deployments. Very nice experience, and quite easy. 

https://dreamlabnetwork.solutions/btcpay-servers.php

Whoever wants to document it, they can offer us a coupon code for a free instance to test things out and write docs.

**Comment by pavlenex** [comment]
Should be done ideally after https://github.com/btcpayserver/btcpayserver-doc/issues/1038

**Comment by Bangalisch** [comment]
After review on #1108 this might close ^^

**Comment by pavlenex** [comment]
#1108
