### ISSUE TITLE
[Proposal] Adding video Subtitles and how to store them

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver-doc#1102]
Yo, 

Just added the ENG sub titles to the Shopify video ( https://www.youtube.com/watch?v=jJjAyvgWVfk&t=80s ) 
Maybe it's a good thing, as we transcribe the video's and do voice overs, to add these as sub titles to any broader video ( and short ones) 

After it's done in voice over we have the ENG transcript of the video, these get put on the video and timed right. 
Now the tekst, exists in clear, sentence by sentence englisch, it could be a quick rewrite into another language ex Spanish. 
It would be good for the Video's like shopify or the What is BTCPay Server to have those with multiple sub titles. 

It could be an option to add a folder with YT translations to the Docs repo. 
DOCS
- YouTube Subtitles.
   - Shopify 
      - ENG
         - eng.txt
      - ESP
      - NL
      - ETC
   - What is BTCPay server? 
      - ENG
      - ETC
      - ETC

**Comment by Bangalisch** [comment]
To make things a little more clear how and why this could be useful. 
Before we used https://www.transifex.com/ this requires this similar setup on a git repo. 

This was used on the website as well so the collaboration was a lot smoother. 
Multiple people can work on the same text without disturbing the other. 

 https://github.com/btcpayserver/btcpayserver.org/tree/master/transifex
