### ISSUE TITLE
Account locked Improve (1) Register account

### ISSUE THREAD

**Issue by Danielalui** [btcpayserver/btcpayserver-doc#1111]
I could not find the information I was looking for on the "(1) Register account" page (`/RegisterAccount/`).

My account got locked. I requested a new password but haben't received an email.

**Comment by Danielalui** [comment]
https://btcpay.btc-boutique.com/login/forgot-password

**Comment by Bangalisch** [comment]
This is not something BTCPay Server can fix. 
BTCPay is the software, used by btc-boutique. 

Their adimistrator needs to set a mail server for this. 
Please contact them :)

**Comment by Danielalui** [comment]
Sorry to ask again but I use Lunanode as hosting. And https://btcpay.btc-boutique.com/login/ is just for the login. 
When I set it up using the launchpad https://launchbtcpay.lunanode.com/ I selected the option attached. Maybe you can point me in the right direction how I can recover my account?
<img width="430" alt="luna" src="https://user-images.githubusercontent.com/59447274/168229233-e25ce076-bb68-471b-93cf-829288bc16ec.png">

**Comment by pavlenex** [comment]
If you forgot admin password and you're admin you'd have to follow this https://docs.btcpayserver.org/FAQ/ServerSettings/#forgot-btcpay-admin-password
