### ISSUE TITLE
Describe howto use mod_proxy (or nginx equivalent) to forward non-btcpay lnurl addresses to btcpay

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1117]
The question on telegram was:

> is there a way for me to use my main domain.tdl with my lnurl without a subdomain and not have to change the A record for my current domain that is pointing to my cms server?

And apparently this can be done with mod_proxy (Apache):

Here is an example config:

```
SSLProxyEngine On
ProxyPass "/.well-known/lnurlp/USERNAME"  "https://your.btc-pay.server.tld/.well-known/lnurlp/USERNAME"
ProxyPassReverse "/.well-known/lnurlp/USERNAME"  "https://your.btc-pay.server.tld/.well-known/lnurlp/USERNAME"
```

Perhaps we can ommit the USERNAME part and make it work for any usernames created on that server. Needs to be tested.

If we decide to add this to the documentation (not sure where exactly), we should also include an example for nginx I think.

**Comment by dennisreimann** [comment]
I recently added this, see btcpayserver/btcpayserver-doc#1107

**Comment by petzsch** [comment]
So sorry. Should habe checked the docs first. 301 redirect is even simpler.
