### ISSUE TITLE
Document how to fetch exchange rates

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver-doc#1124]
Seems we did not document that /api/rates?storeId=xxx endpoint yet. 

https://chat.btcpayserver.org/btcpayserver/pl/wow8skk5p7y4ue7foso16gh8ch

**Comment by pavlenex** [comment]
Is this the API docs you're referring to? Probably should be opened in the main repo then.

**Comment by ndeet** [comment]
It is kinda legacy api inspired by BitPay but in our case scoped to the store and configured pairs (https://testnet.demo.btcpay.tech/api/rates?storeId=46y7JuD7dUHEN1BxeAmtReA5zjUzSho7HVXVteQr1XUW). So yes maybe good to add it to Greenfield too. Seems we never documented the existing one. So I just added the issue if someone wants to get started contributing to pick up low hanging fruit.

Feel free to move it to main repo or let me know if I should open an issue there.

**Comment by pavlenex** [comment]
Yeah, I just don't know where should we document this or how to proceed?

**Comment by ndeet** [comment]
We could put that information here https://docs.btcpayserver.org/CustomIntegration/ (which also needs some overhaul and make clear that BitPay is the legacy API and GF is the way to go).
