### ISSUE TITLE
Joomla VirtueMart Video

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#1134]
When the JM integration gets enough tests eyes and is fully ready we should creat a video to demonstrate it 

https://docs.btcpayserver.org/VirtueMart/

**Comment by Bangalisch** [comment]
Will be taken care of :)

**Comment by Bangalisch** [comment]
https://www.youtube.com/watch?v=k7XfybLAky0 

Can be closed :D
