### ISSUE TITLE
Create a dedicated Doc page for Webhooks

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1142]
Perhaps we can add some example code like the one from the php greenfield client as well? It always helps me with custom integrations to get this working: https://github.com/btcpayserver/btcpayserver-greenfield-php/blob/master/examples/webhook.php

**EDIT:** Might also wanna explain the different types of webhooks, show an example payload(might be to much for a FAQ entry) and explain the difference over the old NotificationURL from the Bitpay compatible API.

_Originally posted by @petzsch in https://github.com/btcpayserver/btcpayserver-doc/issues/1140#issuecomment-1159129088_

Originiated from issue #852

**Comment by pavlenex** [comment]
@petzsch  did #1164 address this or is there more to it that we'd like to do?

**Comment by petzsch** [comment]
since I was able to sneak in my example script in #1164 ...
pretty much satisfied with the outcome.

Closing this one.
