### ISSUE TITLE
Issue trying to pair with btcpayserver and Magento 2 plugin

### ISSUE THREAD

**Issue by stifboy** [btcpayserver/btcpayserver-doc#115]
I have setup  [this](https://github.com/CreamyG31337/magento2-plugin) extension but it does not seem to to pair with Btcpayserver using Magento 2.2.6

**Comment by Kukks** [comment]
This is the wrong place to post this.

**Comment by bitcoinshirt** [comment]
It looks like you already have the discussion going on several places, so I'll close this issue since it's opened in the wrong repository anyway. Should you need further assistance feel free to join us on slack or re-open the issue in appropriate repository.
