### ISSUE TITLE
Rewrite Fast sync documentation + examples

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver-doc#1153]
Yoooo

This is more a reminder then anything else. 
But it would be very nice to rewrite the Fast sync Signing documentation. 

https://docs.btcpayserver.org/Docker/fastsync/#fast-sync-for-bitcoin

**Comment by pavlenex** [comment]
@Bangalisch Is this completed with https://github.com/btcpayserver/btcpayserver-docker/pull/685 merged?
