### ISSUE TITLE
undocumented feature: Email Rules

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1173]
On https://docs.btcpayserver.org/Notifications/#user-emails there is no mentioning of the new email feature.

We could also describe how the placeholders work (list of available placeholders from code: [here](https://github.com/btcpayserver/btcpayserver/issues/4112))

Question came up on Telegram.

**Comment by ProTechEx** [comment]
**Yeah that would be great !**
