### ISSUE TITLE
LunaNode Deployment Docs Should Have a step to specify BTCPAYGEN_CRYPTO1

### ISSUE THREAD

**Issue by asoltys** [btcpayserver/btcpayserver-doc#1174]
I had to `export BTCPAYGEN_CRYPTO1=btc` before running the btcpay-setup.sh script

**Comment by Bangalisch** [comment]
Yo yo 

looked into why this would happen, the only thing i can assume so far ; 
You used [launchbtc](https://launchbtcpay.lunanode.com/) entered ur API key etc. 
Then on the deployment configuration page, you didn't select a single coin and thus didnt deploy with this variable set :) 

thanks for reporting!
We'll file a improvement to LunaNode and i'll follow up in this issue when they respond :)
