### ISSUE TITLE
update Connect Wasabi guide to Wasabi 2.0

### ISSUE THREAD

**Issue by MarnixCroes** [btcpayserver/btcpayserver-doc#1176]
I'll fix this
waiting for a small UX change for creating a new wallet. which should be changed soon

**Comment by MarnixCroes** [comment]
> waiting for a small UX change for creating a new wallet. which should be changed soon

selecting a coinjoin strategy might be removed from default UX.
It might have been in the new major release last week, however it didn't happen (yet)

**Comment by Bangalisch** [comment]
Would you want to wait for it or is this where you decided to just push it now and that update will follow later or so =D? 

Otherwise, PR looks good :)

**Comment by MarnixCroes** [comment]
> Would you want to wait for it or is this where you decided to just push it now and that update will follow later or so =D?

yes. it got frozen.  so consider my comment as discarded. :) 
removing it from the UX will probably not happen in next couple of months.

I'll update when it has changed
