### ISSUE TITLE
Improve Support

### ISSUE THREAD

**Issue by CarlaAustin1** [btcpayserver/btcpayserver-doc#1182]
I could not find the information I was looking for on the "Support" page (`/Support/`).

A couple of weeks ago or so, I am not sure of the exact date, but I already paid the fees that I was asked to pay, all fees except the final $33 and that is an estimation. I believe the fee was $36 and I paid $2 or $3 of it. And now it is asking me to pay again. I cannot pay again. But I have proof in my cashapp of the fees I paid and screnshots too. How can I pay the remaining $33 or so and receive my funds? Thank you

**Comment by pavlenex** [comment]
you need to contact the merchant, BTCPay is only the software the merchant used to processing the payments but we can't do anything you need to solve this with the merchant

we have heard from a lot of scams the last few weeks (bitcoin bonus etc:), if someone promised you a big reward to pay out but you need to pay fiirst some processing fees - it is a SCAM and your money is gone

nobody gives away free money, if it sounds too good to be true then it likely is

**Comment by LilDaffy** [comment]
I was told it was a payment for my mining account. I've made 3 payments of a total of about 170. How cam someone do something like this on your server and get away with it. That was money I needed. It's not right.

**Comment by pavlenex** [comment]
It's not OUR server, it's THEIR server. We're just making a software read this https://docs.btcpayserver.org/FAQ/General/#what-if-i-have-a-problem-with-a-paid-invoice
