### ISSUE TITLE
Improve How to accept Bitcoin in Shopify

### ISSUE THREAD

**Issue by chris-pollard** [btcpayserver/btcpayserver-doc#1183]
I could not find the information I was looking for on the "How to accept Bitcoin in Shopify" page (`/Shopify/`).

Wondering if there is a fallback label/button that shows when and if BTCPay server is down. I run a self-hosted one and it was down today. Someone put through an order and there was just no button from the shopify confirmation page, which is confusing for customer.

**Comment by pavlenex** [comment]
This isn't really an issue for documentation ,but @ndeet what do you think about this?

**Comment by ndeet** [comment]
Hey, I'm not sure how Shopify renders the payment button but if they somehow ping the payment provider URL and hide it when it is down/erroring then likely we can't do much. I have no clue how the Shopify integration works though as it is built on BTCPay not via the API as the others. So maybe @Kukks has an idea how we could handle this edge case and output something like "Payment method not available" instead.
