### ISSUE TITLE
Waiting /root/.nbxplorer/btc_fully_synched to be created...

### ISSUE THREAD

**Issue by AsBobbyDigital** [btcpayserver/btcpayserver-doc#1231]
Hello,

After updating to v12 my node was stuck syncing on 99%. Do you have any idea what the issue is?

alias=AlphaNode added to /data/lnd.conf
LND_CHAIN=btc
LND_ENVIRONMENT=mainnet
Added bitcoin.active and bitcoin.mainnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/btc_fully_synched to be created...

**Comment by pavlenex** [comment]
Unerelated for doc repo
