### ISSUE TITLE
New video explaining BTCPay Vault + HWW 

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver-doc#1232]
Yo

We need to redo the BTCPay Vault video. The current video Vault dates back a long time, is fairly long and shows a very old work flow. 
Vault should also get this same short format overhaul as we're updating video content. 

Current video : 
https://youtu.be/hh_cm8MKl2g 

We've received a Blockstream Jade device and should use this as demo HWW.

**Comment by webwworthy** [comment]
@Bangalisch

**Comment by Bangalisch** [comment]
https://github.com/btcpayserver/btcpayserver-doc/pull/1239 closes this :) Well done @webwworthy !
