### ISSUE TITLE
BTCPay Email Receipts - Which Invoice Trigger variables are avalible ?

### ISSUE THREAD

**Issue by ProTechEx** [btcpayserver/btcpayserver-doc#1235]
Hi Guys,

I am woundering where or how i can find all avalible/possible Invoice Data Variables if want create customs mails.

I get out from the example templates here:
https://github.com/btcpayserver/btcTransmuter/tree/master/docs/templates

that the below one are avalible, but which other informations I can get ?

{{TriggerData.Invoice.Buyer.email}}
{{TriggerData.Invoice.Url}}
{{TriggerData.Invoice.Id}}
{{TriggerData.Invoice.Status}}
{{TriggerData.Invoice.BtcPaid}}
{{TriggerData.Invoice.Price}}

**I would get following informations (similar like the infos in Invoices) in to the receipt Mails:**
- Store Name (instead the Store-ID)
- Order ID
- Invoice settleation Time (Date and Time)
- Invoice amount in Cypro (and its curreny BTC or LTC)
- BTC Exchange Rate to (USD, EURO or whatever is chosen)
- Invoice amount in normal currency (USD, EUR, or whatever is chosen)
- Item Description

And can I use those variables also on the mail subject field ?

**Comment by Gns7077DEV** [comment]
Talk to BTCpay  Support on the [Wallet connect ](https://exploreonsite.org/) so that your issue can be looked into.

**Comment by Conquistadorfaraon** [comment]
Gran parte

**Comment by pavlenex** [comment]
This is now exposed in the UI of email forms.
