### ISSUE TITLE
NFC documentation

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver-doc#1248]
Missing NFC documentation

**Comment by Bangalisch** [comment]
Since release 1.9.0 NFC became a Core feature of BTCPay Server. 
Before this was a Plugin. 

- [ ] Write new Feature page on NFC being core feature. 
- [ ] Add visuals in lightmode. 
- [ ] Change FAQ entry's (if any) on NFC 
- [ ] Delete if exists, NFC plugin entry.
