### ISSUE TITLE
Improve Trocador

### ISSUE THREAD

**Issue by olupeter95** [btcpayserver/btcpayserver-doc#1249]
I could not find the information I was looking for on the "Trocador" page (`/Trocador/`).

[HOW CAN I INSTALL THE PLUGIN IN TESTNET?]

**Comment by pavlenex** [comment]
You'd have to ask plugin author and post question there, this plugin is not developed by btcpay core team. https://github.com/saltrafael/trocador-plugin/tree/39ffea2855e158a77a33018bd0ec08dcf2f74a41/BTCPayServer.Plugins.Trocador

**Comment by olupeter95** [comment]
Alright thanks for the swift response
