### ISSUE TITLE
Improve Deploying BTCPay - LunaNode Web-Wizard

### ISSUE THREAD

**Issue by GriffinHines** [btcpayserver/btcpayserver-doc#1250]
I could not find the information I was looking for on the "Deploying BTCPay - LunaNode Web-Wizard" page (`/Deployment/LunaNode/`).

Do I need to setup certbot or an alternative to access my site with https?

**Comment by dennisreimann** [comment]
I think LunaNode uses our Docker deployment. In that case you don't have to do anything, because certbot is part of that stack and SSL gets handled automatically.
