### ISSUE TITLE
Improve Forms

### ISSUE THREAD

**Issue by Goro2030** [btcpayserver/btcpayserver-doc#1257]
I could not find the information I was looking for on the "Forms" page (`/Forms/`).

I'm trying to create a form that will present the user "options", for delivery of products at a restaurant. I need to be able to present the main default option that's "Instant Delivery", that would be preselected, and then a 2nd Option that's "Scheduled delivery", that if selected (the radio button maybe), will allow the user to enter text of when they want the food delivered.

I've tried this, to no avail... any ideas?
{
  "topMessages": [],
  "fields": [
    {
      "name": "buyerEmail",
      "constant": false,
      "type": "email",
      "value": null,
      "required": true,
      "label": "Enter your email",
      "originalValue": null,
      "helpText": "This is help text",
      "validationErrors": [],
      "fields": []
    },
    {
      "name": "deliveryOption",
      "constant": false,
      "type": "select",
      "value": "false",
      "required": true,
      "label": "Delivery Option",
      "originalValue": null,
      "helpText": null,
      "validationErrors": [],
      "options": [
 {
          "text": "Entregar pedido YA",
          "value": true,
          "type": "radio"
        },
        {
          "text": "Pedido programado",
          "value": false,
          "type": "radio"
        }
],
      "fields": [
        {
          "text": "Entregar pedido YA",
          "value": true,
          "type": "radio"
        },
        {
          "text": "Pedido programado",
          "value": false,
          "type": "radio"
        }
      ]
    }
  ]
}

**Comment by Kukks** [comment]
Select support is coming in 1.9, although we have not planned for conditional inputs yet.

**Comment by pavlenex** [comment]
It's available now, can we try it and close this issue if it works @Goro2030 ?

**Comment by Goro2030** [comment]
It is working now, I'll close the issue.

BTW: Where's the documentation of how to use the forms? The site https://jsonformatter.org/json-parser may help with the creation of the layout, but the syntax is very cryptic for a normal user, and a little guide would help_

**Comment by pavlenex** [comment]
We should be adding a UI in the next release.
