### ISSUE TITLE
Improve Connecting Wasabi Wallet to BTCPay Server

### ISSUE THREAD

**Issue by PRETTYPET69** [btcpayserver/btcpayserver-doc#1261]
I could not find the information I was looking for on the "Connecting Wasabi Wallet to BTCPay Server" page (`/WasabiWallet/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by pavlenex** [comment]
Not enough context, closing until more context is provided.
