### ISSUE TITLE
I sent my payment but it still shows I haven't


### ISSUE THREAD

**Issue by RexLance** [btcpayserver/btcpayserver-doc#1266]

**Comment by RexLance** [comment]
I set my payment to QSBT mining's side but it doesn't show They have received it

**Comment by pavlenex** [comment]
Read this. It's a scam https://blog.btcpayserver.org/bitcoin-bonus-scam/

**Comment by RexLance** [comment]
Everything I researched on qs btminings came back good.  But if you knew it
was an illegitimate Scam why Was it allowed to continue Does b Keyshie pay
server do anything To prevent scamming. If not I guess I understand why
it's not very big and Nobody wants to use you.
