### ISSUE TITLE
FAQ: Deadlink on Lightning FAQ & outdated medium.com article being linked to

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1273]
On this question: https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-can-i-get-inbound-capacity-to-my-node

we link to "This document": https://wiki.ion.radar.tech/tutorials/bootstrapping-liquidity
which doesn't exist anymore.

Also the medium.com article above it is from Jan 2019 and very outdated. Maybe we can find a better source or write something ourselves?

**Comment by pavlenex** [comment]
Seems this was addressed as it links to https://medium.com/lightningto-me/practical-solutions-to-inbound-capacity-problem-in-lightning-network-60224aa13393
