### ISSUE TITLE
Lightning Network and BTCPay 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#128]
Record a video that will show people how to use LN. We now have a technical video, but there are no videos beyond installation. I'd like to show users how to use Zap and maybe even c-lightning command line, but in two separate videos.

- [x] Deploying Lightning Node (BTCPay LunaNode)
- [x] Cover the risks
- [x] Connecting to Zap
- [x] Open a channel
- [ ] Make a payment
- [ ] Request a payment
- [ ] Closing a channel
- [ ] Troubleshooting

**Comment by Eskyee** [comment]
BTCPay LND + Zap 

BTCPay c-lightning + Spark

Desktop & Mobile phone versions

Can we also explain to noobs how to fund your lightning, wallet etc etc..

 thanks pavlenex 
excellent videos ;)

**Comment by leshik** [comment]
Also it would be nice to know of pros and cons of different lightning implementations.

**Comment by britttttk** [comment]
Since this issue has been open for some time... @pavlenex I can try it starting with LND

> Deploying Lightning Node (BTCPay LunaNode)

Which do you prefer?
- During initial install
- Adding to existing
- Both

> Cover the risks

Cover the information shown in the LN warnings in btcpay?

> Troubleshooting

Some logs and check your node is connected? Try the magic command btcpay-restart.sh :)

**Comment by pavlenex** [comment]
@britttttk awesome
> Both
Well during the initial instal, then you can show how to initiate if you haven't done it in the initial install

> Cover the information shown in the LN warnings in btcpay?
Yup, exactly.

> Some logs and check your node is connected? Try the magic command btcpay-restart.sh :)

Hm, maybe we can point them to docs for that one, but if you feel it's necessary, sure, include it as well, your call.

**Comment by pavlenex** [comment]
@britttttk do you plan to tackle rest of the points? 

I have a mixed feeling if it's needed, because the current UI of the wallets and RTL make these things quite obvious, what do you think?
