### ISSUE TITLE
Improve BTCPay Server Apps

### ISSUE THREAD

**Issue by Teasleydunn** [btcpayserver/btcpayserver-doc#1281]
I could not find the information I was looking for on the "BTCPay Server Apps" page (`/Apps/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by Teasleydunn** [comment]
Look I was told to make my $64 dollar payment after converting Bitcoin currency to USD  and it sent me to this address am there's a copy of payment on here to Bitcoin pay and they were going to put the rest on Visa coinbase card that's all I know

**Comment by dennisreimann** [comment]
Please do not pay, it's a scam. See this blog post for details: https://blog.btcpayserver.org/bitcoin-bonus-scam/
