### ISSUE TITLE
Uninstall Script in FAQ maybe?

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1285]
Didn't find it when I searched for it but apparently there is something:
https://docs.btcpayserver.org/FAQ/Deployment/#how-do-i-completely-uninstall-btcpay-from-a-linux-environment-docker-version

Should/could we mention the script @dennisreimann made here?
btcpay-teardown.sh

Thx.

**Comment by dennisreimann** [comment]
Yeah, that would be a good fit 👍
