### ISSUE TITLE
WooCommerce Deploy from BTCPay : No Way to Install/Login

### ISSUE THREAD

**Issue by me639276639936** [btcpayserver/btcpayserver-doc#1289]
In the last section of https://docs.btcpayserver.org/WooCommerce/#2-connecting-woocommerce-and-btcpay-server "Deploying WooCommerce from BTCPay Server" I followed the instructions.

However, when I go to the URL, it does not take me to the WordPress installation wizard. Instead it directs me to login to my btcpayserver dashboard. I tried remapping things and running btcpay-setup but nothing changed.

Woocommerce does show up in my server settings -> services -> external services though.

Ideas?

**Comment by dennisreimann** [comment]
When you use the "See information" link for WooCommerce in the Server Settings > Services section – does that work? 

If not, can you check the nginx logs on the server?

`docker logs nginx`

**Comment by me639276639936** [comment]
Clicking the settings link just takes me to the URL but it doesn't take me to a Word Press setup. The URL just becomes a standard login for the server. Logging in does not take me to a Word Press setup either.

Here are the logs

--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /login?ReturnUrl=%2F HTTP/2.0" 200 13022 "-" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /main/bootstrap/bootstrap.css?v=FN3p6PzCSAk8E4idJN7AvUAnIoFpSSkg0aPxlxpHH1g HTTP/2.0" 200 44739 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /main/themes/default-dark.css?v=rO6dCF1I9RKaIzBzAaWGoheBmdhpJd_G9rObTvv5t3g HTTP/2.0" 200 525 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /main/themes/default.css?v=uyq_2fqV0m5eyxCS1LRCBJAXgXkxp41hSz2wqmEYbLM HTTP/2.0" 200 3158 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /main/site.js?v=6cdRaAmbRB7uCApbqlLlOc_Zf2YcrGnYdjlFx3WzJ8I HTTP/2.0" 200 4738 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /main/site.css?v=tVjyz9bDSW6VT4WxVwi_0XMrCH_ZKs_cp7SPZPwYoJE HTTP/2.0" 200 6859 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"
--URLCENSOREDBYME-- --ipCENSOREDBYME-- - - [03/Jun/2023:14:36:03 +0000] "GET /img/icon-sprite.svg?v=640O-w0pFRLfkh_rKQXfpmFpVsVV38fLwBb4w4iOog8 HTTP/2.0" 200 19121 "https://--URLCENSOREDBYME--/login?ReturnUrl=%2F" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36"

**Comment by dennisreimann** [comment]
@me639276639936 Did you set up the `WOOCOMMERCE_HOST` environment variable as [described here](https://docs.btcpayserver.org/WooCommerce/#deploying-woocommerce-from-btcpay-server)? If so, can you confirm the URL in the BTCPay services list matches that value?

If the above works correctly, can you post the output of the Woocommerce Docker logs? `docker logs generated_woocommerce_1`

**Comment by me639276639936** [comment]
Yessir, I used the setup described there. The URL matching the value.

woocommerce docker logs as this repeated multiple times:

"exec /usr/local/bin/docker-entrypoint.sh exec format error"

**Comment by dennisreimann** [comment]
Are you running on an arm32v7 architecture? The `exec format error` looks liek that and the WooCommerce image isn't compatible with that architecture. ([see the support table](https://github.com/btcpayserver/btcpayserver-docker#support))

**Comment by me639276639936** [comment]
It is 64 bit arch

**Comment by ndeet** [comment]
Hey @me639276639936 can you give more details about your OS and arch you run this on? E.g. Ubuntu 22.04 LTS on x86_64; also your docker version would be interesting, thank you.

**Comment by me639276639936** [comment]
It is an RPI4b running Debian GNU/Linux 11. Docker version 20.10.16, docker API version 1.41

**Comment by dennisreimann** [comment]
Can you provide us the output of `docker compose version` and `docker info`?

**Comment by me639276639936** [comment]
please see image below

![IMG_0123](https://github.com/btcpayserver/btcpayserver-doc/assets/134018025/1a4457a0-fb30-4e8c-bde7-0a34c4732f90)

**Comment by ndeet** [comment]
@NicolasDorier not sure but shouldn't the [upstream wordpress image](https://hub.docker.com/_/wordpress) automatically detect and select the correct image? (see also [this](https://stackoverflow.com/a/70734495))

The dockerfile from us just ensures there are some php extensions available and sets everything up.

**Comment by me639276639936** [comment]
So I was working on a separate issue and it looks like my arch is aarch64 but my bash environment is 32bit… so that could be contributing to this. RPIs are fun that way.
