### ISSUE TITLE
Improve Frequently Asked Questions and Common Issues

### ISSUE THREAD

**Issue by Kstar68** [btcpayserver/btcpayserver-doc#1291]
I could not find the information I was looking for on the "Frequently Asked Questions and Common Issues" page (`/FAQ/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by Kstar68** [comment]
Is there any way to get a refund

**Comment by dennisreimann** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/
