### ISSUE TITLE
Wrong path in crontab automation

### ISSUE THREAD

**Issue by n1kcha** [btcpayserver/btcpayserver-doc#1292]
crontab backup automation fails because it cant find btcpay-backup.sh
BTCPayServer folder is not included in this command. It should be:

`15 4 * * * /root/BTCPayServer/btcpayserver-docker/btcpay-backup.sh >/dev/null 2>&1`

and not be

`15 4 * * * /root/btcpayserver-docker/btcpay-backup.sh >/dev/null 2>&1`

**Comment by ndeet** [comment]
Thanks for reporting. It really depends on how and when you did the setup. And you are right we suggest the path you mentioned above in our [installation docs](https://docs.btcpayserver.org/Docker/#full-installation-for-technical-users).

@dennisreimann 
We are a bit inconsistent in the docs it seems. I think we need to do two things
1) fix the backup guide to match the installation instructions linked above
2) update the [backup guide](https://docs.btcpayserver.org/Docker/backup-restore/) and tell user to do an  `echo $BTCPAY_BASE_DIRECTORY` to be sure it is the correct path

What do you think? Will open an pr then.

**Comment by Sintayew4** [comment]
#1292
