### ISSUE TITLE
Add Sparrow as a recommended wallet in FAQ Gap limit solution. 

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver-doc#1295]
We should look at the wallet around and see if there's more to add here; 

"The only wallets that allow gap-limit configuration, that we're aware of are [Electrum](https://docs.btcpayserver.org/ElectrumWallet/) and [Wasabi](https://docs.btcpayserver.org/WasabiWallet/)"

On page ; 
https://docs.btcpayserver.org/FAQ/Wallet/#the-gap-limit-solution

AFAIK Sparrow wallet also allows it ; 
https://github.com/sparrowwallet/sparrow/issues/10#issuecomment-689545787

**Comment by pavlenex** [comment]
Resolved by https://github.com/btcpayserver/btcpayserver-doc/pull/1375 alrerady
