### ISSUE TITLE
Link to Alby How To "Connect to BTCPay Server"

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver-doc#1296]
Alby has a guide on how to [Connect to BTCPay Server](https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-lightning-account/connect-your-alby-lightning-account-to-other-apps/connect-to-btcpay-server) which we can link to.

**Comment by AryanJ-NYC** [comment]
@dennisreimann do you have an updated link? This one is broken.
