### ISSUE TITLE
Add examples for greenfild API in react and nextjs + answer the payment processing fee 

### ISSUE THREAD

**Issue by A7DC** [btcpayserver/btcpayserver-doc#1297]
Hi so first of all just wanted to say I am not the greatest developer in the world so my apologies.

Some examples of how to do things with the greenfield API in a react or nextjs project would be helpful.

We have a project where payments are akin to a gambling app where we take 10% of transactions and 10% when a user withdraws from our platform.

But reading the documentation I do not have a clue how this is possible using greenfield - or how anything is possible really.

```[tasklist]
### Tasks
- [ ] Add examples for greenfield in react and nextjs
- [ ] Make sure to cover payment processing fee part in docs
```

**Comment by Jtpj2017** [comment]
> Hi so first of all just wanted to say I am not the greatest developer in the world so my apologies.
> 
> Some examples of how to do things with the greenfield API in a react or nextjs project would be helpful.
> 
> We have a project where payments are akin to a gambling app where we take 10% of transactions and 10% when a user withdraws from our platform.
> 
> But reading the documentation I do not have a clue how this is possible using greenfield - or how anything is possible really.

**Comment by deadcoder0904** [comment]
I have made a minimal example in React.js/Next.js that works.

Just copy-paste it in Node.js section of docs and/or create a new Next.js docs & link to it directly as the README contains instructions on how to install, use & run it -> https://github.com/deadcoder0904/btcpayserver-nextjs

**Comment by pavlenex** [comment]
https://github.com/btcpayserver/btcpayserver-doc/pull/1387
