### ISSUE TITLE
Improve Lightning Network FAQ

### ISSUE THREAD

**Issue by OliverThompsonOT** [btcpayserver/btcpayserver-doc#1306]
I could not find the information I was looking for on the "Lightning Network FAQ" page (`/FAQ/LightningNetwork/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]
https://docs.btcpayserver.org/Deployment/LunaNode/
https://docs.btcpayserver.org/Deployment/voltagecloud/

hello, I see these two tutors, if I use btcpay in Lunanode, it includes a Bitcoin full node and Lightning Network nodes?

if I use btcpay in voltage cloud? it did not include Lightning Network nodes? so I need to deploy a lighting node in voltage cloud?

**Comment by webwworthy** [comment]
If deployed on luna node, aws, or anything that is your own manual deployment BTCPay Server will always come with the option to deploy a lightning internally by selecting Lightning > settings > internal node. This uses LND inside of BTCPay Server and you can manage you channels through RTL or Thunderhub, both options are available to choose once your internal node is running that you can get too from inside your BTCPay Server Dashboard.

Specifically in Voltage and also Umbrel's case they leverage their own services to connect your lightning node for you. In both cases you must _**deploy a lightning node first then deploy your BTCPay Server**_. That way the lightning node you have running will be automatically connected to your BTCPay Server when you deploy it on the same Voltage account or Umbrel node.

**Comment by Jtpj2017** [comment]
I would use moon pay or cash app

**Comment by Jtpj2017** [comment]
> If deployed on luna node, aws, or anything that is your own manual deployment BTCPay Server will always come with the option to deploy a lightning internally by selecting Lightning > settings > internal node. This uses LND inside of BTCPay Server and you can manage you channels through RTL or Thunderhub, both options are available to choose once your internal node is running that you can get too from inside your BTCPay Server Dashboard.
> 
> Specifically in Voltage and also Umbrel's case they leverage their own services to connect your lightning node for you. In both cases you must _**deploy a lightning node first then deploy your BTCPay Server**_. That way the lightning node you have running will be automatically connected to your BTCPay Server when you deploy it on the same Voltage account or Umbrel node.
