### ISSUE TITLE
[Question] About plugin possibility

### ISSUE THREAD

**Issue by bitcoinheiro** [btcpayserver/btcpayserver-doc#1308]
Want to confirm before starting my practical research, would it be possible to add support for samourai's paynim to store owners? Since Sparrow adopted it as well, would probably be a way to incentivize "payjoin" from their users with merchants running the plugin. Thanks for your help.

Also, maybe someone is working on this already? Would love to contribute.

**Comment by pavlenex** [comment]
This should be posted in discussions, not documentation repository. https://github.com/btcpayserver/btcpayserver/discussions
