### ISSUE TITLE
Common UX Issues Guide for Merchants

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#131]
Create documentation to help merchants troubleshoot common user experience issues during the checkout/payment process and how to solve them. The information should also be available (possibly infographic) for merchants to print and keep on hand for quick employee reference in physical stores where POS is used. 

Explain customer payment issues such as:
* Underpaid
* Paid Late
* Invalid
* Refunds
* Unconfirmed

**MERCHANT FEEDBACK & INPUT IS REQUESTED** in order to make this document. Please comment any customer payment issues and questions commonly experienced during checkout process. 
(Related to: [#433](https://github.com/btcpayserver/btcpayserver/issues/433) & [#434](https://github.com/btcpayserver/btcpayserver/issues/434))

**Comment by bitcoinshirt** [comment]
Recently I touched upon this subject in [WooCommerce order statuses.](https://docs.btcpayserver.org/integrations/woocommerce#btcpay-order-statuses) but now we need to explain statuses inside BTCPay.

Here are all the outcomes that will be visible in the server (slightly different to Woo, but we also have to tackle them in an easy to understand way and with clear actions what to do for each)

- New
- Paid
- Complete
- Paid Late (paidLate)
- Paid Over (paidOver)
- Paid Partial (paidPartial)
- Expired
- Invalid

So called problems on the checkout happen with: 
- Paid Late (paidLate)
- Paid Over (paidOver)
- Paid Partial (paidPartial)
- Invalid

Refunds can only happen with paid over. Luckily Lightning Network solves all of these as there's no confirmation time, no wrong amount/address entry etc.

**Comment by pavlenex** [comment]
[Added an infographic](https://github.com/btcpayserver/btcpayserver-media/blob/master/infographics/BTCPayServerInvoices.png) for this issue. I don't know what else can we do beyond that. If you guys have any ideas, let me know, otherwise I'll close the issue.

**Comment by britttttk** [comment]
Awesome @pavlenex it looks really good! :)

**Comment by pavlenex** [comment]
Should we close this then?
I assume order statuses are already explained in docs. If no ideas on how to proceed further, will close.
