### ISSUE TITLE
More detailed Info for Customers side 

### ISSUE THREAD

**Issue by Paigep77** [btcpayserver/btcpayserver-doc#1316]
I have been looking all over for details on the customers side.    For someone who is completely ignorant, new to this BTCPay server, it's not clear anywhere as to if the customer can pay for a product out of ANY Bitcoin wallet, like their cash app bitcoins wallet?    Or do they have to have a BTCpay Wallet?  I can't find info for the customer side on if they are to choose lightening? Can someone just explain the customer experience side step by steps with focus on what all wallets are compatible and when or if the lightening should ever be chosen?  Just a single line would help.  Please I need this info urgently

**Comment by Kukks** [comment]
> I have been looking all over for details on the customers side. For someone who is completely ignorant, new to this BTCPay server, it's not clear anywhere as to if the customer can pay for a product out of ANY Bitcoin wallet, like their cash app bitcoins wallet? Or do they have to have a BTCpay Wallet? I can't find info for the customer side on if they are to choose lightening? Can someone just explain the customer experience side step by steps with focus on what all wallets are compatible and when or if the lightening should ever be chosen? Just a single line would help. Please I need this info urgently

Just try out the demo linked on the main site https://btcpayserver.org. BTCPay is just Bitcoin and lightning payments. Any wallet that supports bitcoin and lightning properly will work. It should be pretty obvious

**Comment by Kukks** [comment]
> I have been looking all over for details on the customers side. For someone who is completely ignorant, new to this BTCPay server, it's not clear anywhere as to if the customer can pay for a product out of ANY Bitcoin wallet, like their cash app bitcoins wallet? Or do they have to have a BTCpay Wallet? I can't find info for the customer side on if they are to choose lightening? Can someone just explain the customer experience side step by steps with focus on what all wallets are compatible and when or if the lightening should ever be chosen? Just a single line would help. Please I need this info urgently

Just try out the demo. BTCPay is just Bitcoin and lightning payments. Any wallet that supports bitcoin and lightning properly will work. It should be pretty obvious

**Comment by Paigep77** [comment]
Ok thank you. But it's not obvious to all people. That's what I am saying.  Thank you for the info
