### ISSUE TITLE
Deadlink to bitcoinshirt.co in General FAQ

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-doc#1334]
[The General FAQ](https://docs.btcpayserver.org/FAQ/General/#do-i-need-to-have-an-online-store-to-use-btcpay-server) includes a dead link to bitcoinshirt.co

> If you do not have a store, but want to create one, read [How to Create an Online Store & Accept Bitcoin – Step By Step Guide](https://bitcoinshirt.co/how-to-create-store-accept-bitcoin/)[ (opens new window)](https://bitcoinshirt.co/how-to-create-store-accept-bitcoin/) which teaches you how to build a store from scratch and install BTCPay.

Is the doc still available elsewhere? @pavlenex

**Comment by pavlenex** [comment]
Probably not, I sold the website ages ago it seems it's dead, potentially on some archive site, but that tutorial is outdated probably anyway and can be removed
