### ISSUE TITLE
explore by topic (404 - page not found)

### ISSUE THREAD

**Issue by DuckG** [btcpayserver/btcpayserver-doc#1342]
Hello,

question:
 the links below this url doesn't work
https://github.com/btcpayserver/btcpayserver-doc/tree/master/docs#explore-by-topic

i.e. https://github.com/btcpayserver/btcpayserver-doc/blob/master/Apps/#point-of-sale-app

[What is BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Guide)
[Why BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/UseCase)
[How to deploy BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/TryItOut)
[Wallet Setup](https://github.com/btcpayserver/btcpayserver-doc/blob/master/WalletSetup)
[Lightning Network](https://github.com/btcpayserver/btcpayserver-doc/blob/master/LightningNetwork)
[How to setup POS](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Apps/#point-of-sale-app)
[Greenfield API](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Development/GreenFieldExample)
Frequently Asked Questions
and Common Issues
[How to contribute to BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Contribute)

Is there something broken? 
Or am I doing something wrong?

I was also looking for the explanation of the function of the "macaroon". (in rookie explanation)
 It is only the key(s), thats all?
 
 regards,

**Comment by dennisreimann** [comment]
Thanks for the pointer I fixed the links on GitHub. 

> I was also looking for the explanation of the function of the "macaroon". 

See this: https://docs.lightning.engineering/lightning-network-tools/lnd/macaroons
