### ISSUE TITLE
Document third-party hosting more in-depth

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver-doc#135]
I think we should document differences between self-hosting and third-party hosting more in depth and include possible pros and cons together with attach vectors.
[Related](https://github.com/btcpayserver/btcpayserver/issues/396)

While we can't protect users who use third-party hosts from potentially malicious hosts, we can educate them on potential attack vectors and pros/cons of using third-party hosts in general.  

Of course, this is by no means attack on third-party hosts, I think they are one of the most important part of the ecosystem in adoption, we just need to explain the trade-offs better.

I'm not even sure where this can be put. @britttttk any ideas?

**Comment by britttttk** [comment]
Concept ACK.

> Of course, this is by no means attack on third-party hosts, I think they are one of the most important part of the ecosystem in adoption, we just need to explain the trade-offs better.

Agreed, at this point it's possibly the best solution for least-tech people. 

I prefer less emphasis on how they operate (since this can vary), and more emphasis on self-host vs 3rd-party-host and what it means to use them, trade-offs, etc.

**Comment by bitcoinshirt** [comment]
> ThirdPartyHosting.md

I have no idea how I forgot about doc. Thanks.

**Comment by Eskyee** [comment]
I think now this is a important subject @bitcoinshirt , 
third-party hosts from potentially malicious hosts!!  

> we can educate them on potential attack vectors and pros/cons of using third-party hosts in general.
I agree.

Anything I can do, just let me know....

**Comment by bitcoinshirt** [comment]
Done.

**Comment by Eskyee** [comment]
excellent update, concise.
