### ISSUE TITLE
Improve Greenfield API examples with PHP

### ISSUE THREAD

**Issue by eliehanoo** [btcpayserver/btcpayserver-doc#1368]
I could not find the information I was looking for on the "Greenfield API examples with PHP" page (`/Development/GreenfieldExample-PHP/`).
how to pull money .  using the api 
[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by pavlenex** [comment]
We've done a lot of improvements recently here https://docs.btcpayserver.org/Development/GreenfieldExample-PHP/ let us know if it's better or not.
