### ISSUE TITLE
API examples streamlining

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver-doc#1371]
Add more consistent examples through curl, php, js

ecommerce use case (accept payments):
- create invoice
- register webhook?
- process webhook
- issue refund

more sophisticated, management examples
- create store
- create user
- create api key

**Comment by pavlenex** [comment]
@ndeet is there something more we need to do on this one?

**Comment by ndeet** [comment]
This is still on my todo, the other linked issue was about API docs, this is more about making existing examples the same across multiple languages like here https://docs.btcpayserver.org/Development/GreenFieldExample/
