### ISSUE TITLE
Improve General FAQ

### ISSUE THREAD

**Issue by chipperw1** [btcpayserver/btcpayserver-doc#1373]
I could not find the information I was looking for on the "General FAQ" page (`/FAQ/General/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]
I need to know how to pay someone on the btcpayserver but i cant find the info I need to do that?

**Comment by pavlenex** [comment]
Just use any bitcoin wallet and scan a QR code.
