### ISSUE TITLE
Improve Frequently Asked Questions and Common Issues

### ISSUE THREAD

**Issue by solutionprovidertoproblems** [btcpayserver/btcpayserver-doc#1376]
I could not find the information I was looking for on the "Frequently Asked Questions and Common Issues" page (`/FAQ/`).

I have not seen any useful answer to my question or guide on how to retrieve or recover Bitcoin sent to the demo version of BTC pay server 

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by pavlenex** [comment]
@solutionprovidertoproblems You mean http://mainnet.demo.btcpayserver.org?

Just like with any wallet, if you backed it up you can retrieve it in any external wallet or just send it out by inputing they key that you backed up to sign. https://docs.btcpayserver.org/CreateWallet/#watch-only-wallet
