### ISSUE TITLE
Improve Using the BTCPay API for Custom Integration

### ISSUE THREAD

**Issue by nikitakent** [btcpayserver/btcpayserver-doc#1391]
I could not find the information I was looking for on the "Using the BTCPay API for Custom Integration" page (`/CustomIntegration/`).

**Two small things with regards to the # Modal Checkout section docs**
1. It is unclear what the base BTC_PAY_URL is. Based on the ['Node JS' Greenfield API documentation](https://docs.btcpayserver.org/Development/GreenFieldExample-NodeJS/), a base URL could be either the BTC Pay Server URL, or the BTCPay Server URL + /api/v1/stores/${storeId}/invoices. I am assuming it is the former, but clarification would be helpful.
2. This page is also unclear whether the Modal Checkout is intended to be used with the Greenfield API. Again, I assume that it is, but just stabbing at the dark here and hoping I'm not barking up the wrong tree.

**Comment by pavlenex** [comment]
https://github.com/btcpayserver/btcpayserver-doc/pull/1398
