### ISSUE TITLE
Improve Greenfield API example with Node.js (JavaScript)

### ISSUE THREAD

**Issue by spacekestrel** [btcpayserver/btcpayserver-doc#1404]
I could not find the information I was looking for on the "Greenfield API example with Node.js (JavaScript)" page (`/Development/GreenFieldExample-NodeJS/`).

info about payouts

**Comment by ndeet** [comment]
Hey, what are you looking for. The examples cover some most used cases. Also you would not create a payout but a pull payment for refunds and that example is covered. If you want to create payouts nevertheless you can look at the api docs [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/PullPayments_CreatePayout) or if you want to create a transaction you can look [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_CreateOnChainTransaction).

**Comment by spacekestrel** [comment]
> Hey, what are you looking for. The examples cover some most used cases. Also you would not create a payout but a pull payment for refunds and that example is covered. If you want to create payouts nevertheless you can look at the api docs [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/PullPayments_CreatePayout) or if you want to create a transaction you can look [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_CreateOnChainTransaction).

well, basically in my app users should be able to request payout, based on amount of money they have in app's wallet. And withdrawal should be automated. is it pull payment or payout?

**Comment by ndeet** [comment]
You create a pull payment and the api will return you a link, you can give this link to your users where they can enter their on-chain or LN invoice to redeem the funds. The payout processor (if configured)  can then automatically do the payout.

**Comment by pavlenex** [comment]
Should be resolved by  #1406
