### ISSUE TITLE
First link of lunarNode Setup links to random tshirt buying website

### ISSUE THREAD

**Issue by MichaelBat** [btcpayserver/btcpayserver-doc#1407]
https://docs.btcpayserver.org/Deployment/LunaNode/

This link on that website leads to a random tshirt website.

![image](https://github.com/btcpayserver/btcpayserver-doc/assets/52211042/a8c8e1d5-4814-413b-be77-b7ba62412344)

**Comment by dennisreimann** [comment]
Thanks for the pointer!
