### ISSUE TITLE
Improve BTCPay Server payment gateway for Odoo 17

### ISSUE THREAD

**Issue by yojimble** [btcpayserver/btcpayserver-doc#1442]
I could not find the information I was looking for on the "BTCPay Server payment gateway for Odoo 17" page (`/Odoo/`).

Which version of odoo can I use this? Do I need to host myself?

**Comment by yojimble** [comment]
Sorry my question was not very clear, I meant can BTCPay server be used with what they call odoo online, where odoo host the shop for you.

**Comment by pavlenex** [comment]
I believe it should, have you tried it? @ndeet do you know?

**Comment by ndeet** [comment]
Seems Odoo Online does not work with custom modules or even the app store. See green box here https://www.odoo.com/documentation/18.0/administration/odoo_online.html
