### ISSUE TITLE
Link to edit Wix page is leading to wrong page

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver-doc#1443]
It is trying to navigate to https://github.com/btcpayserver/wix.git/edit/master/docs//Wix.md, see video:

https://github.com/user-attachments/assets/a0845e4e-9859-4be8-9ec7-2b420ed1130d

This issue seems to be with all the docs that have setup as external dependency, like in this PR https://github.com/btcpayserver/btcpayserver-doc/pull/1435

cc @pavlenex @TChukwuleta

**Comment by pavlenex** [comment]
Good catch. I believe this is true for any externally added page to the BTCPay Doc repository, not just Wix.

Don't forget that this markdown is pulled from the original btcpayserver/wix/readme.md and rendered in the repo. Possibly we'd have to have a better way for that bottom link.

@dennisreimann may have ideas as well.

**Comment by dennisreimann** [comment]
Yep, I'll fix. I know it was working at one point before, so this must be doable. Maybe something minor changed.
