### ISSUE TITLE
Improve Dynamic DNS Service

### ISSUE THREAD

**Issue by tropi-github** [btcpayserver/btcpayserver-doc#1469]
I could not find the information I was looking for on the "Dynamic DNS Service" page (`/Deployment/DynamicDNS/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

It would be great if you could write a guide for Umbrel Home users, so that it is possible to access the BTCPay server from the Clearnet. The instructions will not help with my configuration.

Thank you

Despite the installation of a PROXY HOST in NGINX Proxy Manager v2.12.1 and SSL certificate created by Let's Encrypt. I get the login page with the note "You cannot login over an insecure connection when I call the DYNDNS domain. Please use HTTPS or Tor." 
Unfortunately, the configuration instructions do not help. 

My configuration: 
I use umbrel home with bumbrel OS 1.3. The BTCPay server v2.0.3 was installed from the Umbrel Shop. All the displayed configuration paths of your help pages do not exist. No matter whether I log in via ssh on the Umbrel Home and look for the paths/entries or I open the terminal of the BTCPay Server app in Umbrel itself. Entering the command ". btcpay-setup.sh -i" always leads to the following error message "bash: btcpay-setup.sh: No such file or directory"

**Comment by pavlenex** [comment]
Duplicate #1044
