### ISSUE TITLE
Migration and Backup Documentation

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver-doc#156]
Now that we have documentation in place for setup and installation and covering pretty much every use case possible. I think it's time to focus on the "What if" and "Oh no, My server was erased" scenarios. 

I think we will need to document the following:

Backup solutions for NBXplorer (Is it even needed?)
Backup solutions for BTCPay (What needs to be backed up?)
Backup solutions for Lightning (If you have a node and it crashes, how do we move it?)
Restoration processes for all of the above

I really think it's important to offer easy backup solutions along with an easy way to restore old data. If your only running BTCpay, a loss of all your store data could be catastrophic.  

Pinging @bitcoinshirt @britttttk @NicolasDorier @rockstardev @Kukks for thoughts and ideas of how to accomplish

**Comment by LinoxBE** [comment]
Because @rockstardev like it, here is the command I use to dump the database config:

docker exec btcpaytestnet_postgres_1 pg_dumpall -c -U postgres | bzip2 > /home/btcpay-test/backups/dump_`date +%Y-%m-%d"_"%H_%M_%S`.sql.bz2

I guess that you guys know better then me where the configuration files are :-D

**Comment by zaowens** [comment]
Should there be some documentation on backups for running BTCPay on a VPS? Simple as enabling  snapshots, but at least its a suggestion for quick backups.

**Comment by NicolasDorier** [comment]
Important stuff are `/var/lib/docker/volumes/generated_*` can remove bitcoind from this as it takes lot's of space.

I think backing up ligthnign is less dangerous now, thanks to data loss protection feature.

**Comment by NicolasDorier** [comment]
also `/etc/profile.d/btcpay.sh` or something like this.

**Comment by Eskyee** [comment]
Migration and Backup Documentation ??? any progress on these ideas for adding in Documentation for this year! 
BTCPay Migration and Backup Methods.

**Comment by britttttk** [comment]
@Eskyee ok it seems a few ideas are mentioned above. I will try to test them, and see if we can get some basic techniques documented. I guess lightning has backup capability now anyways..

**Comment by oaon** [comment]
I recently migrated my docker install to new server hardware it was pretty straightforward.

1. I created the new docker BTCpay instance on the new hardware and let it sync.
2. Updated old server containers to the latest versions.
3. backed up the old server 
```
btcpay-down.sh
tar --exclude='/var/lib/docker/volumes/backup_datadir/*' --exclude='/var/lib/docker/volumes/generated_bitcoin_datadir/*' --exclude='/var/lib/docker/volumes/generated_litecoin_datadir/*' -cvzf backup.tar.gz  /var/lib/docker/volumes
btcpay-up.sh
```
4. Copy the backup.tar.gz to the new server
5. Recovered the backup on the new server 
```
cd /
btcpay-down.sh
systemctl stop docker 
tar -xvzf /path/to/backup.tar.gz
systemctl start docker
btcpay-up.sh
```
6. Update the apps to use the new server.

The whole thing took less than 10 minutes from starting the backup to having the new server working.

**Comment by dennisreimann** [comment]
Great thread! Used the information above and wrote this little backup script:

```sh
#!/bin/bash
set -e

DOCKER_DIR=/var/lib/docker/volumes
BTCPAY_DIR=$HOME/btcpayserver/btcpayserver-docker
BACKUP_DIR=$HOME/backups

datestamp=$(date "+%Y%m%d-%H%M%S")
dump_file=postgres-dump.sql

cd $BTCPAY_DIR

docker exec generated_postgres_1 pg_dumpall -c -U postgres > $dump_file

btcpay-down.sh

tar --exclude="$DOCKER_DIR/generated_bitcoin_datadir/*" --exclude="$DOCKER_DIR/**/logs/*" -cvzf btcpay-$datestamp.tar.gz $DOCKER_DIR $dump_file

mv btcpay-$datestamp.tar.gz $BACKUP_DIR
rm $dump_file

btcpay-up.sh
```

**Comment by Eskyee** [comment]
Excellent work from Oeon & Dennis I would love to see a backup & restore database button in the Maintenance￼ section next..  that would be a great look for BTCPAY 💚 if possible. 🙌

**Comment by dennisreimann** [comment]
@Eskyee I think this is a good idea and we should also tie the backup process to the upgrade process.

**Comment by Eskyee** [comment]
Perfect 🤩 this makes BTCPAY much more flexible!! 🥂🙌🙌

**Comment by dennisreimann** [comment]
TIL there is a backup script already :D https://github.com/btcpayserver/btcpayserver-docker/blob/master/backup.sh

**Comment by dennisreimann** [comment]
BOOM 🥳 https://github.com/btcpayserver/btcpayserver-docker/pull/429

**Comment by dennisreimann** [comment]
Heads-up: The backup script improvements got merged – it'd be good to receive some feedback on it once you get the chance to test it. @astupidmoose @oaon

**Comment by Al-Bsharat** [comment]
> Heads-up: The backup script improvements got merged – it'd be good to receive some feedback on it once you get the chance to test it. For details see the [backup instructions](https://github.com/btcpayserver/btcpayserver-docker#how-can-i-back-up-my-btcpay-server). @astupidmoose @oaon

Thank you very much.
But how I can restore the backup?
