### ISSUE TITLE
Document Crowdfund in Apps.md

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#158]
We should add Crowdfund app to Apps.md

**Comment by britttttk** [comment]
Also add Crowdfund info to: 
* [UseCase.md - Charity Section](https://github.com/btcpayserver/btcpayserver-doc/blob/master/UseCase.md#charities-and-content-creators-donations)
* [Walkthrough.md - App Section](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Walkthrough.md#apps)

**Comment by britttttk** [comment]
Also consider adding reference to Crowdfund App under Features category in these docs:

* BTCPayVsOthers.md
* Readme.md

**Comment by zaowens** [comment]
I ignored updating Walkthrough.md on my merged PR because I wanted to discuss structure again.

I wasn't sure if detailed crowdfunding documentation would require its own page, or if anyone had started any walk through documentation yet.

**Comment by britttttk** [comment]
No worries @zaowens if no one has been assigned to the task you can assume no one is working on it. Similarly, if you are working on something you can ask to have it assigned to you, so no one will do work you are already doing.

**Comment by pavlenex** [comment]
I think we're good. Walkthrough.md explains just the basics of the Interface, we don't go in-depth and cover the details of the apps there anyway. 

For starters, I suggest we build everything in apps.md if it gets huge and hard to navigate, we can easily break down into multiple pages. Even without breaking down in the sections, I can add links to app headlines into docs.

- Apps.md
     -- PoS (link to pos in apps.md)
     -- Payment Button (link to payment button in apps.md)
     -- Crowdfunding (link to crowdfunding in apps.md)

The document that needs to be modified to include links to the apps is summary.md as that page provide structure for GitBook.
