### ISSUE TITLE
Improving App Related Docs 

### ISSUE THREAD

**Issue by zaowens** [btcpayserver/btcpayserver-doc#159]
I'd like to suggest expanding "Apps" into its own section, which will allow room for organized and expanded documentation related to not only current apps, but any added in the future. 

My suggestion would be to remove apps from the "Features" section, and creating a parent category called "Apps", containing a dedicated page for each app with its own documentation and guides.

Example:

```
### Apps
* Point of Sale
* Crowdfunding
* Payment Buttons
* Lapps
```

In my current fork I'm working on I suppressed Lapps and Payment Buttons into a "View All" link which links back to the original App.md file that would simply contain brief summaries of all Apps with links to any expanded documentation that is available.

This would also start off a documentation section for Issue #158 (Document Crowdfund in Apps.md ).

Any thoughts on how this could / should be structured better?

**Comment by zaowens** [comment]
@britttttk Yes that's what I'm basing my current organizational strategy from (Gitbook docs layout)

I could easily subcategory the pages if everyone would prefer.

**Comment by pavlenex** [comment]
One more problem of having separate pages is that you'll need to fix all links leading to apps.md# because all of them will be broken.
I think that having Apps as a category inside features with separate page for each app is okay.

**Comment by zaowens** [comment]
My suggestion is to leave app.md so the links do not break. Make it summary of apps, with links to dedicated pages of said app containing extended documentation and guides for each.

**Comment by pavlenex** [comment]
That could work, just make sure not to change the titles of already added apps in apps.md when making a summary.

**Comment by britttttk** [comment]
@zaowens I agree with @pavlenex,
I prefer that Apps remains within Features (PoS, CF & PayB nested under Apps).

My reason is:
Some of the other existing documents describe the apps as BTCPay features. See these docs [for example](https://github.com/btcpayserver/btcpayserver-doc/issues/158#issuecomment-454222340), PoS in those docs is currently listed as a feature. As well as the (Apps = View All) redundant UI comment I mentioned above. 

To use subcategories for docs.btcpayserver.org do we need to create new doc for each item in app?

> **Features**
>* Internal Wallet
>* Apps                        <------------------------------ Add CF content (Issue #158)
>    * Point of Sale        <----------------- Add new PoS doc ?
>    * Crowdfunding     <--------------- Add new CF doc ?
>    * Payment Button  <------------- Add new Payment Button doc ?
>* Lightning Network
>* Accounting
>

**Comment by zaowens** [comment]
I am also now in agreement it should be sub-categorized under features. I believe PoS and CF should have dedicated pages since they are 'large' applications. I feel Payment Button could be handled with a simple anchor link to its position on Apps.md
