### ISSUE TITLE
Links to media articles

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#163]
It would be good if we can have a directory with all the links to media articles, podcasts and conference talks about BTCPay.

**Comment by zaowens** [comment]
Would fit great under support and community. 

What should the page be titled? "Publications", "Press", "External Publications" 

Something along those lines?

**Comment by pavlenex** [comment]
All three sound good to me. But if we're going to list podcasts and videos, maybe we need something more generic, not sure.

I use to curate the list of [all btcpay videos](https://www.youtube.com/playlist?list=PL7b9Wt9shK2r-WXS6ysG4tafVQRu80biZ) until 2 months ago, can use some cleanup.

So a page with sections for:
* Articles
* Interviews (Podcasts and Video?)

Not quite sure about the terminology and structure we can use, feel free to chime in with suggestions.

**Comment by NicolasDorier** [comment]
Great idea

**Comment by zaowens** [comment]
Would this page be replacing the "Community articles" section that's currently located at the bottom of README.md ?

Current content being removed and migrated.

**Comment by pavlenex** [comment]
> Would this page be replacing the "Community articles"
@zaowens We'll see let's first have a list. Community articles are written mostly by contributors and are guides, not mass-media type of articles in most cases they are quite technical.
@britttttk I thought of that, it makes sense, not sure if that repo gets enough visibility.

How about we first discuss the sections, then, each of us is assigned for particular section, we merge sections into a single document and decide where to put that document based on the info we gather , we'll easily see where it fits.

**Comment by zaowens** [comment]
> Community articles are written mostly by contributors and are guides, not mass-media type of articles

What are your thoughts on a section for "Technical Guides" and articles? Or is this strictly PR related media? imo anything listed outside of the .org and github is positive exposure for BTCPay. 

Just brainstorming is all.

**Comment by pavlenex** [comment]
Sure, it can be technical guides as well, but let's first tackle these and expand.

**Comment by pavlenex** [comment]
Okay so I've added:
- [Articles](https://github.com/btcpayserver/btcpayserver-media/blob/master/Publications/Articles.md)
- [Videos](https://github.com/btcpayserver/btcpayserver-media/blob/master/Publications/Video.md)

All is left is podcasts which @zaowens is working on.

**Comment by pavlenex** [comment]
@zaowens Any updates on the podcast list? If no, I'd like to take-over so that we can close this issue.

**Comment by zaowens** [comment]
@pavlenex I only found a few podcasts. I'll upload what little I found so you may add to it.
