### ISSUE TITLE
video connecting raspibolt to btcpayserver using dynamic ip

### ISSUE THREAD

**Issue by talentpierre** [btcpayserver/btcpayserver-doc#175]
it would be really nice to see a video, in which you explain how to deploy a connection via raspibolt and btcpayserver using a dynamic ip. i think, this could be some of the great issues, not having a static ip and want to connect to an external btcpay server

**Comment by pavlenex** [comment]
I think with Tor support coming this will not be needed. In my opinion, this is a too specific request for a video, but if you want, feel free to document it or record it.
