### ISSUE TITLE
problems with xpub / ypub

### ISSUE THREAD

**Issue by talentpierre** [btcpayserver/btcpayserver-doc#177]
i tried to use my ypub from samourai to set up a wallet. last time it worked, now it doesn't.
after generating the ypub i pasted it into the wallet section. because i use this my wallet quite often i have more then 10 addresses used, so i had to enter my actual address. after entering i got this message:
> Impossible to find a match with this address >

afterwards i tried to insert an address from the list, presented by btcpayserver but i got the same message.
maybe you can help

**Comment by pavlenex** [comment]
[Follow this guide.
](https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#missing-payments-in-my-software-or-hardware-wallet
)It's not recommended to use a [wallet with gap-limit fixed](https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#missing-payments-in-my-software-or-hardware-wallet), so Electrum is highly recommended if you want to use external wallet.

**Comment by talentpierre** [comment]
sorry. i switched to the ordinary repository, added more details and asked this question again.
i think if btcpayserver doesn't find my receiving address, i could be a problem in btcpayserver, couldn't it?
unfortunately i can't export my xpub/ypub from electrum mobile wallet.
thanks for helping me
