### ISSUE TITLE
Question: How to troubleshoot 503 Service Temporarily Unavailable after running btcpay-update.sh?

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-doc#180]
I have run btcpay-update.sh but this failed the first time.
Then ran btcpay-stop.sh as I figured it was still running.
2nd time worked fine.
Now it looks like it is started and running, but I keep running into 503 Service Temporarily Unavailable Nginx error.

I am myself quite familiar with Nginx, but not so much with Docker or BTCPay Server.
What tools / logs are provided to troubleshoot this?

Any advice would be very much appreciated!!

**Comment by pavlenex** [comment]
This is a wrong repository to ask a question.

btcpay-stop is not the right way to do it.
It should be `btcpay-down.sh` then `btcpay-up.sh` or `btcpay-restart.sh`

**Comment by woutersamaey** [comment]
sorry for the inconvenience. turned out there was something wrong with my load balancer. buh :(

**Comment by pavlenex** [comment]
hah, it happens, lately there have been some issues with 503, so if your server is weird just try `btcpay-restart.sh`
