### ISSUE TITLE
Document Payment Requests

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#187]
We have to figure out a place for payment requests. Ideally they'll go under apps, but since they're not apps, maybe a new page PaymentRequests.md under Features will be more suitable.

Nothing fancy, we already have the article, just need to re-write it more formally and embed a video instruction.

**Comment by Eskyee** [comment]
yes I agree with a new page PaymentRequests.md under Features for sure Pav

**Comment by britttttk** [comment]
Please assign to me.

**Comment by pavlenex** [comment]
Done #195
