### ISSUE TITLE
Server side pairing documentation not clear

### ISSUE THREAD

**Issue by songproducer** [btcpayserver/btcpayserver-doc#196]
The current documentation is:

> The second way, is to generate your private key via some bitcoin library then:
> 
> Go to the store's settings
> Click on Access tokens
> Click on Create new Token
> Select merchant's facade and enter your public key,
> Click request pairing
> Click on Approve

However in the Manage Store > Access Tokens page the hint says:

> PublicKey Keep empty for server-initiated pairing

These instructions seem to be at odds with each other.

I left the PublicKey field empty and it generated a pairing code, but I don't know what to do with it.

**Comment by NicolasDorier** [comment]
what language are you using?

**Comment by songproducer** [comment]
I’m beginning in Nodejs, with the goal of integrating automatics sell orders when a sale happens. Not sure if I should be trying to do this with client or server side pairing.

**Comment by NicolasDorier** [comment]
Have you tried to open an issue on the Node js btcpay library repo? The best UX is client side pairing.
