### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by JorgeOrtegaHdz** [btcpayserver/btcpayserver-doc#20]
Where can i write the configuration of database server?

**Comment by NicolasDorier** [comment]
using `--postgres` command line https://www.connectionstrings.com/postgresql/

**Comment by JorgeOrtegaHdz** [comment]
Thank you, now I have problems with connection between btcpayserver and NBXplorer because the btcpayserver need a user and password for connect, but I didn´t do any configuration of user and password in NBXplorer. Where can I configure the user and password in the two projects?

**Comment by NicolasDorier** [comment]
just run nbxplorer without specific command line args, and btcpayserver as well. It will be able to connect.

**Comment by JorgeOrtegaHdz** [comment]
I did that, i ran the two projects only like the video of setup in BTCpayServer channel. But BTCPayServer show me the error: NBXplorer error 'Response status code does not indicate success: 401 (Unauthorized).'

**Comment by NicolasDorier** [comment]
You are right. This is a bug, fixing it.

**Comment by NicolasDorier** [comment]
Ok so it seems a bug to bitcoin that I need to report.

Repro on Xenial
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Steps
```
sudo apt-get install bitcoind
nohup bitcoind -regtest &
sleep 5
bitcoin-cli -regtest getblockchaininfo
```
Result: 
```
error: incorrect rpcuser or rpcpassword (authorization failed)
```

Something is wrong with the cookie authentication?

**Comment by NicolasDorier** [comment]
I tried 
```
bitcoind -rpcuser=blah -rpcpassword=blah
```
Then run
```
bitcoin-cli --btcrpcuser blah --btcrpcpassword blah -regtest blah
```

Same issue. This is very strange.

**Comment by NicolasDorier** [comment]
I posted here https://github.com/bitcoin/bitcoin/issues/13977

**Comment by NicolasDorier** [comment]
@JorgeOrtegaHdz it might be an unrelated bug... (unsure)

What OS are you using?

**Comment by bitcoinshirt** [comment]
Hey @JorgeOrtegaHdz it appears you either solved the issue or found a workaround. I will close this issue in the next 48 hours since it's not related to btcpay-docs.

If your issue is not resolved, please reply or re-open it in https://github.com/btcpayserver/btcpayserver repo.
