### ISSUE TITLE
How to (manually) install Lightning-only?

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver-doc#205]
I have a server with bitcoind, c-lightning, Wordpress and nginx. I would like to do a bare minimum install of BTCPay Server, such that I can:
* do easy updates (pulling the `latest` branch is fine)
* only support Lightning, not onchain

It seems like I shouldn't need NBXplorer, but it's complaining quite heavily.

`./run.sh  --port 8081 --btclightning=/run/lightningd/lightning-rpc` throws a bunch of `BTC: NBXplorer error Connection refused` errors. I'm able to login to the admin panel and configure various things, depsite the "The node is offline" popup.

I disabled BTC under "Derivation Scheme", but that doesn't seem to help.

Did I miss a configuration option or is this not supported yet?

**Comment by pavlenex** [comment]
Hey Sjors,

The easiest way to `disable` on-chain is not to show it at the checkout, to do that you can go to Server Settings > Checkout Experience.

![checkout](https://user-images.githubusercontent.com/36959754/55278809-7987c080-5311-11e9-961b-c9fb529f603f.PNG)

I'm not quite certain that's what you need though.

**Comment by Sjors** [comment]
I installed NBXplorer for the time being and disabled on chain payments as suggested by @pavlenex. That works for now, but I'd rather not run NBXplorer if I don't need it.

**Comment by pavlenex** [comment]
ping @NicolasDorier: ^
Also, you may want to move this issue to the main repo, seems more appropriate for there.

**Comment by NicolasDorier** [comment]
@Sjors you need NBXplorer because some features, like lightning are automatically disabled if NBXplorer detect that your node is not running or not fully synched.

**Comment by NicolasDorier** [comment]
For the btclightning, use this format `https://github.com/btcpayserver/BTCPayServer.Lightning/#examples` .

Actually this parameter is only useful because it add a clickable link "click here" in the "Add lightning node" which just copy what is set in the textbox.

**Comment by Sjors** [comment]
Maybe I should open a ticket on btcpayserver repo "make NBXplorer dependency optional"? Lightning doesn't really need NBXplorer, right?

**Comment by NicolasDorier** [comment]
Yeah you theorically could.

**Comment by pavlenex** [comment]
@Sjors We've now [added](https://github.com/btcpayserver/btcpayserver-doc/pull/210) how to disable off-chain in docs, should you need help about disabling the  NBXplorer, please open an issue in the main repo.

I'll close this one for now, but feel free to re-open if you need additional assistance.
