### ISSUE TITLE
Add Fast Sync to Sync FAQ

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#209]
https://docs.btcpayserver.org/faq-and-common-issues/faq-synchronization

**Comment by pavlenex** [comment]
Add:

- [ ] How to FastSync and add instructions + video from Bolthaton presentation timestamped exactly there

@britttttk you can pick this one if you want since you're the fast sync expert after watching @rockstardev performance.

Instructions provided [here](https://docs.btcpayserver.org/deployment/raspberrypideployment) from step 15.

**Comment by britttttk** [comment]
I'm hesitant to add instructions to the FAQ because people might disregard the trust considerations. I think the FastSync README.md could be improved by adding instructions.

**Comment by pavlenex** [comment]
Re-opening because in GitBook I noticed lots of search queries for "Fast Sync" that returned nothing. Probably people trying to find a way to use it.
