### ISSUE TITLE
Cannot change port or get BTCPay Server up and running

### ISSUE THREAD

**Issue by d4amenace** [btcpayserver/btcpayserver-doc#21]
I am able to get up to the point where I clone BTCPay server in and do dotnet run help, but I get this error....could it be that my BTCD is running on port 8332?  How do I change it if so?  I tried --port 8332....nothing works.
![untitled3](https://user-images.githubusercontent.com/29969146/44282945-53019300-a222-11e8-8dae-d1d7074fb402.png)

**Comment by NicolasDorier** [comment]
what you are trying to do is develop on BTCPay?

**Comment by NicolasDorier** [comment]
If you don't want to develop, use `run.ps1` do not use `dotnet run`

**Comment by bitcoinshirt** [comment]
Hey @d4amenace it appears you either solved the issue or found a workaround. I will close this issue in the next 48 hours since it's not related to btcpay-docs. 

If your issue is not resolved, please reply or re-open it in https://github.com/btcpayserver/btcpayserver repo.
