### ISSUE TITLE
xpub generation video and doc update

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#213]
People who don't have Nano S or Trezor are having a hard time finding a way to have p2sh compatible xpubkey.

Unfortunately, it's not possible to generate a p2sh seed in Electrum, you can only import it from the external wallet, so we need to create a guide for those people, as I'm seeing an increasing amount of confused newbies.

Any wallet suggestions or workarounds @NicolasDorier?

**Comment by pavlenex** [comment]
Two wallets me and @rockstardev found would be Samourai for Android and Coinomi for iOS. However, neither supports custom gap limit which will be a deal breaker and will cause "where's my money" questions...

So how do we make this easier for people who don't have or can't afford a hardware wallet and for those who want to track payments externally?

I'm really hesitant to open a feature request for watch-only BTCPay Wallet app...

This issue is more for the main repo but maybe we can brainstorm a bit here.

**Comment by JeffVandrewJr** [comment]
This can be run fully client-side without an internet connection using a local copy: https://github.com/iancoleman/bip39

The BIP49 in the generator tab generates P2SH wrapped Segwit addresses.

**Comment by pavlenex** [comment]
@JeffVandrewJr I'm aware of the tool, but it's not a newbie-friendly solution, unfortunately.

**Comment by NicolasDorier** [comment]
When Wasabi Wallet and BTCPay are both done with PSBT, I think we will just advise Wasabi Wallet as the recommended wallet @nopara73

**Comment by nopara73** [comment]
# KeyPaths

Note that Wasabi is bech32 only, so that may be a blocker?

# C#

Wasabi is a good choice, because if there's an issue with it, anyone here can easily touch the code, because it's written in C#, too, where your expertise lies.

# Gap Limit

I added a `MinGapLimit`: https://github.com/zkSNACKs/WalletWasabi/commit/409a01cd48fd0753b1c84f1f1ddcef2a93973b9d

The wallet file can be modified from `File/Open/Wallet Folder`.

# Notes

- **This is not a gap limit.** Wasabi may very well generates and monitors more addresses than this if needed, **thus the name minimum gap limit.**  
- **It cannot be less than 21.** If you set it smaller than 21, then Wasabi will autocorrect it to 21.
- **Why 21?** Because there are 21 million bitcoins.
- **Issues can happen at wallet recovery if it's forgotten to be set to the same value again.** So at wallet recovery, don't forget to set the min gap limit again.
- **This can be only set after a wallet has been successfully generated, recovered or imported.**

**Comment by NicolasDorier** [comment]
> Note that Wasabi is bech32 only, so that may be a blocker?
A feature you mean.

@nopara73 a note about PSBT support on your side:

My server will only know the account level keys, not the keypath to those account:
This mean that in the PSBT you will see:

`accountPubKey.GetHDFingerprint(), m/0/4`

Of course, you know this accountPubKey and the path to it, so if you see this, you will need to use `PSBT.RebaseKeyPath(accountPubKey.GetHDFingerprint(), fpMaster, m/44'/0'/0')` before passing the PSBT to the HW.

**Comment by nopara73** [comment]
@NicolasDorier I understand what you say, but I don't understand the user workflow.

In Wasabi we use PSBT as the following:

Wasabi gets the extpubkey and the fingerprint from hardware wallet and uses it as a normal wallet from there on. Of course we are building and sending the transactions to the hardware wallets through PSBT, but I don't see how BTCPay could come into the picture in this workflow.

The other workflow is when the user builds unsigned transaction and we give a PSBT to the user. The user then manually copypastes or maybe saves the unsigned transaction to a file gives it to a hardware wallet, comes back with signed PSBT and copypastes it to Wasabi for broadcasting.  

How does BTCPay come into the picture? What would be the user workflow?

**Comment by NicolasDorier** [comment]
@nopara73 there will be case where BTCPay users will have a PSBT which is spending stuff that Wasabi Wallet don't know about. Two cases:

* Gap limit in wasabi being not enough
* Multisig, where each user took their xpub from their wasabi wallet

In such case, BTCPay will provide a PSBT, unsigned, with the keypath set relative to the account xpub.
Then if wasabi has a way to sign an arbitrary PSBT, it would need to change the keypath to not be relative to the account xpub but relative to the master key before sending to wallet.

**Comment by nopara73** [comment]
So, gap limit is not an issue anymore.

Regarding signing PSBT, there's no current workflow for that nor were we thinking about having one. We'll add new advanced tabs to the wallet: 

1. Transaction Builder
2. Transaction Broadcasted

I guess a Transaction Signer could be also added, but the first two is taking way too long for @molnard to implement. Nevertheless I'm fine with PRs after that's read: https://github.com/zkSNACKs/WalletWasabi/pull/1351

Now there's the whole question of multisig that I have absolutely no idea how to sign, but I suspect you know exactly, so I don't think we'd encounter issues there.

**Comment by NicolasDorier** [comment]
Gap limit is absolutely an issue.

1. Start wasabi
2. Copy xpub to btcpay
3. Create 22 invoices
4. Pay the 23th
5. No funds on wasabi

I know the gap limit is configurable, but what if the user forgot it.
