### ISSUE TITLE
Cannot open a Lightning channel with Spark - Unsuccessful HTTP Response

### ISSUE THREAD

**Issue by mattnook** [btcpayserver/btcpayserver-doc#216]
Hello, I am getting an "Unsuccesful HTTP Response" error when trying toopen channels from my Lightning node within Spark. Any ideas why this might happen? I also seem to be unable to open channels from my local Lightning node to my BTCPay Server Lightning node. 
![2019-04-20 19_29_05-Spark - Brave](https://user-images.githubusercontent.com/16688198/56463905-8e50f480-63a3-11e9-9099-ae9239d973e6.png)

**Comment by pavlenex** [comment]
@mattnook this is documentation repo, so in future, please post questions on our main repo or even better on [Mattermost](https://chat.btcpayserver.org/).

Here are some things to look at:
- In your BTCPay, Store > Lightning Network Experimental > Modify > `Test Connection`. If it does not say it's successful, try to restart your btcpay with `btcpay-down.sh`, then `btcpay-up.sh` if that does not work, try `btcpay-restart.sh` and give your node some time to catch up.

- If above does not help, you should look [into your c-lightning logs](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-2-lightning-network-c-lightning-docker).

It would be helpful if you can provide a little bit more info on your environment.

**Comment by mattnook** [comment]
it was an issue with Luna Node being down. Thanks
