### ISSUE TITLE
Tried to SSH into BTCPayServer LunaNode Deployment and Can't access Server in Browser

### ISSUE THREAD

**Issue by mattnook** [btcpayserver/btcpayserver-doc#217]
I tried to SSH into my BTCPay Server with putty which I deployed on Windows 10 with LunaNode. 

I did  sudo apt-get update and sudo apt-get upgrade and now when I try to open the server on my browser, I get "This site can’t be reached btcpay735442.lndyn.com refused to connect".
I SSH'd in again and did sudo reboot, but still the same is happening.

LunaNode tells me my VM is online. However I cannot see any of the server settings any more. Do I need to start a new node again or is there a way to restore this one?

I can still SSH in, but all I see is this message
![2019-04-21 21_33_51-](https://user-images.githubusercontent.com/16688198/56480087-3a670e00-647e-11e9-9b51-5b87cf0fac92.png)

**Comment by pavlenex** [comment]
@mattnook this is documentation repo, so in future, please post questions on our main repo or even better on [Mattermost](https://chat.btcpayserver.org/) where chances of getting a proper reply are much higher.

You can try `btcpay-down.sh` then `btcpay-up.sh` but definitely open a ticket with LunaNode and see what they have to say, make sure to provide logs of your vm which can be found in dasboard. Seems to me you wiped something, but they should be able to provide proper help.

**Comment by NicolasDorier** [comment]
You need to be root `sudo su -`  then you can troubleshot with `docker ps`/`docker logs` as documentedin this repo.

**Comment by mattnook** [comment]
thanks and sorry for posting this here. I had to go and stop nginx since it was running for some reason and was taking port 80. I did  `sudo nginx -s stop` then `btcpay-up.sh` and it seems to be running again 😄

**Comment by NicolasDorier** [comment]
@mattnook there should have no nginx installed outside of the docker image.
