### ISSUE TITLE
New FAQ Questions

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#221]
Possibly add some new FAQ questions @pavlenex do you you like any of these? I'm not sure where the hardware questions would go besides "general deployment FAQ".

1. **I am interested in setting up BTCPay so that I can use it both as a personal payment processor for people to pay me (from e.g. tipping, money owed to me, etc.) but also as a payment processor for an online shop. What is the recommended set up to do this?** 
    - You can use the same BTCPay instance for both, there is no need to run separate instances as BTCPay allows you to create an unlimited number of "stores" each with their own settings. This allows users to save on costs because it only requires one hosting plan to use all BTCPay features with only one deployment. 

2. **Would it be recommended to keep the personal BTCPay instance running at home on e.g. a Raspberry Pi in order to save on the hosting costs or are there any major advantages of putting the personal BTCPay instance on a VPS hosting provider?**

    - BTCPay on hardware considerations, Examples: Need reliable power supply/internet, technical skills required (Initial hardware/OS/docker setup, command line skills, setting up static IP & port forwarding, local/non-local ssh, etc.), longer sync time, no monthly server payments. 
    - BTCPay on VPS considerations, Examples: pay for reliability/bandwidth, easy web interface 1-click deployment, easy ssh, IP address unrelated to your physical address, monthly server fees. 

3. **Is it OK to power up my BTCPay on Rasp Pi only when it's expecting a payment?** 
    - No, you need it online at all times so that your Bitcoin node stays in sync with the blockchain to verify transactions. If you only power it up every now and then, it would take a long time to catch up on verifying recent blocks, and your payments would not show up until much later.

4. **Is there any way to use my existing full node, in order to save on e.g. sync time etc.? Are there any advantages and disadvantages of doing so?**
    - There is this [sync with existing node](https://docs.btcpayserver.org/faq-and-common-issues/faq-synchronization#im-running-a-full-node-and-have-a-synched-blockchain-can-btcpay-use-it-so-that-it-doesnt-have-to-do-a-full-sync) guide or this [reduce sync time with Fast Sync](https://docs.btcpayserver.org/faq-and-common-issues/faq-synchronization#can-i-skip-the-synchronization). Both methods require some technical skills. Using the Bitcoin full node that comes internal to your BTCPay deployment by default is much easier for the average user.

**Comment by pavlenex** [comment]
@britttttk I like questions 2 and 3, but initial questions are way to long, we need to re-formulate and shorten them before adding to FAQ.
