### ISSUE TITLE
Installing BTCPay with existing Bitcoind/Lnd

### ISSUE THREAD

**Issue by kampester** [btcpayserver/btcpayserver-doc#224]
Can you install BTCPayServer with a existing active and synced  btc/lnd node on a headless raspberryPi?  It appears all install documentation/guides presuppose starting a node build from zero. Wondering if I missed something.

Specifically, I have an existing RaspberryPi 3 with a headless, synced bitcoind  (bitcoin-core-0.17.1) and lnd (v0.5.2-beta).

Also, I have RTL and btc-rpc-explorer operating on the LAN via a laptop(s) working both on a mac and windows10 laptop. 

I attempted to install BTCPayServer, and ran into this error msg:

 `ERROR: for btcpayserver_lnd_bitcoin  Cannot start service lnd_bitcoin: driver failed programming external connectivity on endpoint btcpayserver_lnd_bitcoin (9aca51c02d33aa4a62bef4f41f95a8e8c79f50170a3ba16e52ecd3227e00aef6): Error starting userland proxy: listen tcp 0.0.0.0:9735: bind: address already in use`

Any work around guides or tips?

Thanks - Erik

**Comment by britttttk** [comment]
Hey @kampester 

It's possible to use your own btc/lnd nodes but it becomes a manual BTCPay deployment which is complicated and time consuming. Using your existing nodes is not currently documented. BTCPay includes a btc/lnd node with the docker install. 

Address is already in use for 9735 is the default port for LND, are you forwarding that port for your existing LND node?

**Comment by NicolasDorier** [comment]
@kampester as @britttttk says, it is theorically possible, but not recommended.
You can use the `./run.sh --help`  on nbxplorer and btcpay to see the command line options.

But you need to understand what the docker compose do by seeing [this video](https://vimeo.com/316630434).

One idea is that you generate your perfect yml by looking the video, this will give you all the configuration needed for each dependency. Then try to set the same thing via systemd. Good luck though. (be carful though, sometimes I listen on `0.0.0.0`, which is safe in docker, but not on bare metal)

**Comment by kampester** [comment]
@britttttk  thxs for quick reply,  Yes using Port forwarding on 9735 for existing lnd node and will heed to your advice here... I will focus on a fresh deployment :)     Cheers Erik
