### ISSUE TITLE
Document U2F and 2FA authentication

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#226]
We should put somewhere (FAQ?) how users can further secure their login accounts with 2FA and now U2F.

**Comment by britttttk** [comment]
Please add question mark tooltip linking to this on U2F tab of BTCPay.

**Comment by pavlenex** [comment]
Looking at docs, it seems @britttttk you already documented this in Getting Started and Walkthrough guides, do you want me to add it to FAQ-General?

- How to secure your BTCPay login? or sth like that?

**Comment by pavlenex** [comment]
Added in RegisterAccount.md now.
