### ISSUE TITLE
Update walkthrough guide with new header image

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#227]
[Walkthrough guide](https://docs.btcpayserver.org/btcpay-basics/walkthrough) should be updated with new header image (remove old one) and new options/settings/features should be documented.

**Comment by britttttk** [comment]
- [ ] Update header image
- [ ] Server Settings
- [ ] Stores
- [ ] Apps
- [ ] Wallets
- [ ] Invoices
- [ ] Payment Requests
- [ ] My Settings
