### ISSUE TITLE
Add Internal Storage Documentation

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#230]
Since version 1.0.3.95 we have internal storage where users can upload files. Sharing img for PoS and other apps no longer need to be external.
```
You can also set up the temporary expirable links for files, which we plan to merge into our apps, so that content creators can sell music, images, and videos through BTCPay, without having to use a CMS like WordPress.

The most important future use-case for external storage service will be Lightning Network static channel backups and the backup of the entire BTCPay Server.
```

**Comment by britttttk** [comment]
For documenting this feature, @pavlenex I was thinking about:
- Add to FAQ
    - But it might be a bit long for the FAQ, I would like to use screenshots/gifs since it's on several pages. I don't know if it should be it's own page or maybe a blog post on how to use it. Any thoughts? 

- Steps to set up and use:
1. Enable feature & choose FS system in Server Settings > Services
2. Upload files from computer in Server Settings > Files
    - UseCase1. Copy uploaded file URL for image use in Apps > Settings
    - UseCase2. Set up temporary expirable links for uploaded files for content creators who sell digital files through BTCPay. Check the download box to allow temp link to download the file on user's computer.

**Comment by pavlenex** [comment]
@britttttk yeah that sounds good. Not sure about the second use case, it should probably be integrated into the apps first, stand-alone temporary expirable links don't mean much to people unless they can use them in apps, etc.
