### ISSUE TITLE
LND: Connect to a full node + forcing a wallet re-scan

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#233]
Since we use pruned nodes in BTCPay, in case of the stuck funds in channels, recommended course of action is to connect to a full archival node (not pruned) and then force a full wallet re-scan in order to recover the funds from LND channels.

@BobleChinois I know you did something similar? I'd personally benefit from this. @NicolasDorier also had an idea to document this, so any guidelines are helpful.

Can be added to Lightning FAQ imo.

**Comment by pavlenex** [comment]
[Context.](https://github.com/lightningnetwork/lnd/issues/3047)

**Comment by NicolasDorier** [comment]
The problem is that you can't do full wallet re-scan without some go voodoo.

**Comment by pavlenex** [comment]
Can we document the voodoo magic that's needed? I guess if we can make a step by step it may help people. I think people will keep experiencing problems like this once they begin closing channels. 

Perhaps my situation is isolated, but I'd really like to get my $300 in BTC back :D

**Comment by BobleChinois** [comment]
Hi, I indeed did something like this, I wrote [an article on my blog](https://www.sosthene.net/story-btcpay-lightning-wreckdom/) about it.
The go voodoo is in fact not very complex, the worst part was the 24h rescan and the constant cp of my `.lnd` dir back and forth that was very stressful
It's probably not detailed enough, but maybe we could use this as a basis.

**Comment by NicolasDorier** [comment]
@BobleChinois I am amazed by your motivation to rescue your funds, I would have considered me reckt.

**Comment by pavlenex** [comment]
@BobleChinois sounds good. Would you like to tackle it in a step by step way?
I can be a genie pig and test out the tutorial provided.

**Comment by BobleChinois** [comment]
@pavlenex ok I'll try to lay it down in a clear step by step tuto by next monday I hope
@NicolasDorier "motivation" is a nice word for "stubbornness" here, there wasn't really much bitcoin there

**Comment by BobleChinois** [comment]
Hi @pavlenex, I tried to sum it up [here](https://gist.github.com/BobleChinois/cd6f74689b0d630e735b5f1b4b72d93b), but it's been a while so let me know if something is unclear or if you encounter any issue, I'll assist as best as I can

**Comment by pavlenex** [comment]
I'm closing this issue, since there should be a better approach to this [as discussed here ](https://github.com/btcpayserver/btcpayserver-docker/issues/179).
