### ISSUE TITLE
Separate Basics and Getting Started Sections

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#252]
We should separate :
- Basics
  - Introduction
  - Use Case
  - BTCPay vs others
  - Try it out
- Getting Started
  - Register account
  - Creating a store
  - Connecting a wallet

**Comment by britttttk** [comment]
I agree with that. Perhaps it should be: 
- Basics
    - List
- Deployment
    - List
- Getting Started
    - List 

Since this is the order of the actions the user needs to take.

**Comment by britttttk** [comment]
@pavlenex I was thinking about possibly creating a header in the readme (Introduction page) called Production Ready which can contain some advanced things like SMTP. My reason being that some of the future OpenID stuff might be able to go under the new Production Ready header... or some other name. 

- Basics
    - List
- Deployment
    - List
- Getting Started
    - List
- Production Ready
    - List

@Kukks do you have any plans for how to document those future features?

**Comment by pavlenex** [comment]
@britttttk We can just mention email setup in the getting started if you want?
I'm not a fan of `Production Ready` term. I'd rather we have a separate dev doc for Kukk's openid stuff, afaik it will be documented separately, would be great if it can be under Development.

**Comment by pavlenex** [comment]
Discussed with @britttttk and at this point, it's hard to make this work with gitbook and we'll loose on visibility.

**Comment by pavlenex** [comment]
Re-opening this, since the only way to add newly created wallets setup will be by breaking it into tiny chunks.

**Comment by pavlenex** [comment]
To-do:
- [ ] **Part 2**, which will add ConnectWallet.md, LedgerNanoS.md. ColdCard.md

- [ ] **Part 3** should connect all pieces together, by altering summary.md, removing unnecessary parts of the GettingStarted.md and updating the readme. It will also nest all the wallets into "Connecting a wallet" section.
- [ ] **Part 4** should tackle payment testing and "What to do next" (What to do next section is yet to be discussed.)

Once all of the planned pull-requests get merged, we should be able to finish  #252 #267 #281 #213

**Comment by pavlenex** [comment]
A bit of an update.

For now, we have:

## Basics
- Introduction
- Use Case
- BTCPay vs others
- Try it out (needs some work #280)


## Getting Started
- [Register account](https://github.com/btcpayserver/btcpayserver-doc/blob/master/RegisterAccount.md)
- [Creating a store](https://github.com/btcpayserver/btcpayserver-doc/blob/master/CreateStore.md)
- Connecting a wallet (Wallets.md)
  - [Wasabi](https://github.com/btcpayserver/btcpayserver-doc/blob/master/WasabiWallet.md)
  - Coldcard ([WIP](https://github.com/btcpayserver/btcpayserver-doc/pull/307))
  - [Electrum](https://github.com/btcpayserver/btcpayserver-doc/blob/master/ElectrumWallet.md)

**Comment by Eskyee** [comment]
very clean simple to read, and follow along,  will use this in my slides ;)
