### ISSUE TITLE
Add set apps on website root to FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#254]
It's only briefly mentioned in the walkthrough.md doc under server settings.

**Comment by pavlenex** [comment]
Only do this after #[887](https://github.com/btcpayserver/btcpayserver/issues/887), as it will change the UI most likely.

**Comment by britttttk** [comment]
If anyone has this question, for now it's an option under: Server Settings > Policies

**Comment by britttttk** [comment]
:) was merged in [898](https://github.com/btcpayserver/btcpayserver/pull/898)
