### ISSUE TITLE
Improve SMTP FAQ or create doc

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#267]
It would be better if we could improve the SMTP documentation for the following reasons:

- FAQ calls it SMTP but doesn't mention the word email, which is not very helpful to new users. Also in UI it's called email server settings, not SMTP. I understand smtp is a common term but not for new users who are learning about this technology by using BTCPay.

- Clarification about: SMTP for Store vs Server, what setting it will enable (i.e. Invoice Email Notification in Apps, password reset, requiring email registration), etc. 

- As of right now it exists in docs here: 
walkthrough.md mentions SMTP for email registration 
~gettingstarted.md mentions SMTP for password reset~
FAQ mentions configure SMTP settings

**Comment by pavlenex** [comment]
In #252 I plan to have CreateAccount md, that has `Configure e-mail`if you're not happy with it, feel free to tackle it once we clean that new structure.

**Comment by pavlenex** [comment]
@britttttk should we close this one, we do mention SMPT on the Create Account page?
