### ISSUE TITLE
DNS configuration videos

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#277]
Lots of newbs are confused about DNS configuration, so maybe a series of quick videos and improved changedomain.sh can help them

- How to configure your DNS and set BTCPay Domain
- How to change your BTCPay domain
- How to use a free domain with your BTCPay
- How to map apps to specific domain in BTCPay

**Comment by Eskyee** [comment]
agreed, for the first time many newbs won't understand things like 
dns & link between domain name to IP address. 
it was a nightmare. for me, jaja, IP to domain name, A records etc etc ,
Excellent Pav  good idea! looking forwards to another batch of great vids ;)

**Comment by pavlenex** [comment]
After some thinking, this could be added to changedomain.md which would then need to be abstracted from Azure deployment since it doesn't refer to Azure only.

**Comment by pavlenex** [comment]
I give up on making a video about this, there are way too many different providers, all a person has to do is google. We can try to better document it by adding some pointers.
