### ISSUE TITLE
Add "Can I connect to BTCPay’s Bitcoin P2P on port 8333?" to FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#283]
## There are two reasons why we don't do this for now:

- This is not in the interest of the user. It increases his bandwidth requirement.
- We are whitebinding connections to this port, so opening it would expose to DDoS

Some btcpayjungle users and others asking about this.

Probably should go under Deployment FAQ but could be better to start a Developer FAQ?
@pavlenex what do you think? I think it could be a good addition for users since we don't have dev doc yet.

Some other info [about this](https://medium.com/@pierre_rochard/bitcoin-and-lightning-nodes-port-forwarding-faq-f92ca5c50d5d).

**Comment by pavlenex** [comment]
I'm not sure I've seen anyone asking this. BTC-P2P is available under services, which means only to server admins, so not really sure how this relates to third-party hosts?

**Comment by britttttk** [comment]
@pavlenex https://github.com/btcpayserver/btcpayserver-docker/pull/169

**Comment by britttttk** [comment]
https://github.com/btcpayserver/btcpayserver-doc/blob/6bcbb77efdff8f986473e6e97a79a3caf5fba5c4/img/Stack.svg shown in this diagram also.

**Comment by maltokyo** [comment]
I have asked this some time back too, I would like to expose 8333 at least on LAN

**Comment by britttttk** [comment]
@maltokyo this is only an issue to document the inability to connect on 8333. If you're requesting this as a feature, please consider requesting in the btcpayserver or btcpayserver-docker repo if you haven't already. :)

**Comment by wiz** [comment]
Please re-open this issue after merging https://github.com/btcpayserver/btcpayserver-docker/pull/169 - as the `opt-unsafe-expose` custom docker fragment becomes available as a feature, users need to be warned to only enable this unsafe option when on a trusted LAN and/or with firewall rules restricting port 8333 to whitelisted hosts.

**Comment by maltokyo** [comment]
Thank you for the information and the option. What is the issue again, what
can an attacker do if they have access to 8333? I don’t really get this.
Isn’t every normal full btc node open on this port for connections? Sorry
for my ignorance.  I don’t understand the risk and a google search didn’t
answer why this is unsafe.

**Comment by wiz** [comment]
@maltokyo it's because btcpayserver-docker currently configures bitcoind to treat incoming connections as "trusted" using the `whitebind` parameter in `bitcoin.conf` - if you're only exposing the TCP/8333 port on your LAN or to certain other specific trusted hosts, you should be fine, but if you want to expose it on the Internet you'd need to implement another custom fragment that exposes the ports in the default untrusted way.
