### ISSUE TITLE
Document domain setup

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#301]
We get a lot of people lately troubleshooting issues with their domain, and it mostly comes from people not using an actual domain and instead go for a private local setup that is not accessible externally. If they want to do this, the requirement is that they use a domain name that ends with `.local`.

**Comment by pavlenex** [comment]
Stuff from #314 added by @dennisreimann got lost when I merged the #328, probably because it was not picked up by Git due to the large deleting of the files. My bad. Needs to be added again.
