### ISSUE TITLE
Improve WhatsNext.md

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#313]
The final steps in the Getting Started section need some love.

1. Add Contents Table for all use cases
2. Link to Payment Requests, PoS, Pay button, crowdfunging etc
3. Invite people to join the community, read faq and ask questions, and invite developers and others willing to contribute.
4. Add payment button demo page @vswee is working on, removed in #330

**Comment by Eskyee** [comment]
I think 🤔 it’s a good idea to a put link to a store section, create and manage store settings , add to ui with a simple explanation for noobs, on docs  since their are links for all the other features!!
