### ISSUE TITLE
Split WebDeployment.md and LunaNode.md once more providers appear

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#325]
There are a few hosting providers working on their own 1-click deployments. 

Once there is more than 1 provider offering web-deployment, WebDeployment.md should be a generic page explaining web deployment process and linking to instructions for particular hosts.

**Comment by britttttk** [comment]
> Once there is more than 1 provider offering web-deployment

Perhaps the issue should be closed until then.

**Comment by pavlenex** [comment]
There's one coming soon ;)

**Comment by pavlenex** [comment]
Closing this until we add configurator, and will propose a re-structure in #501
