### ISSUE TITLE
Add "What is a derivation scheme?" to FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#340]
Users who create a new invoice without a derivation scheme receive this warning which does not provide information about what it is or how to obtain one.

![warning_noxpub_invoices](https://user-images.githubusercontent.com/39231115/66369481-d10a8700-e959-11e9-9b82-2616ad41c4e4.jpg)

**Comment by pavlenex** [comment]
Done in #355 🚀
