### ISSUE TITLE
Dotnet Version 3

### ISSUE THREAD

**Issue by krvcrypto** [btcpayserver/btcpayserver-doc#349]
Instructions for manual install should be updated to reflect Dotnet version 3 requirement.  When I attempted to manual install, it refused to install with version 2.  It worked after upgrading Dotnet 3.

**Comment by NicolasDorier** [comment]
@krvcrypto NBXplorer is on version 3.0, and BTCpayServer is on 2.1.

**Comment by NicolasDorier** [comment]
BTCpayServer will stay on 2.1 until december (https://github.com/btcpayserver/btcpayserver/pull/1070)

**Comment by pavlenex** [comment]
Got a feedback from someone who tried manual install:
`== ''">netcoreapp3.0</TargetFramework>`
 Change `netcopeapp3.0` to  `netcoreapp2.1` we should add it to docs.

**Comment by pavlenex** [comment]
Ok, we can now update this since we're on 3.1 since 3 days ago.
