### ISSUE TITLE
Offer Ledger xpub help during deriviation scheme select

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver-doc#357]
Users with more than 20 accounts in their Ledger have an issue finding the right account within the select because it's confusing and it shows a maximum of 20 entries.

A simple link to future docs via #340 and #355 might do it.  
Also a combination of this and some more detailed info on the spot could help.

I [created the MR](https://github.com/btcpayserver/btcpayserver/pull/1115) before this issue. This is opened for documentation reasons and further feedback. 

I am ok with whatever outcome. I can also support on the docs if wanted.

**Comment by pavlenex** [comment]
I'm not quite familiar with documenting this, so if you can help, would be great.

I suggest we add a section [here](https://github.com/btcpayserver/btcpayserver-doc/blob/master/LedgerWallet.md).

**Comment by pavlenex** [comment]
Done in #358 🚀
