### ISSUE TITLE
Document ElectrumX

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#363]
[This PR](https://github.com/btcpayserver/btcpayserver-docker/pull/217) by @maltokyo introduces ElecturmX support that should all people to connect their electrum to their full node in BTCPay. However, from what I understood it only works with LND implementation.

Would be great to provide **step by step** instructions on how to set this up in [ElectrumWallet.md](https://github.com/btcpayserver/btcpayserver-doc/blob/master/ElectrumWallet.md) so newbs don't leak their info to third-parties when using Electrum anymore.

@maltokyo seems like the best person to do this, if up for a bit of documentation challenge.

**Comment by maltokyo** [comment]
With the helpful advice from @NicolasDorier it now works without LND activated, only reqt is txindex=1 on the BTCPay full bitcoin node which this PR also will activate out of the box. That said, I have no problems to write a step by step guide including some of the quirks I encountered with Electrum itself, which @kyuupichan helped me to solve. In general, except for the need to reindex bitcoin node (a one time thing), it works flawlessly for me.

**Comment by pavlenex** [comment]
Awesome news!

Just to understand a bit of the mindset of typical BTCPay user using Electrum:

*Most likely a merchant, not tech-savvy a merchant that has no hardware wallet to use directly with BTCPay Internal wallet.*

That's why it needs easy to understand step by step.

Would be great if you can take over this one, you're better familiar with Electrum and you did that PR, which I'm sure will be extremely helpful to people using Electrum + BTCPay.

**Comment by maltokyo** [comment]
Yes. Sure. No problem. How do I “take over” that document into my PR. Can I just start editing it as part of my PR? Or separate one?

**Comment by pavlenex** [comment]
Since documentation is different repository than btcpayserver or btcpayserver-docker where you did a PR, best approach is to do a new PR, fork [btcpay-doc](https://github.com/btcpayserver/btcpayserver-doc/) repo and then change [ElectrumWallet.md](https://github.com/btcpayserver/btcpayserver-doc/blob/master/ElectrumWallet.md) file.

![Screenshot 2019-11-07 at 09 43 15](https://user-images.githubusercontent.com/36959754/68373357-09f96f80-0143-11ea-9b7c-01c48dc79e50.png)

You will see that in that document, I've mentioned Electrum Personal server, feel free to alter that with ElectrumX and link that section on the page, where you can show people how to set up their ElectrumX once they've set up their Electrum.

**Comment by maltokyo** [comment]
Got it 👍🏻

**Comment by astupidmoose** [comment]
> With the helpful advice from @NicolasDorier it now works without LND activated, only reqt is txindex=1 on the BTCPay full bitcoin node which this PR also will activate out of the box. That said, I have no problems to write a step by step guide including some of the quirks I encountered with Electrum itself, which @kyuupichan helped me to solve. In general, except for the need to reindex bitcoin node (a one time thing), it works flawlessly for me.

Does the need to reindex effectively stop Bitcoin from being accepted while this is going on? What is your experience in how long this takes? 

I'm looking forward to this implementation but would like to know what the txindex entails.

**Comment by maltokyo** [comment]
Actually, when I switched on txindex while testing, the downtime was mere
minutes. I did notice though that it smartly started making the txindex
from somewhere in the 500k blocks. I don’t know why it started there...
maybe just it’s setup to not start from genesis, but from an appropriate
period (past 6months?).
I then (made the mistake?) of trying reindex = 1. I don’t recommend this as
it started indexing from genesis block and was extremely slow!! So I turned
that off and went back to just txindex. Things seems fine now.. but I can’t
comment on what your wallet will do if it needs a really old txindex.

**Comment by maltokyo** [comment]
Started this here: 
https://github.com/maltokyo/btcpayserver-doc/pull/1/files

**Comment by pavlenex** [comment]
Yes, this is great progress so far! Once we have the  entire doc, I can review it. Good job so far, and very well-explained. I like how you split it into two parts.

**Comment by maltokyo** [comment]
OK, I have had a good first shot at it.  Maybe some improvements but it is fully covered from my side now.  Could you please review @pavlenex ?  Any suggestions welcome.  Omg, while I agree that documentation is mandatory, it really is painful to create.  I see all the effort that you put into this, now that I contribute myself..! ;)

https://github.com/btcpayserver/btcpayserver-doc/pull/367

**Comment by pavlenex** [comment]
#387
