### ISSUE TITLE
Change images in getting started and walkthrough

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#365]
New BTCPay page, will now be a login page. It would be good idea to alter the walkthrough.md and gettingstarted.md with new image design and change text if necessary.

**Comment by britttttk** [comment]
- [RegisterAccount.md](https://github.com/btcpayserver/btcpayserver-doc/blob/master/RegisterAccount.md) update image and text (gettingstarted)
- [Walkthrough](https://docs.btcpayserver.org/btcpay-basics/walkthrough) it is the same welcome page still I believe. Does not need change it seems.
