### ISSUE TITLE
How to create P2SH wallet in Electrum

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#368]
When #363 is done, we should add a paragraph that will teach merchants how to create p2sh wallet (addresses starting with 3), since not all wallets support Bech32 (addresses starting with bc1) and as a merchant you most likely want compatibility with majority of wallets, so p2sh is a solution.
[Blockonomics created a guide ](https://twitter.com/blockonomics_co/status/1192379761730805761)for their customers that we can add to the docs (I've asked them and they allowed it)

**Comment by Kukks** [comment]
I'd also like to add another option for this that I've come to like via Transmuter:

Generate a seed( in transmuter we have this screen for example)

![image](https://user-images.githubusercontent.com/1818366/68470852-31246f80-021d-11ea-8816-a03b476b2210.png)

* Choose the address type(legacy, segwit, p2sh)
* Copy the compatible xpub to btcpay's store
* save the mnemonic seed or WIF in a password manager

To spend, you go to the BTCPay wallet, create a transaction and sign with the key or seed you saved in the password manager.

BOOM, using a seed you generated on your own, with no external leaks and using only BTCPay to receive and send.

Of course, this is only as secure as your password manager is so enable 2FA or U2F on it if possible and also consider using a secondary wallet  to store big funds on.

**Comment by pavlenex** [comment]
This one can now be addressed.
