### ISSUE TITLE
Launched on LunaNode, lightning isn't working

### ISSUE THREAD

**Issue by RyanSinger** [btcpayserver/btcpayserver-doc#37]
![image](https://user-images.githubusercontent.com/2665386/46577480-4a0f8f80-ca23-11e8-8ecb-fcd86547cb08.png)

**Comment by NicolasDorier** [comment]
Does your node fully synched?

LND does not start until your node get synched.

**Comment by RyanSinger** [comment]
Ah. Thank you. I'll wait for the sync.

Ryan

**Comment by bitcoinshirt** [comment]
It seems your issue was with Lightning not being synced. Closing this now.
