### ISSUE TITLE
Should "Where can I find recovery seed backup..." be updated with latest `zlndseedbackup` release info?

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver-doc#383]
I just did the update and while searching the info on how to migrate I found the [blogpost (which was very helpful)](https://blog.btcpayserver.org/btcpay-lnd-migration).  

But first place I was looking for info were actually the docs, specific: [Where can I find recovery seed backup for my Lightning Network wallet in BTCPay Server?](https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#where-can-i-find-recovery-seed-backup-for-my-lightning-network-wallet-in-btcpay-server)

Should the new release be mentioned? Should the blog post be linked?

**Comment by pavlenex** [comment]
Yes, good idea, these should be updated for LND.

**Comment by escapedcat** [comment]
Ok, cool. Let me see what I can do.

**Comment by pavlenex** [comment]
#384
