### ISSUE TITLE
Synchronization FAQ needs instructions for stopping internal node...

### ISSUE THREAD

**Issue by dscotese** [btcpayserver/btcpayserver-doc#385]
In the last section of the FAQ/FAQ-Synchronization.md file, the instructions assume that you stopped the external node.  Another solution is to stop the internal node, if that is even possible, but there are no instructions to do that.  A simpler solution is to add "Stop the external node that was updating the Bitcoin data directory." to the list of steps.

Another solution to this is for the code to check the path it uses for bitcoin data to see if it's a link, and if so, assume that it doesn't need the internal node when it starts.

**Comment by pavlenex** [comment]
#386
