### ISSUE TITLE
add LND backup info with link to LND readme to docs

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver-doc#390]
As @britttttk suggested here's the issue regarding LND backup info.

It's already mentioned in the application...
![image](https://user-images.githubusercontent.com/1016218/70427970-f4df6b80-1a75-11ea-92c3-766121bf2767.png)

...but it might be nice to add this to the official docs as well.

Could be added as an additional item here for example: 
https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lightning-network-lnd-faq

What do you think? I'm happy to help with this.

**Comment by pavlenex** [comment]
@escapedcat  It's a good idea, feel free to lead on the issue.

**Comment by Zaxounette** [comment]
@pavlenex @britttttk  LND Seed backup is documented here: https://docs.btcpayserver.org/FAQ/FAQ-LightningNetwork/#where-can-i-find-recovery-seed-backup-for-my-lightning-network-wallet-in-btcpay-server

Is it sufficient ? Or does it need something else ?

**Comment by escapedcat** [comment]
@Zaxounette I think this is done by now.  
The current version came out of this: https://github.com/btcpayserver/btcpayserver-doc/issues/383  

Looking at this issue now I am not even sure anymore what might be missing.  
Reminder to myself: "_be more detailed and specific when opening an issue that you might come back to 6 months later_".

I'll close this.
