### ISSUE TITLE
Add How to change default exchange rate provider to FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#399]
Issue: [BitcoinAverage removed the "Free" tier plan](https://github.com/btcpayserver/btcpayserver/issues/1230) 

Add FAQ to explain how to change rate provider.

**Comment by britttttk** [comment]
@NicolasDorier rate provider is by store right? So then for each store, user needs to choose another default provider in Store Settings > Rates > Preferred price source 

Is there a new recommended default?

**Comment by NicolasDorier** [comment]
@britttttk I should make a new version with a different default. This suck because this is not easy to know what a good default is :(

**Comment by uakfdotb** [comment]
There is no way to change the provider without editing the code right? I mean I think they are all from BitcoinAverage, the options seem to just be different exchanges that BitcoinAverage pulls the data from.

**Comment by NicolasDorier** [comment]
@uakfdotb kraken as less available pairs.
