### ISSUE TITLE
Decision chart for deployment

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver-doc#404]
I am creating a decision chart and I am waiting for some feedback.

![image](https://user-images.githubusercontent.com/3020646/71568614-0a433500-2b0c-11ea-9b46-d563b726cd41.png)

I will apply the lipstick once the content is good enough. @britttttk @pavlenex

**Comment by NicolasDorier** [comment]
There is other alternative to nodlit, but I can't remember names

**Comment by britttttk** [comment]
This is great. It's really good for explaining choices.

**Comment by NicolasDorier** [comment]
This will be added to this page.

https://github.com/btcpayserver/btcpayserver-doc/blob/73ef16b3c916ad8ff9a2d7dd3a60404b56cc48a7/Deployment.md#btcpay-server-deployment

**Comment by NicolasDorier** [comment]
v2

![image](https://user-images.githubusercontent.com/3020646/71569698-509c9200-2b14-11ea-83e5-07bc4e600ab4.png)

**Comment by britttttk** [comment]
ACK

**Comment by NicolasDorier** [comment]
Final version:

![DecisionDiagInstallBTCPayServer](https://user-images.githubusercontent.com/3020646/71572461-98c2b100-2b22-11ea-9278-5a830604d71c.png)

**Comment by pavlenex** [comment]
Nice,I would avoid advertising particular hosts (LunaNode, Hack0, etc) and rather point them out to generic term "Web Deployment", because in future we may have more of these and then it'll be confusing for people.

I also am not sure about first step. First step should point to third-party hosting and then to self-host.

**Comment by NicolasDorier** [comment]
@pavlenex there is no generic Web deployment right now, there is no alternative to LunaNode.

**Comment by NicolasDorier** [comment]
I think we can rewrite those when we actually have generic web deployment and more boxes.

**Comment by pavlenex** [comment]
Well if you are wiling to update it, then okay. Make sure to keep the file in the format that is easy to edit later on.

**Comment by NicolasDorier** [comment]
yeah I commited the visio file
