### ISSUE TITLE
Add SSH instructions

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#427]
We should add https://github.com/JeffVandrewJr/patron/blob/master/SSH.md to the docs to aid non-technical people with restarting, troubleshooting, etc

**Comment by pavlenex** [comment]
We do have sth in FAQ that already redirects to Jeff doc.

https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-ssh-into-my-btcpay-running-on-vps

**Comment by pavlenex** [comment]
@Kukks Is this good enough or you have something else in mind?

**Comment by Kukks** [comment]
They're very specific to LunaNode, can we maybe create another more generic one?

**Comment by pavlenex** [comment]
I assume whoever uses a non web-deployment method knows ssh, but I assume we can create a generic one.

**Comment by pavlenex** [comment]
#464
