### ISSUE TITLE
Add a doc about front-end customization options

### ISSUE THREAD

**Issue by ch4ot1c** [btcpayserver/btcpayserver-doc#43]
Perhaps:
- a script / instructions how to set an app (or a blank page) as the homepage
- a simple example webpage with an invoice button

And a docs section about the Theme part of the settings

**Comment by bitcoinshirt** [comment]
I think this is way too complicated or a regular user currently. Here's what's currently documented on the Wiki  https://nbitstack.com/t/how-to-edit-the-styling-of-btcpay-front-page/65

I would wait until there is a front-end way to do this without maintaining your own fork.

**Comment by ch4ot1c** [comment]
Somewhat related: https://github.com/btcpayserver/btcpayserver/issues/332
