### ISSUE TITLE
Add a doc about Derivation Scheme (HD wallet setup) config

### ISSUE THREAD

**Issue by ch4ot1c** [btcpayserver/btcpayserver-doc#44]
Currently the derivation scheme settings are not very clear. I am familiar with the different types of HD wallets, but no derivation path I use as input seems to be valid. I've tried `xpub` like in the table, and `m/44'/0'/0'/0` which is the BIP44 scheme. I'm sure this works for Ledger, but I can't quite figure out what to do in the text field.

Also, there is no `Check ExtPubKey` (on a Ledger only?)

**Ah I see now** - `BTCPay format memo` is a table where you insert your xpub(s) instead of the token `xpub` (or `xpub1` or `xpub2`) - and it gives you a followup prompt to confirm addresses.

I think it would be good to have a guide / link to information about generating an offline xprv/xpub, even if they dont have a Ledger

**Comment by NicolasDorier** [comment]
I advise against generating keys yourself. People who knows how to do this can do it, people who does not, should not do it.

**Comment by bitcoinshirt** [comment]
Does the link above your question @ch4ot1c? If so, can we close the issue?

**Comment by ch4ot1c** [comment]
Yes, I'll keep in mind that we aren't recommending manual/offline generation of xprvs. Thank you - closing.
