### ISSUE TITLE
Possibility to customize invoice list fields

### ISSUE THREAD

**Issue by alexandre-a** [btcpayserver/btcpayserver-doc#461]
Hi,
I would like to know if it could be possible to customize the invoice list fields.
By default, it's not really user friendly ! I would like to show directly : "Item Description", "Fiat currency amount", etc.

**Comment by pavlenex** [comment]
Hello 👋 

That's not currently possible. Also documentation repository is wrong repository to ask questions. 

The support type of questions are better to ask on our [chat.btcpayserver.org.](https://chat.btcpayserver.org)

If you would like to submit this as a feature request, [re-open the issue in the main r](https://github.com/btcpayserver/btcpayserver/issues)epository by following the [feature request issue template.](https://github.com/btcpayserver/btcpayserver/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)
