### ISSUE TITLE
Consolidate RPI documentation

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#467]
- [ ] Add disclaimer in RPI3.md that it's not mean for production due to stability issues and lack of RAM.
- [ ] Improve RPI4 docs and standardize them, as it's hard to follow up and one as to look at both RPI3 and RPI4 docs to deploy things on RPI.
- [ ] Suggest RPI Imager and Balena etcher instead of CLI method

**Comment by dennisreimann** [comment]
I'd say we should prevent any ambiguity by removing the RPi3 doc as usage is discouraged anyways. We can consolidate the RPi docs, but in the end there should be one clear way to setup and run on the Pi.

**Comment by pavlenex** [comment]
I agree, but problem is we cannot simply remove RPI3 docs as some parts of it are better explained than in RPI4 docs. From users feedback, people use both. So for this to be closed, we'd have to not only consolidate but also improve documentation so they are suited for RPI4 as recommended option but can be used on RPI3 as well. 

If anyone experienced with RPI wants to take over this challenging task, feel free to. I wanted to but my experience on this is not enough imo. Would be happy to test and help out with review nevertheless.

**Comment by pavlenex** [comment]
To remove ambiguity as Dennis pointed, we should:
- Delete RPI 3 and 4 docs
- Create a new RPI 4 document that is concise but in-depth. 
- Specifically, recommend RPI4 on that page and tell RPI3 is not recommended for production, though may work.

I believe we'll need a straightforward document, that should focus solely on deployment and won't go too much into the "personal preference" side of things.

If there are RPI wizards that would like to help us document this, let us know.
