### ISSUE TITLE
Can be used with another blocks in nginx?

### ISSUE THREAD

**Issue by renguer0** [btcpayserver/btcpayserver-doc#475]
OK, I'm using [that nginx config file](https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination) but I see that enters in conflict with another blocks.

Can we have btcpayserver working with another instances as Drupal or Discourse?

Thanks for your time.

**Comment by britttttk** [comment]
@renguer0 I'm not sure exactly what you're asking. Can you check if this Drupal doc helps you https://docs.btcpayserver.org/integrations/drupal

**Comment by pavlenex** [comment]
This is really wrong repo for this question and from what I remember was already replied on Mattermost.
