### ISSUE TITLE
Document how to use different wallet keypaths

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#482]
I believe that Vault will use Account 0 by default. Explain in docs how to choose different accounts. 

![InkedScreenshot 2020-04-14 at 19 03 12_LI](https://user-images.githubusercontent.com/39231115/79258577-932a7600-7e48-11ea-8bf4-1c5c839ce533.jpg)

**Comment by pavlenex** [comment]
This is so tricky to explain. It's not just a keypath, it's the masterfingerprint that needs to be added. I think this is only useful if you have an externally connected wallet via xpub, then you want to sign a tx with a seed. Usually this sort of information is **auto** added when generating a new wallet (including the hot wallet) and when using vault.
