### ISSUE TITLE
Add documentation about Liquid

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#488]
Include this Liquid info somewhere in docs/FAQ:

https://github.com/btcpayserver/btcpayserver/issues/1282

**Comment by pavlenex** [comment]
I think the most appropriate place would be in the [Altcoin-FAQ](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-Altcoin.md).

**Comment by pavlenex** [comment]
This can probably just be a link to the issue. 
Q:`How to add liquid` 
A: `check this guide.`

Doesn't need to be anything more than that imo.

**Comment by Zaxounette** [comment]
I see that [here](https://docs.btcpayserver.org/FAQ/FAQ-Altcoin/#which-coins-btcpay-server-supports) is a link to #1282. Is it considered sufficient ?

Furthermore @pavlenex, I feel like the docs in general would be better if a maximum of informations be included inside it, instead of having multiple links going out of the docs like this issue, where we are redirect to a github issue instead of having the information readily readable.

Thoughts ?

**Comment by britttttk** [comment]
>having the information readily readable

@Zaxounette I agree. I think it would be better to move the information/images from that isuse and put it in the FAQ. Especially since that FAQ does not contain very many questions anyways. Besides the images I think this is the only important info from the comments:

@Kukks @NicolasDorier looks good or have more info for these?

Q: Can I restore funds with the seed created in BTCPay for Liquid. 
A: No it's not possible because ScanUTXOSet is not supported for Liquid in BTCPay.

Q: Is it possible to spend Liquid using NBXplorer without saving the private keys and use an RPC call to a Liquid node?
A: No. (?? not sure why or if this is relevant)

Q: What are the recommended specs for the storage of L-BTC?
A: It is recommended to provide an additional 10GB of storage specifically dedicated to L-BTC. (On top of the pruning size)

**Comment by Zaxounette** [comment]
It's a hell of a lot of informations for the FAQ.
It might be better to have a specific docs page for Liquid, and have FAQ questions and answers in the FAQ, and add "more informations" links to the FAQ answers that go back to the full Liquid docs page for those who need more indepth informations ?

**Comment by britttttk** [comment]
@Zaxounette I thought about it and I think maybe we should keep it the way it is for now. Reasons being most importantly:
- a lot of info and Liquid will take of Altcoins FAQ page
- we do not make a page for any of the others on that page such as Monero has a similar link 

For now I think we should keep it as it is actually, I think when I made the issue I didn't see the link you mentioned above. @Zaxounette if you really want to make the Liquid page we can discuss, it's not a high priority doc for me personally :)

**Comment by Zaxounette** [comment]
> * we do not make a page for any of the others on that page such as Monero has a similar link

@britttttk A good point. We'd kind of be obliged to do the same for every single Altcoin if we do it for Liquid.
If we can avoid unnecessary politics by not doing it, fine by me =)

**Comment by britttttk** [comment]
@pavlenex any objection to closing this?
