### ISSUE TITLE
Document how to edit server configuration.

### ISSUE THREAD

**Issue by orfeas0** [btcpayserver/btcpayserver-doc#489]
Trying to setup SMTP, I found this:
[https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay)

Nowhere can I find where I have to insert those settings. Is there a server config file somewhere?
I have installed through docker btw.

I found `settings.config` in the `btcpay_datadir` but it is all commented out.

Off-topic, about SMTP setup: Through the web GUI, there is no TLS option available, only SSL.

**Comment by pavlenex** [comment]
In GUI, Server Settings.

**Comment by pavlenex** [comment]
For general questions in the future please use our [community chat,](https://chat.btcpayserver.org/) we use issues for bug reports and to-do.
