### ISSUE TITLE
Translation.md

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver-doc#49]
Proposal to add 2 new documents : Translation.md and Contribute.md inside the Contribute folder.

## Translation.md

There are many non tech-savvy users who want to contribute to BTCPay but they just don't know how. 

Currently it's only possible to translate the checkout. Until we figure out the system how to do handle front-end translations, I believe it would be beneficial to create **Translation.md** and teach these users how to help with translations step by step.

~~## Contribute.md~~

~~Build on this and expand to other use-cases.~~

> ~~How can I contribute to BTCPay? The easiest way is to use the software for your business, provide feedback and report any bugs or issues you or your customers encounter. Translating BTCPay, helping us with documentation are also ways in which you can help, even if you're not a developer or tech-savvy.~~

**Comment by britttttk** [comment]
I can help with working on the translation.md file. I think it's a good idea. 

I looked into translation options recently. Bitcoin Core uses Transifex which I think is $140 per month for ~4500 strings. BTC Pay checkout page is only about 250 words. Transifex uses three translation services (one internal and two external providers). One of the external providers is Gengo. 

I tried their services to check them out and purchased Vietnamese, Ukrainian, Hindi. It costs between $15 and $30 per language with a "crypto specialist" translator, to translate the checkout page. I still haven't had a translator accept the Hindi request so I don't think it's totally automated. 

Just some information about translation options for future considerations.

**Comment by bitcoinshirt** [comment]
@britttttk Awesome. I've used Transifex in past. If I'm not mistaken, it's free for open-source projects. I will contact them to ask.

I was thinking we can create a simple translate.md with a brief introduction and then tackle:
1. Translating the checkout page
2. Translating the front-end - we will tackle this one in the future.

Since currently, it's a bit tricky, I think we need to make a step by step for translating the checkout page. 

Feel free to create a new file when you can and start working on it, if you need any help, feel free to ping me.

**Comment by bitcoinshirt** [comment]
Transifex is free for open-source. [Here's a step by step how to apply](https://docs.transifex.com/projects/open-source-project)  if you're interested in creating it for the future. You appear to have better experience with Transifex than I do.

**Comment by britttttk** [comment]
Ok that's awesome. I think it would be much better for non-tech savvy users who want to do translations. I can look into setting up an account to check it out. I'm not really a GitHub workflow expert though in terms of integration. [https://docs.transifex.com/integrations/github](url). Would need someone to look into the best option for that.

I'll create the Translation.md file first.

**Comment by britttttk** [comment]
@bitcoinshirt if you assign this to me, I will post when [#369](https://github.com/btcpayserver/btcpayserver/pull/369) closes

**Comment by bitcoinshirt** [comment]
Hmmm can't assign you for some reason @britttttk 
While I figure that one out, consider yourself "assigned" for this one.
