### ISSUE TITLE
Drawing a line between user documentation, dev docs and advanced?

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#501]
I had some time to go over the structure of our documentation, and it got me thinking if it's a bit too much for some and too little for the others. Our docs are currently a mixture of everything. 

Once we're done with the front-end change #495 and get the new API, it may be a good thing to consider separating user docs from dev docs. Even then the line may be blurry on what's suitable for dev and what's suitable for first time user. Then we have tech-savvy users who are okay to thinker and try stuff but don't code.

If someone here has good examples of well-presented dev docs and user docs on the front page, please let me know. Even better if someone managed to figure out a way to set simple, advanced and developers docs, please share examples.

Opening this issue for brainstorming purposes. Once the front-end is done we'll def need to focus on cleaning things up.

**Comment by NicolasDorier** [comment]
`dev docs/advanced` should be the same. User doc is to teach people click through the UI

**Comment by pavlenex** [comment]
Makes sense.

Would you consider transmuter docs a dev doc? In my opinion it's for a bit advanced users who aren't devs. 

I am trying to figure out what to display in user docs without providing too much advanced stuff and then developers mostly care about the API/Integrations/Clients.

Now that we will [soon have multi-repository docs](https://btcpaydocs.uix.space) it'll be interesting to see where we draw a line.

**Comment by NicolasDorier** [comment]
in my opinion the transmuter should have its own doc.

**Comment by pavlenex** [comment]
They do have a separate docs on GitHub we don't maintain them in this repo, we'll just use those to show on the front end as it's common documentation. At this point we have so many plugins, repositories, docker environment variables that it's impossible to expect from a user to hop through GitHub trying to connect the dots.

So multi-repositories give us the advantage:
1. Having important docs from different repositories on same front-end
2. Maintenance of those documents is up to repo maintainers, this way we avoid having to copy-paste and maintain documentation. For example take a look at[ docker-repo demo,](https://btcpaydocs.uix.space/Docker/) we can nest documentation much better now. We currently have [this](https://docs.btcpayserver.org/deployment/dockerdeployment) which is not even close to the btcpay-docker document on GitHub. 

For transmuter in-particular I'd nest it under docker-deployment as a plugin or `service` as we call them. But don't really want to go into specific docs now as it's all still just a _demo_.

But to be back on the point of this issue, I would like to have a landing page with search and then user and dev dos separated. I added FAQ just as an example.

![Screenshot 2020-05-02 at 23 25 00](https://user-images.githubusercontent.com/36959754/80892675-3b0ac500-8ccc-11ea-8012-c8fbe45834ee.png)

I guess the reason I opened the issue is to get opinions on how people perceive documentation and certain parts of it. There are lots of mistakes in current documentation structure (Deployment section is a mess since in essence most of it is docker-deployment)

**Comment by britttttk** [comment]
We also need to add mention of  `/docs` for swagger dev docs somewhere as well.

**Comment by britttttk** [comment]
Related to #174

**Comment by Eskyee** [comment]
I like @NicolasDorier & @pavlenex idea, 
BTCPay dev docs/advanced api etc etc = nerds 
BTCPay User doc is to teach people click through the UI = "Noobs"

**Comment by dennisreimann** [comment]
I think the idea of having a landing/intro page with the different sections plus some additional explanation about them is a good idea. Including the search prominently makes absolute sense too.

For the section docs (dev, user) I like how VuePress itself does it with the sections in the header (separating "Guide", "Config Reference", "Plugin" and so on – each having a different sidebar as well). This way we could also cross reference the different sections.

Leaving these links here as a reference on how we could approach this:

- [Custom homepage](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) (might not suffice as customizability is limited) 
- [Custom layout for homepage](https://vuepress.vuejs.org/theme/default-theme-config.html#custom-layout-for-specific-pages) (the fully customizable variant)
- [Navbar links](https://vuepress.vuejs.org/theme/default-theme-config.html#navbar-links)

**Comment by dennisreimann** [comment]
Implemented the aforementioned approach to provide a concrete version we can further discuss.
