### ISSUE TITLE
FAQ cleanup

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#504]
The FAQ are one big mess. There's plenty of duplicate, irrelevant, poorly structured and outdated info there that needs to be taken care of. Will post specifics once I dive deep into what must be cleaned. 

I made those FAQ and it takes me 10 min to  find an answer to a question I was looking for. Looking for #503 made me want to punch myself in the face.

**Comment by Zaxounette** [comment]
I could try and give you a cleaned-up suggestion of the entire documentation.
Will take some time though.

All I need is the outdated info that can be deleted, so that I don't work on it for nothing :p

**Comment by pavlenex** [comment]
@Zaxounette well that's the problem, someone needs to go through the outdated information and rants and remove them. I haven't looked into it yet.

What we can do is go through one by one, starting with FAQ-General.md

- [ ] Proofreading
- [ ] Removing repetitive information
- [ ] Provide concise instructions 
- [ ] Make sure all links work

FAQ-General.md in particular seems more like a blog post then a document, it's too ranty and does not provide concise information. It's also inconsistent

**Comment by Zaxounette** [comment]
@pavlenex I'm willing to work on that.
Should I wait until the migration to vuepress is done ? Or can I submit PR's regarding all of this right now ?

**Comment by pavlenex** [comment]
You can tackle it, @Zaxounette it does not influence the structure of what Dennis is working on.

**Comment by Zaxounette** [comment]
Thanks ! =)

**Comment by britttttk** [comment]
I believe Wallet FAQ is complete for this.

**Comment by britttttk** [comment]
- [ ] General
- [ ] Deployment
- [ ] Synchronization
- [ ] Integrations
- [ ] Server Settings
- [ ] Stores
- [x] Wallet
- [ ] Apps
- [ ] Lightning Network
- [ ] Altcoins

**Comment by pavlenex** [comment]
Great work on this one so far @britttttk!

**Comment by pavlenex** [comment]
@britttttk  Lightning Network FAQ seem fine, I would leave it as is unless you noticed something I missed?

**Comment by britttttk** [comment]
@pavlenex is there anything else needed for this

**Comment by pavlenex** [comment]
@britttttk I don't think so, you have the honors to close this 🎉
