### ISSUE TITLE
Document "btcpay in a box" devices

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#515]
There are lots of people selling pre-built btcpya server on a certain type of hardware. 

It would be good if we can have a document listing all the productsthat offer it. Not everyone wants to build their own, some may want a plug and play solution. 

We touched on this in HardwareDeployment.md but def can be a separate document.

On top of my head:
- [Nodl](https://www.nodl.it/)
- [Hack0](https://www.dglab.com/en/works/hack0/)
- [Lightning in a box](https://lightninginabox.co/)
- ~~Casa 2~~ (actually I don't think they ever released it)
- [MyNode](https://mynodebtc.com/)
- [RaspiBlitz ](https://raspiblitz.com/)

I am unsure of the name of this doc. It can probably be nested under hardware deployment once our new docs are ready.

**Comment by Zaxounette** [comment]
A "BTCPay in a box" cat could be added in the directory and we list all of the websites that offer them on it. 
Just adding a link to the proper cat in the directory in the related docs could do the trick.

**Comment by pavlenex** [comment]
It's quite unlikely it would be as useful there as in the documentation. In documentation, people are landing when they're learning more about the software and ways in which they can deploy it. I think a page in docs would be more discoverable and useful.
