### ISSUE TITLE
Remove thumbnails img folder

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#519]
Thumbnails were only used because GitBook couldn't embed YT videos properly. After the migration to VuePress, we can remove that folder as VuePress fetches thumbnail from YT natively.
Folder can be found in `docs/img/thumbnails/` (after the migration).

**Comment by dennisreimann** [comment]
We should keep them as we decided to go with a GitHub Markdown compatible version for the YouTube embeds, which needs the thumbnails.

**Comment by pavlenex** [comment]
We can always just use the thumbnails from YT. The reason we went with custom thumbnails is because we add play icon manually so it mimics the video layout.

YT generates images like this 
```
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](https://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE) 
```

Where `0.jpg` is whatever default thumbnail you have on YouTube.

I think this way we can save some space, but for current videos we can definitely leave it as is. I'll leave the issue opened as I think it can be something to test at least.

**Comment by pavlenex** [comment]
Can confirm that `https://img.youtube.com/vi/R-videolinkhere/mqdefault.jpg` works absolutely the same way as embedding the thumbnails manually.

So if anybody wants to tackle this issue:

- [ ] use search to find all embedded videos that have manually embedded thumbnails. 
- [ ]  Replace image link with `https://img.youtube.com/vi/videolinkgoeshere/mqdefault.jpg` for example
- [ ] Test and make sure nothing is broken
- [ ] Remove thumbnails folder
