### ISSUE TITLE
Video thumbnail rendered as images

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#525]
- [ ] Fix video thumbnails being rendered as image

[Example of a good video](https://docs.btcpayserver.org/#how-it-works)
[Example of a broken video](https://docs.btcpayserver.org/#contributing)

**Comment by Zaxounette** [comment]
I have no idea how to fix that.

For example, a good video has this code :

`[![How BTCPay Works](./img/thumbnails/HowBTCPayServerWorks.png)](https://www.youtube.com/watch?v=nr0UNbz3AoQ "How BTCPay Server Works")`

And a bad video has this code:

`[![BTCPay Server Simply Explained](./img/thumbnails/BTCPayServerSimplyExplained.png)](https://www.youtube.com/watch?v=dbX6qWZlxOw "BTCPay Server Simply Explained")`

At my level of tech-savvyness, it's the same.

**Comment by pavlenex** [comment]
@dennisreimann Seems like it didn't fix stuff. Please check as well.
