### ISSUE TITLE
Include nfo on "marked" invoices

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#540]
on https://docs.btcpayserver.org/Invoices/#invoice-statuses

**Comment by britttttk** [comment]
The marked means a manual change in status. Unless there is another way. The following invoices statuses may be manually changed (may be others):
- invalid > Mark as Complete
- invalid (paidOver) > Mark as Complete. (Seems this is the only one that can be changed after)
- expired (paidLate) > Mark as Invalid or Mark as Complete

Also I think in the [invoice statuses doc](https://docs.btcpayserver.org/Invoices/#invoice-statuses) it should be complete not completed status.
