### ISSUE TITLE
Add RBF to docs 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#541]
Maybe add to Wallet FAQ? Tooltip in the UI links to bitcoin.org RBF currently.

**Comment by pavlenex** [comment]
v 1.0.5.0 introduced:

- Privacy enhancement: Randomize wallet transaction fingerprint.
- Randomize RBF support in BTCPay wallet by default for privacy

![RBF](https://user-images.githubusercontent.com/36959754/85885354-7ca78000-b7e4-11ea-843b-f8e47cc3741c.PNG)

Should be documented together with this one.
