### ISSUE TITLE
Address FAQ question about the private key in FAQ-General

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#583]
Rephrase thi[s question that btcpay server does not require a private key](https://docs.btcpayserver.org/FAQ/FAQ-General/#does-btcpay-need-my-private-key), to work. It can generate a private key (if you create a wallet, but wipes it, unless a hot wallet is created). Importing xpub from existing external wallet is also possible. 

Context https://docs.btcpayserver.org/WalletSetup/
Tackle following:
1. https://docs.btcpayserver.org/FAQ/FAQ-General/#what-is-btcpay-server
2. https://docs.btcpayserver.org/FAQ/FAQ-General/#does-btcpay-need-my-private-key
3. https://docs.btcpayserver.org/FAQ/FAQ-General/#address-re-use-how-btcpay-creates-a-different-address

**Comment by britttttk** [comment]
I believe it's updated to this now:
3. https://docs.btcpayserver.org/FAQ/FAQ-General/#how-does-btcpay-create-a-new-address-for-each-invoice
