### ISSUE TITLE
Explain 0 Invoice

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#587]
Add FAQ and possibly reference in Invoices.md why a 0 invoice goes to paid immediately and use case explanation.

**Comment by Zaxounette** [comment]
This might be yet another proof of my technological in-expertise, but I don't grasp what use case would require a 0 invoice ?

I'll gladly document why a 0 invoice goes to paid immediately, but need help on the use case explanation.

**Comment by britttttk** [comment]
@Zaxounette it's really a particular use case where a merchant wants to have a POS with free items to collect emails or count the number of people who are interested in an event, etc. The previous alternative was like charging 1 satoshi or small amount just to get this info or use some other plugin in your website instead.. I hope that makes sense. [Here is the original PR info.](https://github.com/btcpayserver/btcpayserver/pull/1358).

It's possible in the `Invoices` page to produce a 0 invoice. @pavlenex do you think we should consider changing it here to be greater than 0? It really only serves a purpose in POS.  If this is created in the invoices page it is completely pointless as it's not even viewable other than in `details`. 

One other note fyi @Zaxounette is that this feature (when collecting emails) can't be combined with:
Store Settings > Checkout Experience > Redirect invoice to redirect url automatically after paid
If this redirect is on, it will not take the time to collect email. This is just for your reference, we should not add this to docs it will just confuse people likely.

**Comment by Zaxounette** [comment]
Thanks for the explanation. Appreciated :)

**Comment by Zaxounette** [comment]
> @pavlenex do you think we should consider changing it here to be greater than 0? It really only serves a purpose in POS.

The #1358 PR you linked says that this "feature" of 0 invoice was requested by the Nodl team. Wouldn't make sense to revert, specially if it doesn't produce any issue that can't be answered through docs.

**Comment by pavlenex** [comment]
Discussing 0 amount invoice is a painful subject that makes me cry. I don't want to go into the why, let's just document it, and perhaps discuss about whether or not it makes sense to have it one day in the main repo. A protection against 0-amount invoice has been added in the apps afaik, so only those who want can use it.

**Comment by britttttk** [comment]
I was talking about 0-invoice protection specifically in the invoices page. I will bring it up in the main repo instead of here.

**Comment by britttttk** [comment]
Using search terms to describe this question from a previous [mattermost inqury](https://chat.btcpayserver.org/btcpayserver/pl/bjxspm4aftfqfeo5wdwtidi58y) as I'm not sure exactly what users would call this issue otherwise. (Obviously 0 invoice is a BTCPay term)
