### ISSUE TITLE
Document I have a problem paying BTCPay Server invoice in FAQ-General

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#599]
The error usually happens when payer uses non-segwit wallet and merchant has Bech32 format. Two solutions, either a merchant can modify their derivation scheme to `P2SH` for better comparability or a customer should use a SegWit compatible wallet. I can't remember the exact error people since it defers from wallet to wallet, but most error contain `invalid address` that should be included in explanation so it appears as a keyword when someone searches in docs.

So one error is Segwit compatibility which is quite common, the other can be an underpaid invoice that mostly happens when payer pays from an exchange, where exchange deducts the fee from the total, which leads to an underpaid invoice on merchant' side. A solution is to pay the due (provided that invoice has not expired) or contact the merchant for a refund or the way to pay a due.

Don't remember any other situations for payer, @britttttk any other I'm missing?

- [ ] Add `I have a problem paying BTCPay Server invoice` to FAQ-General
- [ ] Outline different errors and scenarios that may happen mentioned above.
- [ ] Add `I have a problem paying BTCPay Server invoice` to FAQ-Readme
- [ ] If there's a reliable source listing SegWit compatible wallets, link to it

**Comment by TBCode523** [comment]
- For your second point about exchange fees BTCPay Server allows your invoice to be still be marked as paid even if it is not paid in full. This can be modified in the general settings of your store.
If I missed anything let me know!
![Capture](https://user-images.githubusercontent.com/37788210/85345835-9afa3c80-b4c1-11ea-88da-7b5810272151.PNG)

**Comment by britttttk** [comment]
@pavlenex I think that is everything for the issue "can't pay invoice at all". The issue @TBCode523 mentioned is "can't pay invoice in full. I think they are both good questions from the customer perspective. 

At some point we might want to make a kind of Payments.md page similar to Invoices.md page, where we can explain things from the user perspective. For now we can bring these into general, but just an idea.

**Comment by pavlenex** [comment]
What @TBCode523 mentioned is a solution that helps with underpaid invoice. I am unsure if we should mentioned that since this FAQ is targeted  at payer, not the receiver and it may become overwhelming, but if we can mention it briefly without too much details, then okay.

I outlined two problems:

1. Can't pay at all - SegWit compatibility mostly the answer
2. Can't complete the payment (underpaid, maybe even expired) - exchange taking the cut mostly the issue.

**Comment by britttttk** [comment]
Ah ok, I didn't see that you mentioned 2 in your OP. That should cover this imo.
