### ISSUE TITLE
Benefits? Clarification

### ISSUE THREAD

**Issue by maurocolella** [btcpayserver/btcpayserver-doc#6]
Dear BTCPay maintainers,

I have been tasked with setting up a standalone BTCPay server. I chose to do it under Linux, with .Net Core 2.0.2 and Postgres.

I am slightly confused as to the benefits of such an installation. It looks like my client wants to use the features listed in:
https://btcpay-server-testnet.azurewebsites.net/

In that case, I am slightly confused as to the setup procedure for Linux. Yes, Linux. I am following the steps given for "local development", and would like any clarification you could provide.

**Comment by NicolasDorier** [comment]
I am not sure what you mean by "benefit of the installation". Have you looked https://www.youtube.com/watch?v=a5ehSfzYkJo ? This is a video documenting the installation without posgres (not recommended), you can follow the same steps on linux.

**Comment by maurocolella** [comment]
Thank you, this helps clarify things.

What I mean is: I seem to understand I need to be running a full node, eq. Bitcoin Core, eq. a full Bitcoin node? 

I simply have to make sure the business team is notified of the requirements to self-host a pay server using Bitcoin (eq. potentially large amounts of storage data, computational power and bandwidth).

**Comment by NicolasDorier** [comment]
Yes this is correct, BTCPay requires to self host a bitcoin full node. (or having another business willing to offer to host it as "plateform as a service" for you)
Bitcoin core is working on BIP159, so maybe later we can use a bitcoin full node pruned to minimize storage requirements, but this is not yet done.

The most ressource intensive component is definitively Bitcoin Core.

**Comment by maurocolella** [comment]
Thank you very much.
