### ISSUE TITLE
Tweaking the Algolia search engine

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#628]
As discussed in #545 , we can brainstorm how to tweak the Algolia search engin in the docs.

As Dennisreimann pointed out, a low hanging fruit tweak could be to not have 25 results at each search. Confusing for new users, frustrating for experienced ones.

Pavlenex points out getting irrelevant results in the majority of cases when using the search. Fixing relevancy might be a not so low hanging fruit ?

On a UI note, Zaxounette points out that the search bar might not be advertised/visible enough.

Summarized:
- Tweak search to lessen number of results
- All the while increasing relevancy
- And advertising it's existence better

This is an open brainstorm discussion for code-based _and_ non code-based improvements.

See #630 for proposed code-based fixes.

**Comment by pavlenex** [comment]
For search, I think we have to dive deep into Algolia analytics to see what people search and if they find useful results (I'm unsure if Algolia provides this in-depth behavior).

Less irrelevant and more relevant result is better.

**Comment by dennisreimann** [comment]
Regarding "increasing relevancy": From what I see as the most practical approach would be to analyze the stats/gather feedback from users and then updating the headlines of the individual doc sections to fit the search terms. There might be other options via [tweaking the crawler settings](https://github.com/algolia/docsearch-configs/blob/master/configs/btcpayserver.json) and providing custom [ranking parameters](https://www.algolia.com/doc/api-reference/api-parameters/ranking/), but that seems less approachable than making the headlines fit.

**Comment by Zaxounette** [comment]
Pav's comment (here: https://github.com/btcpayserver/btcpayserver-doc/pull/545#issuecomment-661255823) made me think.

@dennisreimann , is it possible to add meta data to the titles ? 
As in have that meta-data be searchable and render search results based partly on that too ?

Could be part of the tweaking solution.

**Comment by dennisreimann** [comment]
We could add meta data via the pages [frontmatter](https://vuepress.vuejs.org/guide/frontmatter.html#predefined-variables) block. Then we'd have to instruct Algolia to index this as well. 

Nevertheless, that'd mean that we have to add the keywords for each page. And they are most likely already part of the content and headlines. So I'm not sure if this wouldn't just be a big overhead.

**Comment by dennisreimann** [comment]
I've added a [sitemap](https://docs.btcpayserver.org/sitemap.xml) (001b0f00acb4a45ec74660c7f8ff5523d8714ee8), which we can reference in Algolia as well as the Google Webmaster Tools. 

@pavlenex has already added it to the GWT and I've created algolia/docsearch-configs#2981, which adds it to our Algolia index config, as well as doing some more changes that will hopefully improve our index.

Let's wait for it to be merged and re-indexed. Then we can fiddle with the [Algolia config options on our end](https://www.algolia.com/doc/api-reference/api-parameters/).

**Comment by dennisreimann** [comment]
Now that the index and UI improvements have been shipped as well as our SEO updates, let's discuss this anew: Which parts could still be better and what are the terms we should monitor and improve?

According to the Webmaster Tools Search Console, the organic traffic comes mostly from generic terms, like

- wallet
- server setup
- api
- woocommerce
- lunanode
- shopify

Including this screenshot here for people that don't have access …

![sc](https://user-images.githubusercontent.com/886/101464343-ccb37280-393e-11eb-923b-c6dc1247a84b.png)

@pavlenex Do you see actionable next steps for this issue?

**Comment by Zaxounette** [comment]
What this list makes me think is that the organic traffic is composed mostly of people that know the name `btcpay`.
Could hitting other people that don't know the name be a way to improve ?

If it is, we're missing the real generic terms like wallet, shop, merchant with `Bitcoin` or `crypto` associated for example.
In any case, that's for general SEO and inbound traffic.

Wasn't the issue initially about Algolia and the internal traffic ?

**Comment by dennisreimann** [comment]
> Wasn't the issue initially about Algolia and the internal traffic ?

Correct – so here we go with the Algolia searches from the last three months …

![algolia](https://user-images.githubusercontent.com/886/101516424-c42f5c00-397f-11eb-8ab1-9c23e73604a9.png)

**Comment by Zaxounette** [comment]
I'll just re-write what was said in the call last week:

> After @pavlenex pointed out he was surprised to not see `sentences` being inputted in the search, I opinionated that we have to consider the possibility that the inputs are mainly the few regular contributors that directly input terms they know will yield the result they are looking for.

If that's truly the case, I don't see what conclusions we can gather of this data.

----
On the other side, if that's **not** the case, I'm also surprise that no one looked up terms like `store`, `merchant` or other terms relating to the primary legacy goal and use-case of BTCPay.
Maybe we can expand the terms relating to different known use-cases ?

**Comment by pavlenex** [comment]
I think this is solved now, not perfect but way better than before.
