### ISSUE TITLE
Add pull payments to UseCase.md

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#638]
The [PullPayments.md](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/PullPayments.md#user-interface) ui section is using the `subscription` use case maybe we want to use that?

**Comment by pavlenex** [comment]
Not yet, it's really not ready for that particular use-case without automated payouts.

**Comment by britttttk** [comment]
If you think there is no use case for pull payments yet, then feel free to close the issue

**Comment by pavlenex** [comment]
I'll leave it open. There is use case but I understood you wanted to emphasize "subscriptions" which really aren't possible atm.

**Comment by britttttk** [comment]
These are the use cases listed in the PP doc:

- A subscription service (where the subscriber allows the service to pull money every x amount of time)
- Refunds (where the merchant allows the customer to pull the refund money to his wallet when it seems fit)
- Time-based billing for freelancers (where the person hiring allows the freelance to pull money to his wallet as time get reported)
- Patronage (where the patron allows the recipient to pull money every month to continue supporting their work)
- Automatic selling (where a customer of an exchange would allow an exchange to pull money from their wallet to automatically sell every month)
- Balance withdraw system (where a high-volume service allows users to request withdrawals from their balance, the service can then easily batch all the payouts to many users, at fixed intervals)

Seems subscription was nack, I personally nack refunds because I think it's more of a feature. So I'm thinking to use `Time-based billing for freelancers, there is already a [freelance section in Use Case](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/UseCase.md#freelancers--bill-pay). I think it fits the best there.
