### ISSUE TITLE
Add infos on pj-exposed label

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#666]
The following PR introduced automatic labels:
https://github.com/btcpayserver/btcpayserver/pull/1499

One label that is used is the `pj-exposed` and the information that it should provide seems unclear and introduces some questions (See [Chat](https://chat.btcpayserver.org/btcpayserver/pl/9wdcu3brxfy65c9w9hyw9xm6cw)).

That particular label could be explained specifically, but an idea could be to add every single automatic label to the docs, and expand on the meaning of the individual labels, as to clear things for the user.

Maybe afterwards, add an interrogation marker in the wallet page in BTCPayServer directing to that docs page ?

**Comment by Zaxounette** [comment]
New comment related to this issue: https://github.com/btcpayserver/btcpayserver-doc/pull/670#issuecomment-674354579

**Comment by pavlenex** [comment]
@britttttk @Zaxounette is this closed by #670? It seems Brit's PR resolves is on docs end.
Would you like to add a tooltip in BTCPay's UI or?

**Comment by Zaxounette** [comment]
#670 was only part of the issue.
It resolves the issue of not having a table with the transaction labels in the docs. Now we do ! 

But there's still the `pj-exposed` label that is unclear.
Still need @Kukks 's input on this to clarify what information he wanted to send a user when labeling `pj-exposed`.

**Comment by britttttk** [comment]
@pavlenex yes I will try to describe the labels a bit better from looking at the bip, etc. before we add the tooltip as docs are just matching the ui copy at the moment.

**Comment by Kukks** [comment]
Hey, sorry overlooked this discussion.

`pj-exposed` is marked on utxos/transactions that were exposed to customers when they were attempting a payjoin transaction. 

* I have 1utxo in my store wallet 
* I enable payjoin 
* a customer generates an invoice to pay and has a payjoin compatible wallet
* customer initiates a payjoin transaction.
* the utxo in the store is used to create the payjoin and is exposed to the customer.
* The customer knows that that utxo is under ownership of the store. 
* It is irrelevant is the payjoin is completed or abandoned, the utxo was exposed to at least one external user, I would discourage usage of that utxo to anything sensitive (or consolidating it with other utxos that were not exposed) if you are motivated to protect your privacy.
* The coin selection wallet feature is really handy to deal with these exposed coins

**Comment by Zaxounette** [comment]
Nice, thanks a lot @Kukks ! :)

**Comment by britttttk** [comment]
@Zaxounette from reading kukks' descriptions, I am now thinking that the UI info is actually quite clear and it's more conceptually challenging that uninformative. 

What do you think about adding a link in this table, to the Payjoin doc AND adding a tooltip to the Payjoin doc? (I don't think it exists in the ui yet but I need to check).

**Comment by Zaxounette** [comment]
> The UI info is actually quite clear and it's more conceptually challenging that uninformative.

I'm ready to accept the fact it's not uninformative but just a novel challenging concept. But then as a novel concept, it might need explicitation for the newbies like myself. Otherwise we might get avoidable support time.

> What do you think about adding a link in this table, to the Payjoin doc AND adding a tooltip to the Payjoin doc? (I don't think it exists in the ui yet but I need to check).

A link in the transaction page to the Payjoin docs would fit, yes.

What do you mean by "a tooltip" ?

**Comment by britttttk** [comment]
@Zaxounette the (?) icon in the ui

**Comment by Zaxounette** [comment]
> @Zaxounette the (?) icon in the ui

Oh yeah, sure, go for it !

**Comment by britttttk** [comment]
>I don't think it exists in the ui yet but I need to check

Update: Payjoin tooltip exists where you enable it in the store.

![image](https://user-images.githubusercontent.com/39231115/97820714-ad089a80-1c6c-11eb-8df3-f8bda543514d.png)
