### ISSUE TITLE
Document Multisig setup

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#669]
As discussed [here](https://chat.btcpayserver.org/btcpayserver/pl/bu1a57ih3pyrbep9nwskqq66kh), we haven't documented Multisig yet.

- Document using internal wallet as part of a multisig setup
- Document internal wallet as initiator of a multisig setup (if even possible)

As pointed out by Pavlenex, this should wait until new UX/UI is finished/refurbished.

**Comment by britttttk** [comment]
New import xpub page:

![image](https://user-images.githubusercontent.com/39231115/107612963-9e833500-6c04-11eb-98ea-40caa97d388a.png)

**Comment by pavlenex** [comment]
Outdated, closing until we have a proper multi-sig UI.
