### ISSUE TITLE
Testers Documentation - Local Dev Setup

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#676]
There are [videos for setting up local dev environment](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/LocalDev.md#videos) but there is not documentation for it other than the docker repo [how to get started reference](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/README.md).

A new doc to include:
- Photos setup (general)
- Easiest setup (hot wallet)
- Test payment example (make payment, see confirmed invoice)
- common gotchas (add blocks to confirm, etc.)

**Comment by britttttk** [comment]
relates to #174

**Comment by esky33kubernetes** [comment]
ie. some extra links for new dev`s  https://docs.docker.com/docker-hub/ 
etc

**Comment by pavlenex** [comment]
@britttttk what's left on this one after #696 ?

**Comment by britttttk** [comment]
@pavlenex closing this for now, I think `new doc` is complete, we can make updates as they are needed.
