### ISSUE TITLE
Improve BTCPay Deployment Frequently Asked Questions

### ISSUE THREAD

**Issue by seth586** [btcpayserver/btcpayserver-doc#677]
I could not find the information I was looking for on the "BTCPay Deployment Frequently Asked Questions" page (`/FAQ/FAQ-Deployment/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

I already run a well connected lnd node with sufficient inbound liquidity, how can I deploy BTCPay to use it?

**Comment by britttttk** [comment]
@seth586 This process is not documented. It is possible to do, but the docs do not include all information for custom builds of BTCPay including this scenario.

In my opinion, until this process is added to documentation by a contributor, we should at least address this question in the Lightning FAQ.

**Comment by britttttk** [comment]
@seth586 please see the attached pull request for updated information on this issue.
