### ISSUE TITLE
Improve Deploying BTCPay - LunaNode Web-Wizard

### ISSUE THREAD

**Issue by BrotherPeng** [btcpayserver/btcpayserver-doc#685]
I could not find the information I was looking for on the "Deploying BTCPay - LunaNode Web-Wizard" page (`/LunaNodeWebDeployment/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

![image](https://user-images.githubusercontent.com/7921230/91601971-1a622b80-e99d-11ea-8ff0-73e14693f2c3.png)

**Comment by pavlenex** [comment]
Contact lunanode, not really something specific for their deployment method, there's plenty of reasons why SSL error may happen. Probably their lets' encrypt failed.
