### ISSUE TITLE
Show social icons on mobile below the fold

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#692]
A minor nit I noticed while browsing docs is that our mobile menu shows social icons + website and chat links above the fold which isn't optimal UX imo. I suggest we show them below the navigation links and perhaps we can show social icons in a single row?

Optionally maybe we can show them in the header, but I'm unsure how would that look.

![Screenshot 2020-09-01 at 19 24 39](https://user-images.githubusercontent.com/36959754/91880224-e3379700-ec88-11ea-9a47-5ba041b23fdb.png)

**Comment by l33d4n** [comment]
Good idea. I made example of social icons in a single row. We'll have to replace the icons for the chat and website but the structure looks good, right?

<hr>

![image](https://user-images.githubusercontent.com/8020386/92988847-be9db380-f501-11ea-9caa-b9f1ad9bd4c2.png)

**Comment by pavlenex** [comment]
Hey @l33d4n Sure, LGTM 🚀

**Comment by l33d4n** [comment]
Great! I'll start working on this issue. Do you have any idea what the source of the existing icons (Twitter and Github)?

**Comment by pavlenex** [comment]
I am unsure, @vswee @dennisreimann do you guys know what's the source of the Twitter and Github icons we have?

**Comment by dennisreimann** [comment]
Right now they are inlined in the CSS. You can grab them from there or just use SVG that work here. Keep the the switching in mind, the icons need to be displayed in light and dark mode.
