### ISSUE TITLE
Add how to be notified for payments to FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#702]
- Internal Notification Alerts (included by default)
- External Notifications (for all below explain why it's used & give example of what is sent)
   - SMTP in btcpay server settings
   - SMTP in btcpay store settings
   - Transmuter Email Receipts (link to [here](https://docs.btcpayserver.org/Transmuter/EmailReceiptsPreset/#transmuter-email-receipts-setup)) 

Also TODO:
- Tooltip in both SMTP pages linking to this document
- link this existing [SMTP faq info](https://docs.btcpayserver.org/FAQ/FAQ-ServerSettings/#how-to-configure-smtp-settings-in-btcpay)

Additional:
- look for forgot password email info and see if it can be combined here in to a notifications & communications document.
- look for verification email info and see if it can be combined here in to a notifications & communications document.

**Comment by pr1s10n3r0** [comment]
Hi there!, is there a way to receive an external notification from BTCPay server when receive a transaction?

Need help because I'm a noobie.

It could be an email that alerts me a new transaction occurs.

**Comment by britttttk** [comment]
@pr1s10n3r0 you can do it with transmuter with the [email receipts preset](https://github.com/btcpayserver/btcTransmuter/blob/master/docs/EmailReceiptsPreset.md).

**Comment by brainharrington** [comment]
Definitely up vote for getting clarity on how to get notified by email when an invoice is paid. I got SMTP working inside BTC Pay today for the first time and am halfway through set up on Transmuter but not done and randomly email notifications of paid invoices turned on for me.

**Comment by pr1s10n3r0** [comment]
I just can't get SMTP working inside BTC Pay server. Always get the same message "504 Gateway Time-out".

**Comment by britttttk** [comment]
> I just can't get SMTP working inside BTC Pay server. Always get the same message "504 Gateway Time-out". 

Which email service are you trying to use?

**Comment by pr1s10n3r0** [comment]
I tried with several Gmail accounts, then I tried with an account provided by site ground (hosting services).

But I'm open to use anyone who works just fine with BTC Pay server. Can you recommend me one?

**Comment by britttttk** [comment]
@pr1s10n3r0 I just updated the original post with a little more information and some links that may help you. Can you take a look at those links in my original comment. 

Can you describe where you see the "504 Gateway Time-out" error and what you are doing when you see it (setting up server or store email?) Also can you mention your [method for deploying btcpay](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Deployment.md#what-are-my-options)? I just tested with Gmail it works fine for me. If you have accounts to try there, you will need to enable the "Less Secure Apps feature" as mentioned in the FAQ link.

**Comment by pr1s10n3r0** [comment]
I have read the relevant documentation (thanks anyway!) 
I configured gmail to use less secure applications.
I deployed BTC Pay with Luna Node. 
I saw "504 Gateway Time-out" every time I tried to test SMTP configuration (test email button). 

I'm lost. :(

**Comment by britttttk** [comment]
@pr1s10n3r0 I have not seen the 504 Gateway time-out error for sending the test email before. I know that someone was able to get it working with sendgrid today, if you want try that one instead. If you would like to also open an issue in the btcpayserver repo I think that 504 seems like a bug https://github.com/btcpayserver/btcpayserver/issues

**Comment by pr1s10n3r0** [comment]
I'm really thankful for your interest. At least you tried!

Thanks!

**Comment by pr1s10n3r0** [comment]
BTW... This is a screenshot. 
![20201013_185258](https://user-images.githubusercontent.com/72285894/95924392-7f26e900-0d85-11eb-8018-c5562e2463a5.jpg)

**Comment by pr1s10n3r0** [comment]
Hi britttttk

I finally understand what happened to me. 

I deployed BTCPAY with Luna Node. The virtual machine is in Canada. My Gmail account not. So Gmail blocked any attempt from BTCPay server to send emails.

Solution was easy: I create a "Canada" Gmail account and works just fine!

**Comment by pr1s10n3r0** [comment]
britttttk, can you help me with another Q?

I want to receive email notification from PoS BTCPay app when a transaction occurs. Is that possible?

**Comment by brainharrington** [comment]
> Hi britttttk
> 
> I finally understand what happened to me.
> 
> I deployed BTCPAY with Luna Node. The virtual machine is in Canada. My Gmail account not. So Gmail blocked any attempt from BTCPay server to send emails.
> 
> Solution was easy: I create a "Canada" Gmail account and works just fine!

Oh that's smart, that may be what's tripping me up too, what's the process to make a canada gmail?

**Comment by Zaxounette** [comment]
> Oh that's smart, that may be what's tripping me up too, what's the process to make a canada gmail?

I looked it up a bit, and there aren't specific country GMAIL accounts, but rather they base it on internal settings, like language and such.
Creating a new Gmail account with a VPN pointing in canada and putting internal settings relating to canada could work ?

**Comment by pr1s10n3r0** [comment]
That's exactly what I do: VPN pointing in Canada and just create a new account.

As easy as it gets
