### ISSUE TITLE
Add links to GreenField API Development Documentation

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#711]
As per https://github.com/btcpayserver/btcpayserver/pull/1627#issuecomment-690060969, we should link to the GreenField API Development Documentation somewhere in the docs.

The #1627 PR has been merged, but since it's in the BTCPayServer repo, I expect it to be available only on next release. Please confirm.

If that is so, we'll need to wait until then.

Links to that document can be included in :
* WriteDocs
* DevCode
* LocalDev

It can also be linked in other docs as needed. 
Open for discussions.

**Comment by britttttk** [comment]
Related to #174
