### ISSUE TITLE
Icons in Community.md open an image box instead of directly going with a link

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#721]
When you click on the community social icon in the Community.md it goes to link directly but then you're greeted with an experience like this.

![Screenshot 2020-09-18 at 16 57 05](https://user-images.githubusercontent.com/36959754/93612717-2192bd00-f9d0-11ea-804e-7ddc0f13011d.png)

I'm not sure if there's something we can do to fix this without affecting other pages where image box is useful, otherwise we can simply use text links.

**Comment by thehapax** [comment]
you can do fix this with HTML would that be acceptable?

**Comment by pavlenex** [comment]
@thehapax whatever fixes the issue is fine 😄

**Comment by thehapax** [comment]
Looked into it a bit deeper. It looks like a simple html/css override would not do the trick as all the images are currently using this medium-zoom package: https://github.com/francoischalifour/medium-zoom#usage

There might be an override somewhere but I'd have to look into it a bit more without affecting other images on site. Thoughts?

**Comment by dennisreimann** [comment]
I'll take a look.

**Comment by dennisreimann** [comment]
This was related to an old version of the medium zoom plugin: Upgraded it, so that it does not zoom images contained in links.
