### ISSUE TITLE
Add update alert option to docs

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#726]
Possibly add this to [How to update FAQ](https://docs.btcpayserver.org/FAQ/FAQ-ServerSettings/#how-to-update-btcpay-server) or add new FAQ how to be notified for updates.

![image](https://user-images.githubusercontent.com/39231115/93847143-57030900-fc63-11ea-850e-edfa21d712d2.png)

**Comment by pavlenex** [comment]
I think it's not just the box that needs to be enabled, @rockstardev do we need to set up an env variable for this to work or should it work if the checkbox is selected out of the box?

**Comment by britttttk** [comment]
I think it should work OOTB and it checks once per day, afaik 24 hours after the time it's enabled.
