### ISSUE TITLE
Improve Hardware Deployment

### ISSUE THREAD

**Issue by martijnw** [btcpayserver/btcpayserver-doc#736]
I could not find the information I was looking for on the "Hardware Deployment" page (`/HardwareDeployment/`).

The installation is rather inflexible port wise. Many businesses run CCTV cams, VPN access, etc. so the HTTP port should be able to be specified in an environment variable to say 8080 or 8888 as this complicates things a lot. It would really make deployment easier in more complex network environments.

**Comment by Zaxounette** [comment]
Hi @martijnw !

Thank you for your feedback.

Environnement variables for the docker component can be found here: https://docs.btcpayserver.org/Docker/#environment-variables

Reverse proxy port changes are listed in the variables offered.
Is this the information you where looking for ?

**Comment by martijnw** [comment]
Thank you! I will give it a try and bind the server to 8080 externally instead of 80 but from the hardware deployment page, it said this is not possible and will fail on letsencrypt. Thanks anyway for responding. Should be able to make it work eventually.
