### ISSUE TITLE
Documentation about BTCPay API security

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#740]
Explain the security measures:
- Legacy API auth
- Greenfield auth
- Give api example to explain and improve dev doc

**Comment by britttttk** [comment]
ping @Eskyee is this what you think might be good?

**Comment by Eskyee** [comment]
Yes some extras will be fine.. and just a basic understanding is good enough .. if people are more interested!! They can research on their own time.. thanks bk
