### ISSUE TITLE
Outdated folder reference on Documentation

### ISSUE THREAD

**Issue by VanJaime5** [btcpayserver/btcpayserver-doc#756]
I found the documentation points to a folder that is not the right one.

Specifically this site:
https://docs.btcpayserver.org/FAQ/FAQ-Deployment/#how-to-access-the-onion-address-without-clearnet

![image](https://user-images.githubusercontent.com/61366014/96904962-d273f800-1465-11eb-897c-83d0bacdc46f.png)

That folder change  = /BTC-P2P/

**Comment by dennisreimann** [comment]
The `BTC-P2P` is the bitcoind onion address – the `BTCPayServer` one contains the onion address for the weeb interface of your BTCPay Server instance. The information presented is correct. /cc @Zaxounette
