### ISSUE TITLE
some extra info about BTCPay Server Branches, would be nice  

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver-doc#758]
ie some more quick newbie overview info about building updating Branches
btcpay server GitHub..  sorry if my questions are not clear..  I can explain better with a online session if needed..
 
Master Branch ..  ie purpose 
Latest Branch ..  ie purpose

info on updating docker hub via tags.. ?? haven't seen any info  in docs, sorry if I missed it!!

would be nice to see a little more information on branches,  and not just local development.. branches, they are all nicely  documented.
 
but like upstream branches if someone is maintaining a folk
ie 
git remote -v
git fetch upstream
git merge upstream/master 

https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches

pushing branch or tag to hub.docker!!
as I find sometimes I'm can be confused by this sometimes.. master branch  & latest branch, or via tag process, 
and would love to see this more about this in detail, as I have self learnt this with hub.docker docker , its nice too know which is the correct method. and gain more confidence.  since we are no longer using the stable branch..  a clear overview in the mind  helps to see thru btcpay faster..
thanks
@pavlenex @britttttk 

any feedback will be helpful!!

https://www.youtube.com/watch?v=k6pxsaXAhbI

https://www.youtube.com/watch?v=Gg4bLk8cGNo

making it easy for noobs to maintain their own repo!! ;) is my goal

**Comment by britttttk** [comment]
@Eskyee if there is a specific **git action** that you think could be added [here](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Contribute/ContributeDev/ContributeDevCode.md) can you let me know?

For Docker info can you check [this guide](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Contribute/ContributeDev/ContributeDevTest.md#using-docker-images-for-mainnet-testing) and let me know if you think it's missing info. 

It doesn't explicitly stage fork in the doc above but I personally don't think it's necessary to teach people how to make and maintain forks of the project. The purpose of fork is they want to go their own way.

**Comment by Eskyee** [comment]
hey bk 

yes theirs no problem with the git action commands.. from what I see

just identifying the branches we have in use.. 

Master Branch .. ie purpose..  build n push & maintain
Latest Branch .. ie purpose.. ??  this what btcpay uses as a update branch ..  ie tag
just some info about branches will do fine..

"I personally don't think it's necessary to teach people how to make and maintain forks of the project. The purpose of fork is they want to go their own way."

yes I agree 100% with you here.

also this looks great!!  "Docker info can you check this guide and let me know if you think it's missing info."

I can't see nothing missing .. great job!!  nice overview here.. I love the content!!

https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Contribute/ContributeDev/ContributeDevTest.md#using-docker-images-for-mainnet-testing

**Comment by Eskyee** [comment]
loved this section bk  ..  this  answered  my  other question I had with rockstar the other day..

Step 5:

Inside the root directory of your btcpay-branch there are Dockerfiles prefixed by the following amd64, arm32v7, arm64v8. We need to build and push a custom image using the Dockerfile for the OS being used. Replace <yourRepo> and tag 1.0.0.1 in the following commands:

#build image
docker build -t <yourRepo>/btcpayserver --file ./amd64.Dockerfile .

#push image
docker push <yourRepo>/btcpayserver:1.0.0.1

;)

**Comment by britttttk** [comment]
>Master Branch .. ie purpose.. build n push & maintain
>Latest Branch .. ie purpose.. ?? this what btcpay uses as a update branch .. ie tag

This makes sense @Eskyee I think we could add this. Master vs Latest and how it works with releases. I think adding it to this Contribute-Testing doc could be good. Example: If you find a bug in Master, it may not be released yet... etc.

**Comment by Eskyee** [comment]
If you find a bug in Master, it may not be released yet... etc.
Yes as this is what I brought me to the question of branches bk, 

thanks
I will close this issue now!

**Comment by britttttk** [comment]
@Eskyee I think it's a good idea to add those ideas (release vs. master), reopening this for a reminder to mention it in contribute docs about the release process in BTCPay.

**Comment by Eskyee** [comment]
https://nvie.com/posts/a-successful-git-branching-model/

this is a great explanation and overview of production ready code and a GitHub workflow model .  @britttttk
