### ISSUE TITLE
Add warning for manual deployment troubleshooting

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#769]
Lately there have been many manual deployment and custom configuration deployment questions in the mattermost chat. While this is fine to inquire if anyone knows issue solutions... I do agree we should ([as mentioned in the chat](https://chat.btcpayserver.org/btcpayserver/pl/sfyshbmwftfxidqfrheh4uskwy)):

_emphasize more that manual deployments are heavily discouraged if you can't solve deployment and maintenance issues on your own_

Add `yellow warning box` possibly to troubleshooting.md, deployment.md, or other.

**Comment by Zaxounette** [comment]
Just to jump in on this:

Warning and "disclaimers" are already stated in `ManualDeployment.md` (disclaimer) `ManualDeploymentExtended.md` (big red warning).

Additional suggestion **on top** of adding warnings: 
Re-order the menu items and create `Production deployments` and `Educational/Testing Deployments` or something similar, as to add a difference directly in the menu items.

**Comment by Zaxounette** [comment]
#771 Adresses your initial issue Britttt.
I didn't work on my suggestion, since I don't know if there's consensus on it or not.

**Comment by britttttk** [comment]
>Re-order the menu items and create Production deployments and Educational/Testing Deployments or something similar, as to add a difference directly in the menu items.

I like the idea of it, but I think that it would be hard to do because Production is a bit relative. I am partial to using the word Custom over non-production. Do you like something like this? 

**Deployment**
- Choosing a Deployment Method
**Simple** <-- ??
- Third-party Hosting
**Recommended**
- Docker
   - web
   - azure
   - google
   - hw
   - raspi
- Docker plugins
**Custom**
- Manual
**Automated**
- Configurator

**Comment by Zaxounette** [comment]
We maybe could use the wording "`recommended for production`" and "`recommended for development and testing`".
That could indicate that it's recommended but not mandatory, and people can use whatever, but will know it's only optimized for a specific use-case ?
The wording might be too long for the menu now that I think of it. On the other hand, we already have "choosing a deployment method" string that is fairly long too, so It could fit in.

In any case, something of the sorts might be ok ? :

* Choosing a Deployment Method
* Recommended for production
  * Simple/Easy/Beginners
    * Third-party-hosting
    * Lunanode 1-clic
  * Intermediate
      * Docker
        * web
        * azure
        * google
        * hw
        * raspi
        * Docker plugins
      * Configurator
 * Recommended for Development and Testing
    * Advanced users
        * Manual
        * Extended manual

**Comment by dennisreimann** [comment]
I'm not convinced that using the navigation hierarchy is a good idea to convey this. It might even add more confusion as setups like MyNode and Raspiblitz are using the Manual Deployment for their production use case ;)

We should collect all of the information regarding recommendations on the "Choosing a deployment method" and refer to that from initial use case warnings/mentions, like on the Manual Deployment pages. I don't think there's much more we can and should do here.

**Comment by Zaxounette** [comment]
> I'm not convinced that using the navigation hierarchy is a good idea to convey this. [...]

The effect I was aiming for in tweaking the nav items was an instant visual cue for the proper deployment depending on the user's skill and the use-case (production or dev/testing).

Since you propose to use deployment.md, I'll find a way to make such cues visible in it, as well as freshen that doc, since I think it's one of the oldest and IMO it could use an update, at least on the information delivery side.

I'll PR a proposal tomorrow evening.
