### ISSUE TITLE
Document adding Webhooks

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#774]
Document the new feature: create webhooks with BTCPay which is being added to the next major release.

![image](https://user-images.githubusercontent.com/39231115/99898786-64d40b00-2c61-11eb-9d2a-70d1bd9e71b1.png)

Stores > Settings > Webhooks > Create a new webhook

![image](https://user-images.githubusercontent.com/39231115/99898809-9d73e480-2c61-11eb-8e50-49860d76604e.png)

**Comment by pavlenex** [comment]
#1140
