### ISSUE TITLE
Deployment.md - Refresh & update

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#789]
Relates to #769 and https://github.com/btcpayserver/btcpayserver-doc/issues/769#issuecomment-736082738

* Update `deployment.md` file
* While refreshing the way to choose a deployment based in `use-case` and/or `"skill"` of the user.

**Comment by Zaxounette** [comment]
1°) Okay, so I've been regrouping all the informations inside the different tables into a unique table for clarity.
No information loss, I kept all the links, table inputs and such.

I just added a link to the directory hosts page.

Thoughts ?

![Code_DLHG9M2y99](https://user-images.githubusercontent.com/51208677/102010551-ff92a780-3d3e-11eb-98e5-d270ed494262.png)


2°) I also really really want to delete the first infographic on that page. It's redundant and more difficult to read than the tables right under it.
Also thoughts ?

**Comment by pavlenex** [comment]
Lunannode is a VPS.

**Comment by dennisreimann** [comment]
Awesome, this is easy to diggest and offers a nice way to compare the different options! Way better than what we have currently and I agree that the infographic isn't necessary anymore with these changes.

**Comment by Zaxounette** [comment]
Okay, I'll PR this and see if there's something missing or that could be explicited.
