### ISSUE TITLE
Improve BTCPay Server Wallet FAQ

### ISSUE THREAD

**Issue by jsharookh** [btcpayserver/btcpayserver-doc#796]
I could not find the information I was looking for on the "BTCPay Server Wallet FAQ" page (`/FAQ/FAQ-Wallet/`).

Why there is a rate fee showing in send option, If it is my own server to whome i am paying the rate fee while sending btc from wallet ?

**Comment by Kukks** [comment]
There is a fee to create a Bitcoin transaction, that's just how Bitcoin works. Our documentation assumes you have basic knowledge about Bitcoin.  
https://en.bitcoin.it/wiki/Miner_fees
