### ISSUE TITLE
What is BTCPay

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#81]
Create a "what is BTCPay video" animated. 
Video can be embedded at the front page.
Think of a concise storyline.
Ideas welcome.

**Comment by NicolasDorier** [comment]
I try to get my wife coming on the slack to talk about it but she is shy it seems...

**Comment by bitcoinshirt** [comment]
Who knows the stories you told her about our Slack. We don't bite.
I'd be happy to help her with the storyline. She can ping me anytime.

**Comment by pavlenex** [comment]
This one is now finished.

We have an intro video coming, plus btcpay simply explained and how btcpay works videos available on YouTube channel.
