### ISSUE TITLE
Some docs aren't rendering URLs

### ISSUE THREAD

**Issue by dcentrica** [btcpayserver/btcpayserver-doc#813]
I've found at least two instances where the docs aren't rendering a URL that should be there:

https://docs.btcpayserver.org/Configurator/

"deploy new BTCPay instances. When enabled, Configurator is located at"...

https://docs.btcpayserver.org/FAQ/FAQ-Deployment/#cause-4-getting-500-nginx-error-on-a-local-server-https-and-for-http-btcpay-is-expecting-you-to-access-this-website-from

"Cause 4: Getting 500 nginx error on a local server https and for http BTCPay is expecting you to access this website from"...

**Comment by britttttk** [comment]
@dcentrica Thanks for opening the issue to update these. :) I have opened a PR to fix the Configurator link. However, the other link you have mentioned, Cause 4 is not meant to contain a link. That statement is referring to the error that is shown to the user.

I agree this section can be improved to make this more clear.

**Comment by Zaxounette** [comment]
I can confirm, the `Cause 4` doesn't include a link and isn't intended to.

As for the configurator issue, it shouldn't be a link either, but something of the sorts of `yourbtcpaydomain.com/configurator`.
