### ISSUE TITLE
Link to Community in documentation is broken

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver-doc#821]
Source: https://docs.btcpayserver.org/Contribute/ContributeMisc/#community

Link is broken on `community` in this paragraph.

> Another great way is to join the community and help others

**Comment by britttttk** [comment]
It works for me :/ @Eskyee can you try it.

**Comment by Eskyee** [comment]
yes the link works for me @britttttk     https://docs.btcpayserver.org/Community/

**Comment by Eskyee** [comment]
<img width="1440" alt="Screenshot 2021-01-17 at 19 28 30" src="https://user-images.githubusercontent.com/30862925/104853672-3b023200-58fa-11eb-959d-f70453b89419.png">

**Comment by Zaxounette** [comment]
Works for me too.

![y43RvHX5Sd](https://user-images.githubusercontent.com/51208677/104853676-a4863e80-5902-11eb-9d9d-e6ba90607d74.gif)

**Comment by pavlenex** [comment]
404 for me.

**Comment by pavlenex** [comment]
I think this is a redirect script that gets slow somehow.  Or something was blocking it https://youtu.be/dm9M-MjuA7k?t=378

**Comment by Zaxounette** [comment]
Well yesterday, Brittttt's PR modifying that exact doc was merged and I assume pushed to GH-pages also.
Could it have been just tough luck on the timing ?

**Comment by pavlenex** [comment]
I experienced the same today with a different link, (don't remember which one was a navigational link) so could it be that redirected links script is slower @dennisreimann ?

**Comment by dennisreimann** [comment]
> could it be that redirected links script is slower

What do you mean with "redirected links"?
It works for me on navigating via the link as well as initial page load …

**Comment by rockstardev** [comment]
The way to reproduce this was to CTRL+Click - opening page in new tab (like in the linked video).

It does work for me now, though. So it could be some script as @pavlenex is mentioning.

**Comment by Zaxounette** [comment]
The link is still functional and no additional reports for the same issue have been made for 17 days.

Since it was a temporary glitch, I'll close this.

Feel free to re-open if needed Uncle.
