### ISSUE TITLE
Add Import from file error to Wallet FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#826]
Error: "Wallet file was not in the correct format"

Usually when wallet is password encrypted in Electrum. Add this to Electrum doc and/or wallet FAQ.

**Comment by britttttk** [comment]
For reference, this note is now added to the import screen:

![image](https://user-images.githubusercontent.com/39231115/107608966-bfdf2380-6bfa-11eb-9ff9-c80c64cded7e.png)

**Comment by pavlenex** [comment]
@britttttk considering it' s quite obvious in the UI, do you still want to document it or should we close this one? Don't have a preference personally just curious if it's better to document it or not.

**Comment by britttttk** [comment]
@pavlenex I think most users are trying to backup something they created a long time ago and do not remember. I think we should close the issue and reopen it if it comes up in the chat again.
