### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yoki332** [btcpayserver/btcpayserver-doc#835]
I sent money twice to the same account by mistake, the money was sent, but did not reach where it was sent, since the transaction is old, how can I cancel the second transfer?

**Comment by Zaxounette** [comment]
Hi @yoki332 !

Please don't abuse the issues for support.

The main support channel can be found in the BTCPay Server [chat](https://chat.btcpayserver.org/btcpayserver/channels/support).

Closing this.
