### ISSUE TITLE
Wallet Redesign Docs Update

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#837]
Find and replace old wallet docs and images :) [Wallet redesign PR](https://github.com/btcpayserver/btcpayserver/pull/2164)

Existing Wallet
- [x] Hardware wallet
- [x] Import wallet file
- [x] Manually input xpub
- [x] Scan QR code
- [x] Manually input seed

New Wallet
- [x] Hot wallet
- [x] Watch-only wallet

**Comment by pavlenex** [comment]
Now that the wallet setup is merged, this should be a priority for documentation. Note that there may be minor UI changes, so taking screenshots may not be good at this stage, as some things may change soon, but the structure outlined by @britttttk is the same.

[#2277 ](https://github.com/btcpayserver/btcpayserver/discussions/2277)
[#2276](https://github.com/btcpayserver/btcpayserver/discussions/2276)

**Comment by pavlenex** [comment]
We have a design meeting today where we'll hopefully wrap things up in terms of  the UI so we'll have a preview for documentation crew early next-week for sure.

**Comment by britttttk** [comment]
Omitting the following wallet setup page **images** from docs:

- Let's get started (connect existing or new wallet)
- Choose your import method (hardware, xpub, qrcode, etc.)
- Choose your wallet option (hot-wallet, watch only)

To keep docs more flexible and require less updates these pages wont have images in wallet docs, just referenced in steps like in the PR linked above.

**Comment by pavlenex** [comment]
Some feedback from my end regarding the restructuring (posted on Mattermost, posting here for the reference)
![Screenshot from 2021-03-11 10-50-03](https://user-images.githubusercontent.com/36959754/110768484-8e886080-8257-11eb-80e9-99796080e166.png)

**Comment by dennisreimann** [comment]
I think we should strive for a single/combined page. We should put the important information directly on the views in the app, so that people don't even have to consult the docs for the immediate setup info. (that's also the beauty of focusing on one setup/import method per page)

**Comment by Zaxounette** [comment]
IMO the nav bar is already 20km long. Not including the dropdowns.

Adding a new page means adding it to the nav bar, either as a standalone or a dropdown. We should add new pages on top of the existing ones as a last resort.

**Comment by pavlenex** [comment]
Do we have ETA on this? @britttttk @Zaxounette

**Comment by britttttk** [comment]
We might want to create a follow up clean up doc for old wallets content. The linked PR #877 just matches the ui to the docs in the wallet area but it seems like there are old docs/images related to wallets in the repo.
