### ISSUE TITLE
Improve Altcoins Frequently Asked Questions

### ISSUE THREAD

**Issue by bastianignaciojg** [btcpayserver/btcpayserver-doc#845]
I could not find the information I was looking for on the "Altcoins Frequently Asked Questions" page (`/FAQ/FAQ-Altcoin/`).

BTCPay Does support ETH payment?

I've already implemented BTCpay on my app. but I need accept ETH transaction for give mine token for customer.

Thanks

**Comment by Zaxounette** [comment]
Hi @bastianignaciojg !

An ETH (and USDT20) support has been merged a while ago.
See technical details [here ](https://github.com/btcpayserver/btcpayserver/pull/1730)
But it seems that it's not the most easy integration if you have no technical skills.
