### ISSUE TITLE
Add Docker Tooling to BTCPay Docs

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver-doc#85]
Docker repo has amazing documentation.

I think we need somehow to clone that repo into doc repo and then add that to GitBook section > Development.

**Comment by britttttk** [comment]
I think setting up a development doc could be good. Are you thinking just bring the information from [btcpayserver-docker README](https://github.com/btcpayserver/btcpayserver-docker/blob/master/README.md) into it?

**Comment by britttttk** [comment]
I'm thinking your second option. Adding some brief text to the LocalDevelopment.md and a link to Docker-Tooling. I think it's best to keep that information in the main repo, it's pretty technical.

**Comment by bitcoinshirt** [comment]
Alright, agreed, let's do that.
I'm thinking should we put it as a `Docker` under deployments 
![screen shot 2018-12-09 at 10 17 05](https://user-images.githubusercontent.com/36959754/49695449-99954780-fb9b-11e8-9180-c115f5ad34b5.png)
Or what you said, the link in Local development.md

**Comment by bitcoinshirt** [comment]
I still have no idea where to put Docker.
Should we put a link to docker repo in deployment or development?
I think once we have better documented manual VPS deployment it'll probably be on Docker.
@NicolasDorier Can you help on this dilemma?

**Comment by bitcoinshirt** [comment]
Ugh, I need to improve my memory and stop complicating things.
There's a file docker.deployment.md where we link to to the resource, no need to overcomplicate stuff, sorry my bad.
