### ISSUE TITLE
Add info to docs about using BTCPay with other services

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#853]
A lot of comments in the chat come from users with BTCPay on things like MyNode, Umbrel, Raspiblitz, etc. We should mention in docs that all of these are different ways of implementing BTCPay and we are not able to answer questions about those setups. 

Discussed in [this docs meeting](https://github.com/btcpayserver/organization/issues/23). Talked about adding this disclaimer to Hardware As a Service document.

**Comment by Zaxounette** [comment]
Relates to Hardware-as-a-wallet. 
I'll self assign.
