### ISSUE TITLE
Fix 'what if I have an issue paying an invoice' FAQ

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#855]
[FAQ Question](https://docs.btcpayserver.org/FAQ/FAQ-General/#what-if-i-have-a-problem-paying-an-invoice)

This page tells them to edit the wallet and add a -[p2sh] to the end, but we need to explain that this means it will become an entirely new wallet. 

- If they are using it as a hot wallet, their seed won't be stored with the change
- If they imported it from another wallet, their wallet wont track these payments and the addresses generated
- Old funds wont be available in the wallet feature

[Comment from chat](https://chat.btcpayserver.org/btcpayserver/pl/37s8k8k65jyj8fbc6jfgwgkqgw)

**Comment by Zaxounette** [comment]
In addition to this info, we would need more:

The seed isn't stored with the change: What does that mean ? 
It becomes a hot wallet ? It becomes a "seedless" address ? Else ?

**Comment by Kukks** [comment]
> In addition to this info, we would need more:
> 
> The seed isn't stored with the change: What does that mean ?
If you generated the wallet using the generate wallet option and ticked the "Is Hot wallet" or the "import to rpc" feature, they will now no longer be enabled.
