### ISSUE TITLE
BTCPay WooCommerce Installaton Infographic

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver-doc#86]
Not sure if it will look good or if it's doable, but I'm gonna give this one a try. Leaving it here as a reminder.

**Comment by bitcoinshirt** [comment]
Feedback welcome.

![btcpaywoocommerceinfographic](https://user-images.githubusercontent.com/36959754/47844662-3d345080-ddc3-11e8-98c3-c54704527cd3.png)

**Comment by slack333** [comment]
Please read Section 1 Writing error.

**Comment by bitcoinshirt** [comment]
thanks @slack333 uploaded replaced with a new image
