### ISSUE TITLE
Layout seems to break when searching via mobile 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver-doc#864]
White space at the side... after a search on iPhone 📲 iOS first time I noticed this bug when searching docs just now!! @dennisreimann 

![F4A2FC97-6EEC-4E8B-8972-C6DB24370846](https://user-images.githubusercontent.com/30862925/110225318-678b0100-7edc-11eb-98a9-7c111be0c4e8.png)
![0BC9A960-6E52-438B-B695-9D361361FFE6](https://user-images.githubusercontent.com/30862925/110225319-68bc2e00-7edc-11eb-822e-b7f6f36c0736.png)

**Comment by dennisreimann** [comment]
@Eskyee Can you verify my fix works for you? I couldn't reproduce it on the Local Dev page, but on another one where it is fixed now.

**Comment by Eskyee** [comment]
Yes no problem..  can I check it via my mobile, as that’s how I spotted the white space...  send link !!

**Comment by Eskyee** [comment]
Yes thanks 🙏 fixed in my iOS iPhone 
Good job 

![B187B00D-A9E6-4CA1-B262-3A269D7BD2FA](https://user-images.githubusercontent.com/30862925/110249226-1b3bd180-7f6d-11eb-958b-86ff70d4d8ba.png)
