### ISSUE TITLE
Deployment Decision Infographic

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#87]
As we develop more options for implementing BTCPayServer, I think it could be helpful for new users to have a way to determine which solution is best for them. Lately people have been asking questions in the Slack where they are using multiple tutorials at once that can't be used together. 

I was thinking we could create an infographic decision tree that shows which deployment methods will be best suited for the user depending on their needs and links? to skip to different parts in the process. If any one has ideas about how to organize the info, feel free to change/add. Since developers can make these decisions on their own, I think it should be more Newbie friendly...

**Some of these could be:**

-You need to build a website
-You already have a website
-You care about price / hosting Providers
-You want to use a 3rd Party BTCPay Host
-You want to make a simple donation page
-Hardware deployment options 
-You want developer capability / manual builds
-You want to use the Lightning Network

**Comment by britttttk** [comment]
Yes I think that's a good idea like pros and cons. Not shilling but like how to choose.. other than just saying it's easy or hard.

**Comment by britttttk** [comment]
@bitcoinshirt it doesn't need to be a tree. I just called it this to get the idea across. For links, I mean't more like QR codes like how you did on your WooCommerce infographic but it does take up a lot of space... so you are probably right, we should skip them. 

I'll work on writing up pros and cons for deployment methods.

**Comment by bitcoinshirt** [comment]
@britttttk Good idea, try to make it concise and stick to the facts, so that people can decide. You can determine criteria like:

- Skill Level (probably need a better term here)
- Pricing
- etc

**Comment by britttttk** [comment]
|                 Web Solutions            |                1.            |     2.     |   Why?       |     
| ---------------------------------------- |:----------------------------:|:----------:|:------------:|
| Business <br> (Fast Setup)               | 3rd Party <br> BTCPay Hosts  |Web-Wizard  |- Low Difficulty <br> - BTCPayServer Support (1) <br> - Lightning Network (2) |
| Cost                                     | Free / Pay                   | 10 USD / mo| BTC Accepted |

<br>

|                 Cloud Solutions       |                1.            |     2.     |   Why?  | 
| ------------------------------------- |:----------------------------:|:----------:|:-------:|
| Business <br> (Self Setup)            | Google <br> Cloud            | Microsoft <br> Azure |- Moderate Difficulty <br> - Docker Compose Build <br> - Lightning Network        |
| Cost                                  | 70 USD / mo                  | 60 USD / mo|BTC Not Accepted   |

<br>

|           Hardware Solutions         |                1.          |     2.     |   Why?   |   
| ------------------------------------ |:--------------------------:|:----------:|:--------:|
| Business <br> (Hardware Setup)       |Ready Out Of <br> The Box   |  Installation & <br> Consultation | - Prices Vary By Service <br> - BTCPayServer Support <br> - Lightning Network|
|                                      |                            |            |BTC Accepted|

<br>

|           Developer Solutions          |              1.     |    2.             |   3.         |    
| -------------------------------------- |:-------------------:|:-----------------:|:------------:|
| Developer <br> (Testing Setup)         | Manual Install  | Manual Build | Manual Hardware Build |
| **Not Recommended <br> For New Users**   | Install From <br> Command Line |   Build Without <br> Docker Image | Build / Install in <br> Hardware Environment |

**Comment by bitcoinshirt** [comment]
Great concept. This can easily be embedded into docs and I can make an infographic out of it. Maybe insert a relative link to each of the deployment methods in the table?

By the way, there's also a way to manually deploy LunaNode, so LunaNode can be placed in both cloud and web solutions. I think we need to put * on LunaNode Web-Deployment and clarify that while it's deployable from an easy-web interface, it's basically a VPS, or as you named it "Cloud solution".

And maybe also mention that BTCPay is not limited to these and can be deployed on any VPS that meets the minimal requirements.

**Comment by britttttk** [comment]
@bitcoinshirt Thx for feedback. I changed it, see above. I don't know where to put this into the docs... 

I was thinking, what about changing the page: "Getting Started" to "After Deployment" and creating a more general getting started page. There is a lot of great getting started info in the FAQ page that could be moved maybe related to your Issue #88

**Comment by bitcoinshirt** [comment]
@britttttk  I've been thinking that we need a deployment.md to explain and link to all the methods, so perhaps there, some sort of a deployment readme?

Great suggestion. I agree about getting started document, don't like how it sounds as well. We'd have to edit already added links as well. 

It appears you have a much better idea how to structure those pages, can you open an issue for that specific fix and feel free to tackle it.

**Comment by britttttk** [comment]
Ok sounds good I will work on:
- creating a deployment doc issue and PR
- change the gettingstarted.md doc to afterdeployment.md & update links

If you want to close this issue for the infographic that's up to you. I'm fine with closing it for now since deployment.md will be a new issue.

**Comment by bitcoinshirt** [comment]
Awesome! Closing this one now. I'll then focus on FAQ entirely and cleaning things up. Let's do this.
