### ISSUE TITLE
Improve BTCPay Frequently Asked Questions and Common Issues

### ISSUE THREAD

**Issue by anonymoustrident** [btcpayserver/btcpayserver-doc#870]
I could not find the information I was looking for on the "BTCPay Frequently Asked Questions and Common Issues" page (`/FAQ/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

Hi, I have issues with using the BTCpayServer Modal on mobile. It works fine on web app but it’s not reactive when it’s view on the same website when view from mobile. Any idea? Browser used was both chrome and safari on iOS. Web works fine.

**Comment by dennisreimann** [comment]
This sounds more like a bug report than request for better documentation, am I correct?

**Comment by pavlenex** [comment]
visit https://chat.btcpayserver.org/ for support
