### ISSUE TITLE
Is there a event that triggers when payment is completed something like window.btcpay.onpaymentcompleted()?

### ISSUE THREAD

**Issue by jediiry** [btcpayserver/btcpayserver-doc#871]
I could not find the information I was looking for on the "Using the BTCPay API for Custom Integration" page (`/CustomIntegration/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by Kukks** [comment]
Literally mentioned right before the issue creation button. 
![image](https://user-images.githubusercontent.com/1818366/111632263-96667880-87f4-11eb-8535-b27c5209cce5.png)
