### ISSUE TITLE
Re-Structure FAQ

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver-doc#88]
Right now we have lots of good information scattered around and it would be a good idea to consolidate and categorize them.

My suggestion is to have three types of documents:

1. [FAQ.md ](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ.md)- General BTCPay questions which are more about navigation, options, features.
2. Troubleshooting.md #48 - Document that will describe how users can troubleshoot a certain problem and get help. This is more general information document rather than coding instructions.
3. Common Issues - This will be a huge document with all the technical issues categorized. The goal is to provide code so that people can use. I propose we take a look at FAQ and the Wiki to create categories and structure the questions. For instance, - Synchronisation - all questions about the sync (why it's needed, how long it takes, what to do if it's stuck.

The 3. document will potentially take time and we'll need to think of the "categories" for the issues. The easiest is to just take a look at NBitstack Wiki and try to group similar issues.

Thoughts?

**Comment by bitcoinshirt** [comment]
## Wallet
 
- [Can I use Bitcoin Core wallet with BTCPay Server?](https://nbitstack.com/t/can-i-use-a-bitcoin-core-wallet-with-btcpayserver/33)
- [What gap limit is optimal?](https://nbitstack.com/t/how-to-make-sure-that-the-gap-limit-in-btcpay-is-picked-up-by-my-wallet/59)

## Apps

- [How can I use BTCPay in a physical store?](https://nbitstack.com/t/how-can-i-change-the-currency-from-usd-to-some-other-fiat-currency-and-use-btcpay-as-a-physical-pos/38)
- [Is there a Point of Sale feature in BTCPay?](https://nbitstack.com/t/is-there-a-pos-feature-for-btcpayserver/47/3)
- [How to get sucessful payment notification if I'm not using e-commerce software](https://nbitstack.com/t/how-can-i-be-notified-about-btcpay-payment-if-im-not-using-e-commerce-software/63/2)

## Lightning Network

### LND
- [How many Zap Wallets can I connect to BTCPay at simultaneously?](https://nbitstack.com/t/how-many-zap-wallets-can-be-connected-to-a-btcpay-server-ln-simultaneously/45/4)
- [Error /root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory](https://nbitstack.com/t/btcpay-lnd-error-root-lnd-data-chain-bitcoin-mainnet-admin-macaroon-no-such-file-or-directory/68)

## Server Settings

### Maintainance
- [How can I check my BTCPay Server version via terminal? ](https://nbitstack.com/t/is-there-a-pos-feature-for-btcpayserver/47/3)

### Theme / Customization
- [How to customize my BTCPay theme style](https://nbitstack.com/t/how-to-edit-the-styling-of-btcpay-front-page/65/3)
- [How to add Google Analytics code to BTCPay](https://nbitstack.com/t/how-can-add-google-anlytics-tags-to-my-btcpay-server/64/3)

## Stores

- [Error: You need to configure the derivation scheme in order to create an invoice](https://nbitstack.com/t/i-cant-create-an-invoice-in-btcpay/46)
- [Consider the invoice confirmed when the payment transaction](https://nbitstack.com/t/consider-the-invoice-confirmed-when-the-payment-transaction-in-btcpay/61)

## Developers
### API
- [StatusCodeError: 400 - {“error”:“You need to specify storeId (in your store settings)”}](https://nbitstack.com/t/btcpay-error-unhandled-rejection-statuscodeerror-400-error-you-need-to-specify-storeid-in-your-store-settings/55)
### Altcoins
- [How to implement a new altcoin to BTCPay Server?](altcoin.md)
- [How to add an altcoin to my existing BTCPay deployment?](https://nbitstack.com/t/how-do-i-set-up-additional-cryptocurrencies-on-btcpayserver/58/3)

## Integrations
### WooCommerce
[How to configure order statuses in BTCPay?](https://nbitstack.com/t/how-to-set-up-order-statuses-in-woocommerce-and-btcpay/67/2)

**Comment by britttttk** [comment]
I think splitting them is a good idea. 'CommonIssues.md' is a good name. Hopefully users will start seeing and using NBitStack from finding their questions in these docs.

**Comment by bitcoinshirt** [comment]
I will focus on restructuring the FAQ #90 . Troubleshooting should be a separate document, independent of FAQ folder. I'm merging FAQ and what we referred to as "common issues into neatly structured FAQ folder.

**Comment by bitcoinshirt** [comment]
TODO
- [ ] Stores FAQ 
- [ ] Integrations FAQ
- [ ] Developers FAQ / API FAQ
- [ ]  Bitcoind FAQ
- [ ] Altcoins FAQ

**Comment by bitcoinshirt** [comment]
FINISHED!!!
