### ISSUE TITLE
Document btcpay-clean.sh command

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#880]
`btcpay-clean.sh` command isn't documented in https://github.com/btcpayserver/btcpayserver-docker#tooling

Would be cool to add it. Submitting the issue in this repo, since we pull info from it.

**Comment by Zaxounette** [comment]
Confirm this for me, so that I can document it without mistakes:

`btcpay-clean.sh` Terminates unused docker processes and removes them ? DB as well ?

In the chat you give the examples of the altcoins, so it can become an example in the docs as well.
`This is particularly useful for users that switch from the Altcoin Build to the Bitcoin Build. `

**Comment by pavlenex** [comment]
Let's keep it simple, it purges unused images. 

If you check the code https://github.com/btcpayserver/btcpayserver-docker/blob/master/btcpay-clean.sh

You'll see it performs `docker image prune -a` which does this according to [this](https://devopsheaven.com/docker/volumes/purge/devops/2018/05/25/purge-docker-images-containers-networks-volumes.html).

```
Delete Docker unused images

Finally, part of the current tagged images could be not used. Docker provides a command to purge these unused images as well (previous dangling images included):

```

**Comment by Zaxounette** [comment]
Thanks !

**Comment by britttttk** [comment]
[similar example](https://chat.btcpayserver.org/btcpayserver/pl/aosmt1kch7n13yt6x3fjrd5adc) for transmuter @Zaxounette

**Comment by Zaxounette** [comment]
See PR [#454](https://github.com/btcpayserver/btcpayserver-docker/pull/454) in btcpayserver-docker repository for review of this issue.

You said to keep it simple Pav, so I kept it simple.

cc @britttttk @pavlenex
