### ISSUE TITLE
Update header images

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#889]
In https://github.com/btcpayserver/btcpayserver/pull/2412 we've restyled our header.
While not critical, we'd probably want to replace the images that consis header for consistency and to avoid confusion.

**Comment by Zaxounette** [comment]
Just did an "inventory" of the number of images containing the soon-to-be outdated header.

Per folder:
`img`: 12
`contribute`: 0
`createwallet`: 1
`hotwallet`: 1
`infographics`: 0
`invoice`: 0
`notifications`: 0
`payjoin`: 3
`payment-requests`: 0
`point-of-sale`: 0
`pull-payments`: 0
`shopify`: 0
`smtp`: 0
`wallet`: 0
`wasabi`: 0

It is to note that, for example in the `img` folder, only 12 have the related header, but if one image is updated, we'll need to update all of the images relating to the "series".
I stopped counting at 40+ images total in that context.

**Comment by pavlenex** [comment]
Closing this as new navigation will require revision, so a new issue will be required
