### ISSUE TITLE
Improve Using the BTCPay API for Custom Integration

### ISSUE THREAD

**Issue by itsaphel** [btcpayserver/btcpayserver-doc#892]
I could not find the information I was looking for on the "Using the BTCPay API for Custom Integration" page (`/CustomIntegration/`).

Two questions:

1. What is the `BTCPAY_URL`? Is it just the domain? Or is it the store URL? Or something else? A specific example URL would help.
2. Assuming `BTCPAY_URL` is just the BTCPayServer instance: then if `Allow anyone to create invoice` is enabled (in `General settings` of the store), how does the API request know which store to create the invoice under? Surely the store must be provided as a parameter or as part of the URL? But this isn't documented on the page. It can't be the same request as if it were BitPay because (as the doc says) "Bitpay only allows one account for one merchant, BTCPay allows a user to manage multiple stores."

**Comment by Kukks** [comment]
Bitpay api is only meant to allow interoperability with older integrations. We now offer the greenfield API whichis a superior experience with way wider featuresets.See https://docs.btcpayserver.org/API/Greenfield/v1/ or /docs on your own btcpay install.

**Comment by Kukks** [comment]
The `Allow anyone to create invoice` option is really only meant for the Pay Button. It is not meant for broad application development integration and should be discouraged

**Comment by itsaphel** [comment]
@Kukks To clarify/add context: I have a BitPay marketplace integration and am just looking to easily convert it into a BPS integration. My hurdle is that whereas BitPay let's you easily issue API tokens for "POS" usage only without needing to go through the pairing code process, BPS doesn't.

**Comment by Kukks** [comment]
> @Kukks To clarify/add context: I have a BitPay marketplace integration and am just looking to easily convert it into a BPS integration. My hurdle ([btcpayserver/btcpayserver#2451](https://github.com/btcpayserver/btcpayserver/issues/2451)) is that whereas BitPay let's you easily issue API tokens for "POS" usage only without needing to go through the pairing code process, BPS doesn't. But I feel like the docs are unclear on the two points above, as well.
> 
> I can imagine the option is undesirable, but so long as it exists it should be documented how it works right (or deprecated?)

There is an option to create a "legacy" bitpay key that sounds  like what you are describing
