### ISSUE TITLE
Improve BTCPay Server Apps

### ISSUE THREAD

**Issue by spinbackwards** [btcpayserver/btcpayserver-doc#894]
I could not find the information I was looking for on the "BTCPay Server Apps" page (`/Apps/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

I would like to use BTCPay for tips. So the person leaving the tip would decide how much to tip me.

Is this possible?

**Comment by britttttk** [comment]
hey @spinbackwards yes it is very common to accept tips using BTCPay. There are a few ways to do this. Please checkout [this blog article](https://blog.btcpayserver.org/how-to-accept-bitcoin-donations/) for a few ideas.

However the two main ways to do this are: 
1) embedded payment button in a website
2) Point of sale app with the option selected for the user to input any amount

**Comment by britttttk** [comment]
![image](https://user-images.githubusercontent.com/39231115/114290712-c2b19580-9a3e-11eb-8281-aedcf1c610d3.png)

**Comment by spinbackwards** [comment]
Beautiful!

You need a BTCPay Server so I can give you some Sats for your help!

peace and love,

**Comment by Zaxounette** [comment]
> You need a BTCPay Server so I can give you some Sats for your help!

Hey @spinbackwards !
If you wish, you can tip @britttttk here: [btcpayserver.org/donate](https://btcpayserver.org/donate/). 
She's listed with the same name and same profil pic, you can't miss it.

**Comment by spinbackwards** [comment]
I sent Sats. Love it.
We’re using BTCPay Server.
peace and love,

**Comment by Zaxounette** [comment]
Thanks for the support !

**Comment by spinbackwards** [comment]
You’re welcome!

Do you recommend Lunanode as the easiest way to go for self-hosted?

Are there other choices?

Paul Kulas
human 
<self-aggrandizing statement omitted>
heyheyrenee.com
970.331.6404
Eagle, CO

On April 10, 2021, britttttk ***@***.***> wrote:
> Thanks for the support !
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/btcpayserver/btcpayserver-
doc/issues/894#issuecomment-817268088>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ATH4TDTBR4XYFS73OZ4Z3CLTIFKLJANCNFSM42XE3YQA>.

**Comment by Zaxounette** [comment]
Lunanode is definitely the easiest, but there are other deployment methods that aren't that complicated either.
See the docs here: https://docs.btcpayserver.org/Deployment/
