### ISSUE TITLE
Update Cold Card wallet videos for wallet ui updates

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#896]
Looking at [these videos](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/ColdCardWallet.md), they are quite old.

Making a separate issue for this from #881

**Comment by Zaxounette** [comment]
I don't have a coldcard. I'm out on this one.

**Comment by pavlenex** [comment]
Maybe @nvk can help and send you one?

**Comment by Zaxounette** [comment]
> Maybe @nvk can help and send you one?

A video or a coldcard ?

**Comment by nvk** [comment]
Happy to, just need your email.

**Comment by britttttk** [comment]
Those videos are also linked [here under the btcpay category](https://coldcardwallet.com/docs/) we might want to ping when this is complete if the YT links change

**Comment by pavlenex** [comment]
@Zaxounette Were there any progress on this? Have you received your coldcard and do you still intend to improve a video?

**Comment by Bangalisch** [comment]
This one got closed with PR https://github.com/btcpayserver/btcpayserver-doc/pull/1239
