### ISSUE TITLE
Improve Deploying BTCPay - LunaNode Web-Wizard - Modify Env Vars

### ISSUE THREAD

**Issue by Chris869218** [btcpayserver/btcpayserver-doc#903]
I could not find the information I was looking for on the "Deploying BTCPay - LunaNode Web-Wizard" page (`/LunaNodeWebDeployment/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

I was hoping to find a resource for how to enable keysend on my lnd-based BTCPay Server instance (setup via the LunaNode Web-Wizard). If such a resource exists, including a link on this page would be great.

**Comment by britttttk** [comment]
hey @Chris869218 thanks for the suggestion to make this more clear.

For now, you can add it the same way you would as any of the [other environment variables](https://docs.btcpayserver.org/Docker/#generated-docker-compose). Here an a [generic example of how to modify](https://docs.btcpayserver.org/FAQ/FAQ-Deployment/#how-can-i-modify-or-deactivate-environment-variables) your environment variables. 

To run those commands you will need to [ssh into your server](https://docs.btcpayserver.org/FAQ/FAQ-ServerSettings/#how-to-ssh-into-my-btcpay-running-on-vps). Your ssh password comes from your LunaNode dashboard..

BE SURE to note that when you add keysend you should do it like this:

`export BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-lnd-keysend"`
(do not forget this part in the line above ---> `$BTCPAYGEN_ADDITIONAL_FRAGMENTS;` it means keep your existing setup AND add keysend.

Feel free to join a [community chat](https://docs.btcpayserver.org/Community/) if you get stuck :)

**Comment by britttttk** [comment]
@Zaxounette we should keep this issue open and add a section to LunaNode doc (maybe?) about how to modify your server after setup. Right now the visibility of the generic env var FAQ is not good. :(

**Comment by Chris869218** [comment]
That was so speedy. Thanks a lot. I assume I need to restart lnd to get the new variable to take effect? Whats the best way to go about that?

**Comment by britttttk** [comment]
```
sudo su -

# Go to the root/btcpayserver-docker directory
cd /root/btcpayserver-docker

export BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-lnd-keysend"

. btcpay-setup.sh -i
```

These are the exact commands @Chris869218, running the setup script in the last step will restart for you. :)

**Comment by Chris869218** [comment]
Worked like a charm! Thanks again for your help.

**Comment by Zaxounette** [comment]
> @Zaxounette we should keep this issue open and add a section to LunaNode doc (maybe?) about how to modify your server after setup. Right now the visibility of the generic env var FAQ is not good. :(

Sounds good to me !
