### ISSUE TITLE
Add troubleshooting information to docs for Vault

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#913]
When this issue comes up in support we basically need to ask the same questions every time to get information about the issue:

- What is the btcpay version
- What is the Vault version
- What is the HW wallet, fw, version, etc.
- What is the browswer/os
- What is the step you are stuck at (connect wallet or spend funds)

Once this data is gathered there are usually the same follow up suggestions.. Refresh browser, refresh wallet, close ledger live, etc...

We should add some of this information to docs so that when a user comes to the chat they can do some basic self troubleshooting on their own before.

**Comment by pavlenex** [comment]
I've added a template for issues in the vault repo a while ago, should be sufficient.
