### ISSUE TITLE
Improve BTCPay Server Walkthrough

### ISSUE THREAD

**Issue by just-john** [btcpayserver/btcpayserver-doc#914]
I could not find the information I was looking for on the "BTCPay Server Walkthrough" page (`/Walkthrough/`).

I need to know how a payment event is joined to an online store transaction.  

eg.  if joe public rocks up to the store, likes something and pays for it, how does the transaction get linked to a specific user?  The payment could come from any user, no?  Is there a unique receiving wallet created per transaction?

thanks

**Comment by Kukks** [comment]
Hey John,
We generate a unique address per payment per invoice and that is how a payment is correlated to a specific invoice.

**Comment by just-john** [comment]
Thank you for the quick reply Kukks,
I found an explanation of this [on one of the FAQs](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/FAQ/FAQ-General.md#how-does-btcpay-create-a-new-address-for-each-invoice), but feel that this information needs a mention / link to more in-depth explanation on the walkthrough page, hence the question.

This is a great project, wish you well :)
thanks

**Comment by Kukks** [comment]
cc @britttttk  @Zaxounette

**Comment by Zaxounette** [comment]
> I found an explanation of this on one of the FAQs, but feel that this information needs a mention / link to more in-depth explanation on the walkthrough page, hence the question.

Thanks for this info, will look into it.
