### ISSUE TITLE
Improve Refunds Documentation

### ISSUE THREAD

**Issue by humboldtscabinet** [btcpayserver/btcpayserver-doc#919]
I could not find the information I was looking for on the "Refunds" page (`/Refund/`).

Hello,

So I did a test run on my btcpay on my website. I purchased something off my own website for 40 bucks or so. than I issued myself a refund, and did the process listed on this github. But now it still says awaiting approval under awaiting claims, so not sure where i go from here.

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

**Comment by Zaxounette** [comment]
You should have received a notification in your BTCPay Server UI stating that their is a refund waiting for approval.

In case you don't have the notification, it's under `Wallet` > `Pull Payments`. You'll see all the refunds that are awaiting for approval.

**Comment by Kukks** [comment]
So there is a flow to refunds:
* As a merchant, you create a pull payment (also known as a refund request)
*  You share the URL of the pull payment with the user you wish to refund
*  The user inputs an address and the amount to receive on it (a user may wish to split a refund into multiple parts). This is called a Payout
* You, as a merchant need to approve or reject a payout ( in a future version, payouts can be optionally automatically approved)
* You, as a merchant then can batch send the payments to all approved payouts in one transaction (saves you fees)

**Comment by britttttk** [comment]
> So there is a flow to refunds:
> 
> * As a merchant, you create a pull payment (also known as a refund request)
> * You share the URL of the pull payment with the user you wish to refund
> * The user inputs an address and the amount to receive on it (a user may wish to split a refund into multiple parts). This is called a Payout
> * You, as a merchant need to approve or reject a payout ( in a future version, payouts can be optionally automatically approved)
> * You, as a merchant then can batch send the payments to all approved payouts in one transaction (saves you fees)

This issue should remain open to improve the [refunds documentation](https://docs.btcpayserver.org/Refund/#refunds) with this info and any other questions @humboldtscabinet has. 

Thanks for opening the issue :)

**Comment by Bangalisch** [comment]
I will do this :) <3
