### ISSUE TITLE
Improve and update Walkthrough.md

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#921]
1. Review for any general updates or outdated information
2. Update header image 
3. Improve the Invoices section (ex: link to [invoices.md](https://docs.btcpayserver.org/Invoices/) and mention how merchants associate invoices with orders with no address reuse as mentioned in #914

**Comment by Bangalisch** [comment]
Hey, 

i'll take this on me. 
I've looked trough it for abit, but as on more places, i feel like the video content should wait a lil longer. 
As the dashboard is slowly being build, it might be good to get video content updated once the dash really is filled up. 
Everything else, the new features and fuctions, new views etc im down to update and go trough all that :)

**Comment by pavlenex** [comment]
Done in #1074
