### ISSUE TITLE
Delete references to Hint address input field

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver-doc#928]
In [#2575](https://github.com/btcpayserver/btcpayserver/pull/2575) the hint address input field is being deleted, disabled and forgotten forever.

I found two instances in the docs where the hint address is spoken of:
https://docs.btcpayserver.org/ElectrumWallet/#alternative-setup
https://docs.btcpayserver.org/WasabiWallet/#step-by-step

Issue:
* Update screenshots to reflect the change
* Update wording to delete any mention of `hint address`

**Comment by Bangalisch** [comment]
i will take this on :)

**Comment by Bangalisch** [comment]
@pavlenex i think after merge of 1067 this one can close ?

**Comment by pavlenex** [comment]
Yup, nice catch, closing.
