### ISSUE TITLE
Improve BTCPay Server Wallet

### ISSUE THREAD

**Issue by cybertriton** [btcpayserver/btcpayserver-doc#935]
I could not find the information I was looking for on the "BTCPay Server Wallet" page (`/Wallet/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]
I couldn't find information about multisig wallet used in the BTCPay Server. A merchant usually needs a multisig wallet to manage funds it has received.

**Comment by pavlenex** [comment]
We don't have an interface for multisig atm.

**Comment by britttttk** [comment]
Relates to #669. 

It is only possible to do this with manual xpubs.
