### ISSUE TITLE
Improve BTCPay Server Use Cases

### ISSUE THREAD

**Issue by Slicington** [btcpayserver/btcpayserver-doc#936]
Hello,

I could not find the information I was looking for on the "BTCPay Server Use Cases" page (`/UseCase/`).

[PLEASE DESCRIBE HOW THE PAGE CAN BE IMPROVED]

Hi, I am having trouble laughing BTCPayServer on my domain name and allowing customers to use publicly. I have my own node. I'd like to be able to accept payments online. But I can't quite figure out to get the server public.

I've read the documentation asked around customer supports and YouTube, Telegram groups, etc. I've have used the server to pay myself on a few Lightning invoices. Seems to be working fine but only on my personal network. There might be something wrong with my configuration personally but I've only been following step I've been told to follow.

I was wondering if someone could help me out with this.
Thank you,
Slicington

**Comment by britttttk** [comment]
@Slicington how did you deploy your btcpay?

**Comment by Slicington** [comment]
Hi @britttttk,

I deployed my BTCPay through my myNode device. More information on myNode's website here: https://mynodebtc.com/
I connected to BTCPay Server which seems like it was only accessible to me on my network. I setup my wallets and Store and generated Pay Buttons. Then, the Pay Buttons generated invoice links that only seems to work on my private network. I paid the invoices with my Lightning Wallet... It works great.

***UPDATE***

I have since created a domain name that redirects to this private server. My invoices are now viewable to the public internet. But the only thing is the connection is not secure. My customers will see this message before they're able to see the invoice.
![photo_2021-06-27_23-14-33](https://user-images.githubusercontent.com/86463793/123769482-586afd00-d897-11eb-8325-a9e800c01ec8.jpg) 

To remove this message I need to install my CA issued SSL certificate into my NGINX server. I've tried a couple times but I've misconfigured the system a couple times. I'm a noob to NGINX and configuring SSL certs, and all that.

Does anyone know the proper way to do this?

Thanks,
Slice

**Comment by pavlenex** [comment]
Hi Slicington it seems you're on a good way, but I'm afraid there's little we can do to assist you with MyNode as they're using custom deployment method, so it's better to reach out to them and ask how you can expose BTCPay Server outside of your local network with a proper https.
