### ISSUE TITLE
Add a notice that channels have to be closed when migrating from one implementation to the other (LND>c-lightning and vice-versa)

### ISSUE THREAD

**Issue by Giszmo** [btcpayserver/btcpayserver-doc#937]
I'm hitting limits with cL and would like to switch to LND but [the documentation](https://docs.btcpayserver.org/FAQ/FAQ-LightningNetwork/#how-to-change-from-c-lightning-to-lnd-or-vice-versa) does not mention what to do with my open channels.

Do I have to close my open channels or can I take them with me over to LND?

**Comment by britttttk** [comment]
> Do I have to close my open channels or can I take them with me over to LND?

You need to close them first before switching implementations

**Comment by pavlenex** [comment]
@britttttk I am not 100% sure it needs to be closed, maybe @Kukks knows, regardless we should document this if we haven't.

**Comment by Kukks** [comment]
They are completely separate products/services. Please be sure to close all channels and fully move all funds off (on chain and offchain)

**Comment by Giszmo** [comment]
Thanks. That looks like an important detail to add to the documentation.
