### ISSUE TITLE
Update hot wallet signing considering 1.2.0 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#950]
https://docs.btcpayserver.org/Wallet/#signing-with-a-hot-wallet in 1.2.0 we've added an option that when a hot wallet is created it'll automatically use the seed store on a server to sign. We may want to update that part and also see if there are some updates regarding signing that are required.

**Comment by dennisreimann** [comment]
Depending on how urgent this is, it might make sense to combine it with the upcoming changes in btcpayserver/btcpayserver#2713. Though they are related, this can be tackled on it's own -- just wanted to bring it up, as it would be an opportunity to rework the signing docs as a whole.

**Comment by CypherSkunk** [comment]
I will give this one a go

**Comment by pavlenex** [comment]
Sure, go ahead @CypherSkunk and let us know if you need any help.

**Comment by petzsch** [comment]
@Bangalisch pointed me to this issue.

Can we use this issue to gather some ideas what needs to go into the documentation? I think we should (with the current version) mention that hot wallets might be needed for certain features like the On-chain Payout Processors? (need to check if that info is allready somewhere else)

I don't know did @CypherSkunk start writing something that we can flesh out? (ping)

I would like to open a PR for this one tomorrow  and start writing up something that I see fit.

**Comment by Bangalisch** [comment]
can be closed @pavlenex
