### ISSUE TITLE
Improve Server Settings Frequently Asked Questions - SSH failure to log in.

### ISSUE THREAD

**Issue by brianoflondon** [btcpayserver/btcpayserver-doc#964]
I could not find the information I was looking for on the "Server Settings Frequently Asked Questions" page (`/FAQ/FAQ-ServerSettings/`).

This section:

#Error: Maintenance feature requires access to SSH properly configured in BTCPayServer configuration
Sometimes an issue with Docker can temporarily cause your BTCPay Server's maintenance features to be misconfigured. This issue is typically fixed by restarting your BTCPay Server. Unfortunately when this error appears in the interface, the restart button will be disabled. You will need to restart using ssh to resolve the issue.

## The answer of "restart the docker containers" doesn't fix the issue.

I still get `Maintenance feature requires access to SSH properly configured in BTCPay Server configuration.` in a red box on the Maintenance page of BTCPay Server.

I am able to SSH in to my machine and SU to root though I'm pretty sure the machine I'm using has SSH in directly as root to the whole machine prohibited. Is this causing the issue? If so, more instructions on this would be apprecieated.

In the Docker logs for ` docker logs generated_btcpayserver_1 ` I get the following:

```
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
warn: Configuration:  SSH invalid credentials (Permission denied (publickey).)
warn: Configuration:  Retrying SSH connection in 40 seconds
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
warn: Configuration:  SSH invalid credentials (Permission denied (publickey).)
warn: Configuration:  Retrying SSH connection in 80 seconds
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
warn: Configuration:  SSH invalid credentials (Permission denied (publickey).)
warn: Configuration:  Retrying SSH connection in 160 seconds
```

I may try to check out my SSH settings on this box and see if that fixes this but more instructions would help.

**Comment by britttttk** [comment]
>  though I'm pretty sure the machine I'm using has SSH in directly as root to the whole machine prohibited. Is this causing the issue?

Maybe.. How did you deploy your server?
