### ISSUE TITLE
Improve Translating BTCPay Server

### ISSUE THREAD

**Issue by AdiuvoInc** [btcpayserver/btcpayserver-doc#969]
I could not find the information I was looking for on the "Translating BTCPay Server" page (`/Contribute/Translate/`).

How to apply an existing translation into my server?

**Comment by britttttk** [comment]
Hey @AdiuvoInc currently only the invoice pages (where the user pays) are translated. The actual BTCPay Server (where you log in and check you wallet balance, etc.) is not available for translation at this time. That functionality has been a work in progress for some time now: https://github.com/btcpayserver/btcpayserver/pull/972

**Comment by AdiuvoInc** [comment]
> 
> 
> Hey @AdiuvoInc currently only the invoice pages (where the user pays) are translated. The actual BTCPay Server (where you log in and check you wallet balance, etc.) is not available for translation at this time. That functionality has been a work in progress for some time now: [btcpayserver/btcpayserver#972](https://github.com/btcpayserver/btcpayserver/pull/972)

Okay, thanks for your help!
