### ISSUE TITLE
Check dark mode render of supporter svgs

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#972]
Check dark mode render of supporter svgs: `Coincards`, `Baillie Gifford`, `PNXBET`

**Comment by dennisreimann** [comment]
What's to be done here? Do they need to be changed? I think we can leave them as they are.

![image](https://user-images.githubusercontent.com/886/137473452-0730a07a-3759-467f-8ff3-59a6483893d1.png)

**Comment by britttttk** [comment]
I think it was a concern was should they all have have the white/black backgrounds, or should the background be transparent like some of the others. Idea of @Zaxounette will defer on this one.

**Comment by pavlenex** [comment]
@dennisreimann @britttttk is this one addressed? Not really sure by looking at the doc page if it has everything you guys wanted. If it is, we can close this one then.

**Comment by dennisreimann** [comment]
@pavlenex Nope. I still need to take care of this one :)

**Comment by Zaxounette** [comment]
Pav, the PR linked above was "reversed" by https://github.com/btcpayserver/btcpayserver/pull/3001 following a comment you made.
