### ISSUE TITLE
New docs homepage and ux

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#974]
- [ ] Homepage: Replace BTCPay Server Architecture button with button to Contribute docs
- [ ] UX bug: Left of left nav bar scrolling will scroll the page (on the right) @dennisreimann
- [ ] Investigate failed circle ci label on docker introduction page. Should we remove it? Seems it has been failed for a while.
- [ ] Change Deployment.md warning from red to orange label and move lower on the page (below diagram image)

**Comment by Zaxounette** [comment]
@dennisreimann It's regarding the following:

![wQzZSusIho](https://user-images.githubusercontent.com/51208677/137355350-6ed37611-b9fa-4c73-8472-a0e504c59d5a.gif)
