### ISSUE TITLE
Extract developers docs from user guide 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-doc#975]
- [ ] Extract dev content from Integrations custom integration: keep pairing in user guide, move modal checkout & code
- [ ] Move PayJoin spec from user guide to dev docs More Info section
- [ ] Troubleshooting issues Keep ui troubleshooting in User Guide, move logs, cli, docker etc. to dev docs (i.e. move sections 1.3 & 2)

**Comment by pavlenex** [comment]
@britttttk What's the progress on this one any blockers?
