### ISSUE TITLE
Improve Introduction

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver-doc#979]
I could not find the information I was looking for on the "Introduction" page (`/Docker/`).

maybe this will be useful for some people who put their btcpayserver behind CDN, which do HTTPS handling for them. If they get ERR_TOO_MANY_REDIRECTS error on any URL, then probably they need to remove support for https nginx:

```
export BTCPAYGEN_EXCLUDE_FRAGMENTS="nginx-https"
. btcpay-setup.sh -i
```

and problem is solved

**Comment by pavlenex** [comment]
@2ge Where would you add this piece of information? How about FAQ?

**Comment by 2ge** [comment]
maybe to FAQ.
