### ISSUE TITLE
How to restore a backup? It's not mentioned in the docs.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#981]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/2928

<div type='discussions-op-text'>

<sup>Originally posted by **woutersamaey** September 29, 2021</sup>
The docs tell us how to backup on page https://docs.btcpayserver.org/Docker/#how-can-i-back-up-my-btcpay-server, but it does not mention how to do a restore.

Backup up without a restore procedure isn't very handy.

Can anyone comment on this so we can improve the docs?</div>

**Comment by woutersamaey** [comment]
More than documenting, we need a better way of backing up altogether…
