### ISSUE TITLE
Revise `Explore by topic` section on the docs homepage and make sure we feature the most important topics

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#994]
The Explore by topic page should be revised and we should discuss which articles we'd like to feature and in what order.

**Comment by pavlenex** [comment]
![Screenshot 2022-03-23 at 19 18 50](https://user-images.githubusercontent.com/36959754/159768814-b9835005-32ce-49ff-acd2-71c748796977.png)

- What is BTCPay and how it works?
- Getting Started
- FAQ

....

**Comment by Bangalisch** [comment]
Yoo 

What if we do the top three (left to right) about BTCPay Server the what/why/how. 

What is BTCPay Server? 
https://docs.btcpayserver.org/Guide/

Why BTCPay Server?
https://docs.btcpayserver.org/UseCase/

How to deploy BTCPay Server?
https://docs.btcpayserver.org/TryItOut/

Then the second row (left to right) be about the main function/features that one would set up.

Wallet Setup 
https://docs.btcpayserver.org/WalletSetup/

Lightning Network setup 
https://docs.btcpayserver.org/LightningNetwork/

How to setup POS 
https://docs.btcpayserver.org/Apps/#point-of-sale-app

And have the bottom row left for Api docs/faq /contributing; 

Greenfield Api 
https://docs.btcpayserver.org/API/Greenfield/v1/

FAQ 
https://docs.btcpayserver.org/FAQ/

Contribute 
https://docs.btcpayserver.org/Contribute/

**Comment by pavlenex** [comment]
Done ✅  in https://github.com/btcpayserver/btcpayserver-doc/pull/1166
